### ISSUE TITLE
Issue - 500 error kode instead of code 400 -> validationsrules #920

### ISSUE THREAD

**Issue by IreneDataHub** [Energinet-DataHub/geh-charges#1044]
Hej
Se filen som angiver de forhold (side 1 til 4)hvor jeg får fejlkode 500 i forhold til skemavalidring jf. #920. Jeg vil umiddelbart forvent at der skulle komme en kode 400 samt en fejlbeskrivelse de steder også, men det håber jeg I kan vurdere på. 
I kan derudover se hvad jeg har kontrolleret for fra side 5 og nede, hvor det er gået godt mht. fejlkode 400.
[https://app.zenhub.com/files/345465244/6c677ace-04fa-4294-b3d2-a479b2e21831/download]

**Comment by PerLysemose** [comment]
Alex from Titans is currently looking at this bug

**Comment by IreneDataHub** [comment]
After validation rules had been updated with version 1.0.8 ( PR # 1057) with the new forms, I have made the review again, and everything is working as expect (code 400).

[https://app.zenhub.com/files/345465244/ee094cfe-0988-4919-bde8-b4a21d62ad62/download](https://app.zenhub.com/files/345465244/ee094cfe-0988-4919-bde8-b4a21d62ad62/download)
