### ISSUE TITLE
Issue VR.507-2  - expecting as a possible "charge whitout prices/only masterdata " but rejecing with code E87

### ISSUE THREAD

**Issue by IreneDataHub** [Energinet-DataHub/geh-charges#1050]
After test to sen a charge with only masterdata, I got a VR.507 "The number of prices 0 for charge Charge1 doesn't match period type P1M", but I expect it is possible to send a messager with only masterdata for charge

Request:

<cim:RequestChangeOfPriceList_MarketDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cim="urn:ediel.org:structure:requestchangeofpricelist:0:1" xsi:schemaLocation="urn:ediel.org:structure:requestchangeofpricelist:0:1 urn-ediel-org-structure-requestchangeofpricelist-0-1.xsd">
	<cim:mRID>DocId{{$isoTimestamp}}</cim:mRID>
	<cim:type>D10</cim:type>
	<cim:process.processType>D18</cim:process.processType>
	<cim:businessSector.type>23</cim:businessSector.type>
	<cim:sender_MarketParticipant.mRID codingScheme="A10">8100000000030</cim:sender_MarketParticipant.mRID>
	<cim:sender_MarketParticipant.marketRole.type>DDM</cim:sender_MarketParticipant.marketRole.type>
	<cim:receiver_MarketParticipant.mRID codingScheme="A10">5790001330552</cim:receiver_MarketParticipant.mRID>
	<cim:receiver_MarketParticipant.marketRole.type>DDZ</cim:receiver_MarketParticipant.marketRole.type>
	<cim:createdDateTime>2022-01-07T08:28:09Z</cim:createdDateTime>
	<cim:MktActivityRecord>
		<cim:mRID>OpId{{$isoTimestamp}}</cim:mRID>
		<cim:ChargeGroup>
			<cim:ChargeType>
				<cim:chargeTypeOwner_MarketParticipant.mRID codingScheme="A10">8100000000030</cim:chargeTypeOwner_MarketParticipant.mRID>
				<cim:type>D01</cim:type>
				<cim:mRID>Charge1</cim:mRID>
				<cim:name>Charge Sub Name</cim:name>
				<cim:description>The charge description</cim:description>
				<cim:priceTimeFrame_Period.resolution>P1M</cim:priceTimeFrame_Period.resolution>							
				<cim:effectiveDate>2020-05-31T22:00:00Z</cim:effectiveDate>
				<cim:VATPayer>D01</cim:VATPayer>
				<cim:transparentInvoicing>false</cim:transparentInvoicing>
				<cim:taxIndicator>false</cim:taxIndicator>
			</cim:ChargeType>
		</cim:ChargeGroup>
	</cim:MktActivityRecord>
</cim:RequestChangeOfPriceList_MarketDocument>

Peek:

<?xml version="1.0" encoding="utf-8"?>
<cim:RejectRequestChangeOfPriceList_MarketDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cim="urn:ediel.org:structure:rejectrequestchangeofpricelist:0:1" xsi:schemaLocation="urn:ediel.org:structure:rejectrequestchangeofpricelist:0:1 urn-ediel-org-structure-rejectrequestchangeofpricelist-0-1.xsd">
    <cim:mRID>d7346243a039437c8a9dbd8a05d1435c</cim:mRID>
    <cim:type>D11</cim:type>
    <cim:process.processType>D18</cim:process.processType>
    <cim:businessSector.type>23</cim:businessSector.type>
    <cim:sender_MarketParticipant.mRID codingScheme="A10">5790001330552</cim:sender_MarketParticipant.mRID>
    <cim:sender_MarketParticipant.marketRole.type>DDZ</cim:sender_MarketParticipant.marketRole.type>
    <cim:receiver_MarketParticipant.mRID codingScheme="A10">8100000000030</cim:receiver_MarketParticipant.mRID>
    <cim:receiver_MarketParticipant.marketRole.type>DDM</cim:receiver_MarketParticipant.marketRole.type>
    <cim:createdDateTime>2022-01-14T10:57:54Z</cim:createdDateTime>
    <cim:reason.code>A02</cim:reason.code>
    <cim:MktActivityRecord>
        <cim:mRID>51f299fc8a524a09b42fb449f4270eb2</cim:mRID>
        <cim:originalTransactionIDReference_MktActivityRecord.mRID>OpId2022-01-14T10:57:06.559Z</cim:originalTransactionIDReference_MktActivityRecord.mRID>
        <cim:Reason>
            <cim:code>E87</cim:code>
            <cim:text>The number of prices 0 for charge Charge1 doesn't match period type P1M</cim:text>
        </cim:Reason>
    </cim:MktActivityRecord>
</cim:RejectRequestChangeOfPriceList_MarketDocument>

**Comment by prtandrup** [comment]
Duplicate of #1072
