### ISSUE TITLE
Different problems when sending requests with either empty or whitespace values

### ISSUE THREAD

**Issue by prtandrup** [Energinet-DataHub/geh-charges#1070]
Submitting requests to the Charges domain with **empty -** or **whitespace values** are problematic

Mostly they results in the actor receiving a StatusCode 500 - internal server error
And in one case, the whitespace value is allowed, but will cause a problem downstream between charges and messagehub (message hub throws an exception as GLN is missing).

We need a solution to these whitespace and empty value problems, which returns a useful rejection to the sender.

COO: According to TI, we are not allowed to cleanup spaces. 

#### Observations: 

* (VR.223) Submitting empty or whitespaces as ChargeOperationId (cim:mRID) => StatusCode 500; System.InvalidOperationException => (Cannot ReadValueAs when there is no value (CanReadValue is false).)
* (VR.424) Submitting 'D02' in cim:process.processType => status 500.
* (VR.449) Submitting whitespaces as ChargeType => StatusCode 500; System.InvalidOperationException => (Cannot ReadValueAs when there is no value (CanReadValue is false).)
* (VR.912) Submitting a schema valid value (P1Y) for Charge Prices only (D08) => StatusCode 500. Problem lies in the `ChargeCommandBundleConverter.cs` in conjunction with `public static string Map(Resolution resolution)` in the `ResolutionMapper.cs`

**Comment by PerTHenriksen** [comment]
VR912 to be addressed, afterwhich the bug is ready for product backlog

**Comment by prtandrup** [comment]
VR.912 issue still relevant. Added a few notes to it. Moved to product backlog

**Comment by prtandrup** [comment]
Removed below, as they are no longer relevant:

* ~~(VR.150) Submitting whitespaces as sender GLN => causes invalid data available => exception in post office: GLN must be filled.~~
* ~~(VR.153) Submitting whitespaces as receiver GLN => StatusCode 500; System.InvalidOperationException => Cannot ReadValueAs when there is no value (CanReadValue is false)~~
* ~~(VR.440) Submitting empty or whitespaces as ChargeId => StatusCode 500; System.InvalidOperationException => (Cannot ReadValueAs when there is no value (CanReadValue is false).)~~

**Comment by x-platformcoder** [comment]
All exceptions thrown as part of parsing the marketdocument is thrown as a synchron B2B message. Values that can be ignored and collected either as a documentvalidation or inputvalidation don't throw a synchron B2B message.

**Comment by IreneDataHub** [comment]
18.11.
space is not covered by the changes - expect b2b errors.
It must also be rejected when codes other than D08 and D18 are used (ie not only D02).
Space in codes - awaiting processing according to new roadmap
Jan looks at the others issue again.

**Comment by x-platformcoder** [comment]
cimfield (blank field, invalid value)

Document:
mRID (sync, _)
type (*1, error 500)
process.processType (error 500, sync)
businessSector.type (error 500, error 500)
sender_MarketParticipant.mRID (sync, sync)
sender_MarketParticipant.marketRole.type (error 500, error 500)
receiver_MarketParticipant.mRID (async, *2)
receiver_MarketParticipant.marketRole.type (error 500, error 500)
createdDateTime (error 500, error 500)

Activityrecord:

ChargeInformation (D18):

mRID (error 500, _)
chargeTypeOwner_MarketParticipant.mRID (async, async)
type (schema, schema)
mRID (async, _)
name (async, _)
description (async, _)
priceTimeFrame_Period.resolution (schema, async)
effectiveDate (schema, schema)
terminationDate (schema, schema)
VATPayer (schema, schema)
transparentInvoicing (schema, schema)
taxIndicator (schema, schema)

ChargePrices (D08):
resoultion (schema, async)
start (schema, schema)
end (schema, schema)
position (schema, schema)
price.amount (schema, schema)

_ ikke relevant
*1 ved tom/blank, indsætter et eller andet den korrekte værdi inden den kommer ind i ingestion laget?
*2 validerer ikke på værdien overhovedet, den accepteres blot (manglende inputvalideringsregel?)

**Comment by IreneDataHub** [comment]
28.11.2022
Environment T-001
All test = OK

Status OK
B2B-005
<Error>
  <Code>B2B-005</Code>
  <Message>Syntax validation failed for business message.
'mRID' is either empty or contains only whitespace.</Message>
</Error>

(VR.223) Submitting empty or whitespaces as ChargeOperationId (cim:mRID) => StatusCode 500; System.InvalidOperationException => (Cannot ReadValueAs when there is no value (CanReadValue is false).)

OK
Wrong code
<cim:Reason>
            <cim:code>D02</cim:code>
            <cim:text>Document type Unknown not allowed together with business reason code UpdateChargeInformation.</cim:text>

Space
<Error>
  <Code>B2B-005</Code>
  <Message>Syntax validation failed for business message.
'type' is either empty or contains only whitespace.</Message>
</Error>

Type doesn't exit

<Error>
  <Code>B2B-005</Code>
  <Message>The specified input does not pass schema validation.</Message>
  <Details>
    <Error>
      <Code>SchemaValidationError</Code>
      <Message>The 'urn:ediel.org:structure:requestchangeofpricelist:0:1:type' element is invalid - The value 'D99' is invalid according to its datatype 'urn:ediel.org:structure:requestchangeofpricelist:0:1:MessageKind_String' - The value 'D99' is not valid according to any of the memberTypes of the union.</Message>
      <InnerError>

(VR.424) Submitting 'D02' in cim:process.processType => status 500.

Status OK
Wrong chargetype
or>
  <Code>B2B-005</Code>
  <Message>The specified input does not pass schema validation.</Message>
  <Details>
    <Error>
      <Code>SchemaValidationError</Code>
      <Message>The 'urn:ediel.org:structure:requestchangeofpricelist:0:1:type' element is invalid - The value 'D05' is invalid according to its datatype 'urn:ediel.org:structure:requestchangeofpricelist:0:1:ChargeKind_String' - The value 'D05' is not valid according to any of the memberTypes of the union.</Message>

Emty
<Code>B2B-005</Code>
  <Message>The specified input does not pass schema validation.</Message>
  <Details>

Space
  <Code>SchemaValidationError</Code>
      <Message>The 'urn:ediel.org:structure:requestchangeofpricelist:0:1:type' element is invalid - The value '  ' is invalid according to its datatype 'urn:ediel.org:structure:requestchangeofpricelist:0:1:ChargeKind_String' - The value '  ' is not valid according to any of the memberTypes of the union.</Message>
      <InnerError>

(VR.449) Submitting whitespaces as ChargeType => StatusCode 500; System.InvalidOperationException => (Cannot ReadValueAs when there is no value (CanReadValue is false).)

Status
Using P1Y 
<Error>
  <Code>B2B-005</Code>
  <Message>Syntax validation failed for business message.
Provided 'resolution' value 'P1Y' is invalid.</Message>
</Error>

(VR.912) Submitting a schema valid value (P1Y) for Charge Prices only (D08) => StatusCode 500. Problem lies in the ChargeCommandBundleConverter.cs in conjunction with public static string Map(Resolution resolution) in the ResolutionMapper.cs
