### ISSUE TITLE
VR.507-1 implementation is incorrect - It block submission of master data only as well as price series longer than a day

### ISSUE THREAD

**Issue by prtandrup** [Energinet-DataHub/geh-charges#1072]
**Description**
Our current implementation of VR.507.1 `The number of prices <1> for charge <2> doesnt match period type <3>` is incorrect.

The current implementation has three shortcomings: 

1.   It throws an `ArgumentException` when `resolution = P1M`, which blocks VR.505-1 from rejecting a wrong resolution for a tariff. 

2. It does not consider the price series period to be longer than a day, which often will be the case.

3. It blocks the submission of charges with master data only.

File: `ChargeTypeTariffPriceCountRule.cs`

**Acceptance criteria:**
Please see  prtandrup's comment from 15-03-2022, where updated AC's are listed
~~- [ ] VR-507-1 works as expected~~ 
~~- [ ] Submit a charge message that violates VR.505-1 and get a rejection message for it~~

Request that identified this problem:
````
<?xml version="1.0" encoding="UTF-8"?>
<cim:RequestChangeOfPriceList_MarketDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cim="urn:ediel.org:structure:requestchangeofpricelist:0:1" xsi:schemaLocation="urn:ediel.org:structure:requestchangeofpricelist:0:1 urn-ediel-org-structure-requestchangeofpricelist-0-1.xsd">
	<cim:mRID>DocId2022-01-20T11:22:18.278Z</cim:mRID>
	<cim:type>D10</cim:type>
	<cim:process.processType>D18</cim:process.processType>
	<cim:businessSector.type>23</cim:businessSector.type>
	<cim:sender_MarketParticipant.mRID codingScheme="A10">8100000000030</cim:sender_MarketParticipant.mRID>
	<cim:sender_MarketParticipant.marketRole.type>DDM</cim:sender_MarketParticipant.marketRole.type>
	<cim:receiver_MarketParticipant.mRID codingScheme="A10">5790001330552</cim:receiver_MarketParticipant.mRID>
	<cim:receiver_MarketParticipant.marketRole.type>DDZ</cim:receiver_MarketParticipant.marketRole.type>
	<cim:createdDateTime>2022-01-20T12:22:18Z</cim:createdDateTime>
	<cim:MktActivityRecord>
		<cim:mRID>OpId2022-01-20T11:22:18.278Z</cim:mRID>
		<cim:ChargeGroup>
			<cim:ChargeType>
				<cim:chargeTypeOwner_MarketParticipant.mRID codingScheme="A10">8100000000030</cim:chargeTypeOwner_MarketParticipant.mRID>
				<cim:type>D03</cim:type>
				<cim:mRID>Tariff0002</cim:mRID>
				<cim:name>Charge Tariff day Name</cim:name>
				<cim:description>The charge description</cim:description>
				<cim:priceTimeFrame_Period.resolution>P1M</cim:priceTimeFrame_Period.resolution>
				<cim:effectiveDate>2022-10-31T23:00:00Z</cim:effectiveDate>
				<cim:VATPayer>D01</cim:VATPayer>
				<cim:transparentInvoicing>false</cim:transparentInvoicing>
				<cim:taxIndicator>false</cim:taxIndicator>
				<cim:Series_Period>
					<cim:resolution>P1M</cim:resolution>
					<cim:timeInterval>
						<cim:start>2022-10-31T23:00Z</cim:start>
						<cim:end>2022-11-30T23:00Z</cim:end>
					</cim:timeInterval>
					<cim:Point>
						<cim:position>1</cim:position>
						<cim:price.amount>150.001</cim:price.amount>
					</cim:Point>
				</cim:Series_Period>
			</cim:ChargeType>
		</cim:ChargeGroup>
	</cim:MktActivityRecord>
</cim:RequestChangeOfPriceList_MarketDocument>
````

ApplicationInsights showing the issue:

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/21edd014-305c-4d88-af1b-586bf1f4d021)

**Comment by prtandrup** [comment]
We need to reconsider validation rule VR.507-1:

* is it fit for a CIM context in its current state?
* Should it be applied on all types of charges?
* Should it only assert that the number of Points match the time interval of the price series?
* Should we perhaps add a new validation rule for restricting price series shorter than 1 day of points?

For now, I have added a [PR](https://github.com/Energinet-DataHub/geh-charges/pull/1184) which removes some shortcomings in the way VR.507-1 ChargeTypeTariffPriceCountRule is currently implemented.

* It allows master data only requests through (requests with no prices)
* It doesn't throw when resolution = P1M (monthly)

But be aware that it still rejects price series longer than a day of values.

The team could have a look at the PR, and then I suggest we move the story back to refinement for the team to figure out the questions above.

**Comment by prtandrup** [comment]
The additional work that needs to be done on VR-507-1 has been moved to new story; #1198.

The remaining thing to test on this story are the following acceptance criteria:

- [ ] 1 As System Operator, submit a charge message with master data only. Verify that the charge is persisted, and a notifications is sent to a Grid Access Provider.
- [ ]  2 Submit below message (Perhaps it is necessary to change some charge data) 
And verify that this is not rejected by VR-507-1, but by VR-505-1: "The Tariff to which the charge information applies must have period type Day, Hour or Quarter of Hour" and uses error code D23.

````
<?xml version="1.0" encoding="UTF-8"?>
<cim:RequestChangeOfPriceList_MarketDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cim="urn:ediel.org:structure:requestchangeofpricelist:0:1" xsi:schemaLocation="urn:ediel.org:structure:requestchangeofpricelist:0:1 urn-ediel-org-structure-requestchangeofpricelist-0-1.xsd">
	<cim:mRID>DocId2022-01-20T11:22:18.278Z</cim:mRID>
	<cim:type>D10</cim:type>
	<cim:process.processType>D18</cim:process.processType>
	<cim:businessSector.type>23</cim:businessSector.type>
	<cim:sender_MarketParticipant.mRID codingScheme="A10">8100000000030</cim:sender_MarketParticipant.mRID>
	<cim:sender_MarketParticipant.marketRole.type>DDM</cim:sender_MarketParticipant.marketRole.type>
	<cim:receiver_MarketParticipant.mRID codingScheme="A10">5790001330552</cim:receiver_MarketParticipant.mRID>
	<cim:receiver_MarketParticipant.marketRole.type>DDZ</cim:receiver_MarketParticipant.marketRole.type>
	<cim:createdDateTime>2022-01-20T12:22:18Z</cim:createdDateTime>
	<cim:MktActivityRecord>
		<cim:mRID>OpId2022-01-20T11:22:18.278Z</cim:mRID>
		<cim:ChargeGroup>
			<cim:ChargeType>
				<cim:chargeTypeOwner_MarketParticipant.mRID codingScheme="A10">8100000000030</cim:chargeTypeOwner_MarketParticipant.mRID>
				<cim:type>D03</cim:type>
				<cim:mRID>Tariff0002</cim:mRID>
				<cim:name>Charge Tariff day Name</cim:name>
				<cim:description>The charge description</cim:description>
				<cim:priceTimeFrame_Period.resolution>P1M</cim:priceTimeFrame_Period.resolution>
				<cim:effectiveDate>2022-10-31T23:00:00Z</cim:effectiveDate>
				<cim:VATPayer>D01</cim:VATPayer>
				<cim:transparentInvoicing>false</cim:transparentInvoicing>
				<cim:taxIndicator>false</cim:taxIndicator>
				<cim:Series_Period>
					<cim:resolution>P1M</cim:resolution>
					<cim:timeInterval>
						<cim:start>2022-10-31T23:00Z</cim:start>
						<cim:end>2022-11-30T23:00Z</cim:end>
					</cim:timeInterval>
					<cim:Point>
						<cim:position>1</cim:position>
						<cim:price.amount>150.001</cim:price.amount>
					</cim:Point>
				</cim:Series_Period>
			</cim:ChargeType>
		</cim:ChargeGroup>
	</cim:MktActivityRecord>
</cim:RequestChangeOfPriceList_MarketDocument>
````

**Comment by Mech0z** [comment]
Test 1:
When sending this Tariff with no points
![image](https://user-images.githubusercontent.com/2316684/158983197-756ed50b-9414-4291-83e1-56aa09f85dec.png)

We get this in the database
![image](https://user-images.githubusercontent.com/2316684/158983129-c1fa9d47-e5bf-46ee-ac1c-11895ca27cde.png)

Test 2:
Sending the xml provided here https://github.com/energinet-datahub/geh-charges/issues/1072#issuecomment-1067998467 we get this message in [MessageHub].[AvailableChargeReceiptValidationError] but no message is ready to peek / dequeue 
![image](https://user-images.githubusercontent.com/2316684/158983668-5075955a-2034-4638-997e-3e11b04fdbff.png)

But errorcode and text is correct

**Comment by Mech0z** [comment]
Tested again, using Market participant 9656626091925 instead fixed the issue
