### ISSUE TITLE
Schema validation -> Role must be verified against GLN

### ISSUE THREAD

**Issue by IreneDataHub** [Energinet-DataHub/geh-charges#1077]
**Synopsis**

In created stories # 922, we found another issue that needs to be validated. 
Volt decided to make a new story, as it is immediately outside the "scope" compared to the #922 and bugs.

**Acceptance criteria**

Validation of the correct role code in relation to "sender" and "receiver" of GLN (in the messages)

[See bug report](https://app.zenhub.com/files/345465244/541e4736-a03c-4b70-9dde-c08e535f3622/download)

**Comment by HenrikSommer** [comment]
@IreneDataHub must this validation be carried out by schema validation?
Background info: Schema validation has no database access, hence it has no knowledge of the allowed rule of an actor. Can we fulfill the need with a validation rule in the asynchronous validation flow?

**Comment by IreneDataHub** [comment]
@HenrikSommer 
We are waiting for a clarified from the architect group.
Mogens are going to Martin and Søren. They have to clarification whether it is handling individual by each domains as a asynchronous validation or it is going to be rejected in a synchronous validation based on a package we receive from Titanium.
Therefore I cant give answer yet. Do you want me to set thise issue on hold or?
