### ISSUE TITLE
Reject WebApi HTTP requests when not authenticated

### ISSUE THREAD

**Issue by HenrikSommer** [Energinet-DataHub/geh-charges#1088]
**Synopsis**
As GreenForce ART
We want web API HTTP endpoints in DataHub to require authentication.

**Tech Notes**

Team Batman has created a JWT Token Middleware NuGet package to be used in all domains. The package is already in use in the metering point domain pull request #650

SimpleInjector is implemented in the metering point domain, hence a helper method for registering the JWT Token Middleware in dependency injection container is provided for SimpleInjector only. We can choose to implement a helper method for the .NET Core built-in dependency injection container, or we can migrate to SimpleInjector and use the provided helper method

All domain tests must be updated to provide a valid JWT token for all requests

TenantId (B2C_TENANT_ID) and Audience (BACKEND_SERVICE_APP_ID) should be pulled from shared resources key vault

Acceptance criteria
- [ ] AC 1:
Given any HTTP endpoint in the web API
When an unauthenticated request is received
Then the request is rejected and the caller receives an HTTP 401 response

- [ ] AC 2:
Given a metering point with charge links
When the metering point is looked up in the frontend
Then charge links are displayed

* AC 2 is actually more a helper to check that we didn't break anything when implementing AC 1.

**Comment by PerTHenriksen** [comment]
blocked; mangler mulighed for bruger auth udenfor browsere.

**Comment by IreneDataHub** [comment]
Test: OK ( environments u-001 and t-001
 AC 1:
Given any HTTP endpoint in the web API
When an unauthenticated request is received
Then the request is rejected and the caller receives an HTTP 401 response

Wrong token - e to much in the begining at the token:
![image.png](https://images.zenhubusercontent.com/612f6568004bdd03eab7ca46/9f24c1f2-067b-495c-ad16-d1664419bc0f)

Reject 401:
![image.png](https://images.zenhubusercontent.com/612f6568004bdd03eab7ca46/6a0542bf-9872-4400-9cb1-8716444baaa9)

The test is ok for charge/chargelink and create MP from "samples" - I receive 401 for all kind of request.

AC2 - test tomorrow

**Comment by IreneDataHub** [comment]
Test 16.2.2022
Test: OK ( environments u-001 and b-002
AC 1:
Given any HTTP endpoint in the web API
When an unauthenticated request is received
Then the request is rejected and the caller receives an HTTP 401 response
![image.png](https://images.zenhubusercontent.com/612f6568004bdd03eab7ca46/b1d82e24-9a81-492b-8508-c4b96c4e748b)

Test ac2: = OK
 AC 2:
Given a metering point with charge links
When the metering point is looked up in the frontend
Then charge links are displayed

AC 2 is actually more a helper to check that we didn't break anything when implementing AC 1.

![image.png](https://images.zenhubusercontent.com/612f6568004bdd03eab7ca46/b302a2c1-33b3-4be1-ae65-497e59e5d778)


![image.png](https://images.zenhubusercontent.com/612f6568004bdd03eab7ca46/23346532-efb8-45e1-b92e-b593a15dc236)

![image.png](https://images.zenhubusercontent.com/612f6568004bdd03eab7ca46/f6793134-181f-41ef-9627-07e39cb14c2e)
