### ISSUE TITLE
Charge links rejections cannot be peeked

### ISSUE THREAD

**Issue by BjarkeMeier** [Energinet-DataHub/geh-charges#1104]
### Current Behavior

Charge links rejections cannot be peeked. There are no expected rejection messages to peek.

### Expected behavior

When an invalid charge link document is sent to DataHub then the actor can peek a rejection.

### Acceptance criteria
Charge link rejections messages should be able to be peek'ed

**Comment by lasrinnil** [comment]
The issue with not being able to peek the rejections was introduced with this PR, and the missing data updated needed for existing data that was not dequeued

**Comment by BjarkeMeier** [comment]
"...introduced with this PR...", did you intend to add a link @lasrinnil ?
