### ISSUE TITLE
 HTTP POST - response for successful HTTP 200 change to 202 after a request charge or charge link

### ISSUE THREAD

**Issue by IreneDataHub** [Energinet-DataHub/geh-charges#1127]
If the content complies with the applicable rules, 202 Accepted will be returned from DataHub instead of 200 as we use today.

Acc:
Accepted 202 will be returned from DataHub after receive chargelink

Acc:
Accepted 202 will be returned from DataHub after receive charge

**Comment by prtandrup** [comment]
### Tested in T-001

✅ **ChargeIngestion gives 202**

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/ec5dff23-3a12-40ea-b9fe-d16c81b144b9)

✅ **ChargeLinksIngestion gives 202:**

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/3ef20145-042d-467e-9ae0-36ae4a4798d2)
