### ISSUE TITLE
 HTTP POST - response fo succecful HTTP 200 change to 202 after a request charge or chargelink

### ISSUE THREAD

**Issue by IreneDataHub** [Energinet-DataHub/geh-charges#1128]
If the content complies with the applicable rules, 202 Accepted will be returned from DataHub instead of 200 as we use today.

Acc:
Accepted 202 will be returned from DataHub after receive chargelink

Acc:
Accepted 202 will be returned from DataHub after receive charge

**Comment by prtandrup** [comment]
duplicate of #1127
