### ISSUE TITLE
Cover feature AC#2 with tests: Allow Charge information and Charge Price updates without any changes to the existing data (ac2)

### ISSUE THREAD

**Issue by prtandrup** [Energinet-DataHub/geh-charges#1135]
With this story we add the necessary tests at the lowest possible test level to ensure that
* a Charge Information (D18) request with the exact same master data as stored is accepted and processed
* a Charge Price (D08) request with the same price values as stored is accepted and processed.

**Acceptance criteria:** 
The following **integration tests** have been added: 

- [x] 1 `ChargeInformationEventHandlerTests`: Given a charge already exist,
When a new Charge Information (D18) request (in shape of a `ChargeCommandReceivedEvent`) with the same master data as currently in storage is received and processed
Then it follows the happy flow (accepted and stored)
<br>

- [x] 2 `ChargePriceEventHandlerTests`: Given a price list already exist,
When a new Charge Price (D08) request (in shape of a `ChargeCommandReceivedEvent`) with the same price list data as currently in storage is received and processed
Then it follows the happy flow (accepted and stored)

**Comment by HenrikSommer** [comment]
Note for the tester: Production code isn't changed, so only regression test and code review is relevant.

**Comment by prtandrup** [comment]
**AC1 OK, integration test created and executed:**

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/66829b2c-4d1c-4ab6-8904-a89af524e0d3)

**AC2 OK, integration test created and executed:**

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/01c8a74e-5dca-4ad0-bc77-392404a2693a)
