### ISSUE TITLE
Agreement on enrichment of timeseries to aggregations (and what charge data is needed)

### ISSUE THREAD

**Issue by PerLysemose** [Energinet-DataHub/geh-charges#114]
Vi skal være skarpe på hvilke data aggregerings domænet rent faktisk har brug for. 

Derfor sætter vi en kort session op for at koordinere: 
Berigelse af tidsserier og hvilke data aggregerings domænet har behov for.  

AC1: Vi har lavet kontrakten med tidsserie domænet, som beskriver hvilke data vi får fra dem. 
AC2: (Tilføjet undervejs) Få defineret hvilke charge/charge links data som aggregation har behov for.

**Comment by prtandrup** [comment]
Mads (PO, Joules) and I had a meeting today, where we defined the charge + charge links data needed from the Charges domain to the Aggregation domain. The data list can be found below (please consider the names used as temporary as these may very well change in the time to come):

_**Charge** data:_ 
- Charge ID
- Charge Name
- Charge Owner
- Resolution
- Tax
- Price list (including Price + 'Time_the_price_is_valid')
- A reference to the Market Actor's charge transaction ID

_**Charge links** data_
- Metering Point ID
- Charge ID 
- Charge linked from date
- Charge linked to date
- Charge link quantity (only valid for subscription and fees) 
- A reference to the Market Actor's charge link transaction ID
