### ISSUE TITLE
Persist Charge (4/4) - Update before a registered stop flow (ac 1a)

### ISSUE THREAD

**Issue by prtandrup** [Energinet-DataHub/geh-charges#1154]
**Synopsis:**
As a Grid Access Provider,
I want to update the master data of a charge that has a future stop date
So that I can keep the master data aligned with my own system until the charge is stopped.

This is another story of a few stories with the goal of implementing the [charge persistence rule set](https://github.com/Energinet-DataHub/geh-charges/tree/main/docs/process-flows#persist-charge) (master data only)

With this story we will implement the **updating before a registered stop** flow, highlighted below:
<hr>

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/4de7377f-2396-4f74-b9a9-6fc70c918479)

**Acceptance criteria:**
- [ ] 1 Given an existing charge with two periods has been stopped
When updating the charge master data with an effective date inside period two
Then period two's end date is adjusted
And the master data update is inserted as a third period with the registered stop date
So that the persisted result be like: 

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/d03cd6f6-8897-4b2b-8c00-5a14ba0c479d)

**Comment by IreneDataHub** [comment]
Test B-002 22.03.2022/IRS
https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/d03cd6f6-8897-4b2b-8c00-5a14ba0c479d
Create subscription  Stopupdate start 1.11.2022 
Update 1.12. 2022 new description
Stop 1.1 2023 
![image.png](https://images.zenhubusercontent.com/612f6568004bdd03eab7ca46/327c166d-ac35-4493-b1c0-4b67b258ad58)
Update 15. 12.2022 new description "...update 4" 

![image.png](https://images.zenhubusercontent.com/612f6568004bdd03eab7ca46/bc90a023-a3f2-466f-b1ac-f04c49fd2525)
 
Then period two's end date is adjusted
And the master data update is inserted as a third period with the registered stop date= OK

{
                "Id": "6747b8c3-6cdd-47c6-ba18-8428fdd3760d",
                "ChargeId": "89a7787d-f6eb-4184-b3a4-58a802415e3d",
                "TransparentInvoicing": false,
                "Description": "The charge description stop 1 update 4",
                "Name": "demo sub stop and update",
                "VatClassification": 2,
                "StartDateTime": "2022-12-14T23:00:00",
                "EndDateTime": "2022-12-31T23:00:00"
            },
            {
                "Id": "6accfad3-2f4c-4819-b1cb-9e304283de24",
                "ChargeId": "89a7787d-f6eb-4184-b3a4-58a802415e3d",
                "TransparentInvoicing": false,
                "Description": "The charge description stop 1 update 3",
                "Name": "demo sub stop and update",
                "VatClassification": 2,
                "StartDateTime": "2022-11-30T23:00:00",
                "EndDateTime": "2022-12-14T23:00:00"
            }

New update 15. nov 2022 - - make new period from 1.11. - 15.11. and from 15.11. to. 1.1.2023 - overwrite the others period, but the stop is still activ

{
                "Id": "2d33acbb-1a09-4dc2-9090-b13ef576c00c",
                "ChargeId": "89a7787d-f6eb-4184-b3a4-58a802415e3d",
                "TransparentInvoicing": false,
                "Description": "The charge description stop 1 update 2",
                "Name": "demo sub stop and update",
                "VatClassification": 2,
                "StartDateTime": "2022-10-31T23:00:00",
                "EndDateTime": "2022-11-14T23:00:00"
            },
            {
                "Id": "f4008a00-637b-413f-8df8-e1b6a9910fdc",
                "ChargeId": "89a7787d-f6eb-4184-b3a4-58a802415e3d",
                "TransparentInvoicing": false,
                "Description": "The charge description stop 1 update 5",
                "Name": "demo sub stop and update",
                "VatClassification": 2,
                "StartDateTime": "2022-11-14T23:00:00",
                "EndDateTime": "2022-12-31T23:00:00"
