### ISSUE TITLE
VR.679 only checks if charge exists - not if it exists on charge link's effective date

### ISSUE THREAD

**Issue by prtandrup** [Energinet-DataHub/geh-charges#1164]
According to our validation rule master data sheet, VR.679 goes like this:

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/6541a571-4c8e-4dba-b19f-188f397390ac)

Our current implementation only checks if the charge exists - NOT if charge exists on charge link's effective date.
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/2be2fce7-85c8-4773-9a91-ef25063a87d9)

This will allow a charge link to be created before the charge's start date.

File: ChargeMustExistRule.cs

**Comment by PerTHenriksen** [comment]
#1141 - please align possible overlap @prtandrup

**Comment by prtandrup** [comment]
Duplicate of #1141, hence closed.
