### ISSUE TITLE
Charge price lists: Being able to provide notifications using new business reason code D08 (Feature-AC4c/AC5a)

### ISSUE THREAD

**Issue by PerTHenriksen** [Energinet-DataHub/geh-charges#1196]
**Synopsis**
It has been decided with the Market that **prices** and **master data** are to be submitted separately; same CIM message, but with different business reason codes:

* **Charge price list** | Business Reason Code: **D08** | Message: RequestChangeOfPriceList
* **Charge master data** | Business Reason Code: **D18** | Message: RequestChangeOfPriceList

With this story the Charges domain must be able to:

As a Grid Access Provider
I want to receive validated charge price notifications for tax tariffs from DataHub
So that I can calculate the amounts payable to the Danish Tax Authorities

**Acceptance criteria**
- [ ] Given a valid charge price list request for a tax tariff has been processed by DataHub
When any Grid Access Provider peeks
Then a charge price notification is received with
* the correct content (limited master data (Charge ID, Owner, Type and effectiveDate) + all price data)
* and correct business reason code = D08

- [ ] 2 Given a valid charge price list request for a NON-tax charge has been processed by DataHub
When any Grid Access Provider peeks
Then no charge price notification is received.
<br>

- [ ] 3 Architecture diagram for Charge Prices has been updated to reflect any changes that this story introduced.

Out of scope : request D08 included all price infomation and not only limited infomation for D08.

**Comment by PerLysemose** [comment]
@HenrikSommer please review

**Comment by IreneDataHub** [comment]
Status Blocked:
I can't peek (after request price D08 and a confirm) - getting kode 204, but I expect to peek notification / RSM-034.
It is possible to send notification out ( RSM-034) after request for pris information D18.

Test 3 June / environment B-002
[https://app.zenhub.com/files/345465244/6a307828-0f8d-4ef1-82f3-64b079d9e1dc/download](https://app.zenhub.com/files/345465244/6a307828-0f8d-4ef1-82f3-64b079d9e1dc/download)

**Comment by IreneDataHub** [comment]
Test 17. June Environment B-002
Request nede to contain all the price information but doesn't need "name" and "description" to requestt with code D08. Out of scope that it is possible only to send request for limited masterdata.

Test -> notify is ok for D08. We only send limited data and nok all the others infomation

1) OK
Then a charge price notification is received with
the correct content (limited master data (Charge ID, Owner, Type and effectiveDate) + all price data)
and correct business reason code = D08
 2) OK
 Given a valid charge price list request for a NON-tax charge has been processed by DataHub
When any Grid Access Provider peeks
Then no charge price notification is received.

Please se the attachment[https://app.zenhub.com/files/345465244/de40ca9d-b9a6-4f69-a5b3-8af883838519/down[https://app.zenhub.com/files/345465244/15fbcd69-16f3-4097-b62b-c55778289d45/download](https://app.zenhub.com/files/345465244/15fbcd69-16f3-4097-b62b-c55778289d45/download)load](https://app.zenhub.com/files/345465244/de40ca9d-b9a6-4f69-a5b3-8af883838519/download)
