### ISSUE TITLE
Reject charge updates changing resolution (AC3)

### ISSUE THREAD

**Issue by prtandrup** [Energinet-DataHub/geh-charges#1200]
After creating a Charge, it is no longer allowed to change the resolution of that charge

**Acceptance criteria:**
- [ ] 1 When sending a charge update with master data changes but the same resolution, no rejection is returned.
- [ ] 2 When sending a charge update with master data changes but different resolution a rejection message is received:
"**When updating Master Data, the period resolution \<periodResolution> cannot be changed.**" with error code DXX
- [ ] 3 Update [validations.md](https://github.com/Energinet-DataHub/geh-charges/blob/main/docs/business-processes/validations.md) in GitHub with this new rule.

**Comment by Mech0z** [comment]
@IreneDataHub Can you have a look at the rejection message and error code for this error, I have just created a example in the accept criteria.

**Comment by IreneDataHub** [comment]
Reason code D23
![image.png](https://images.zenhubusercontent.com/612f6568004bdd03eab7ca46/1fba903c-507d-4a6b-99a5-29d5e9bbef4b)
![image.png](https://images.zenhubusercontent.com/612f6568004bdd03eab7ca46/e6e75ecd-747d-499a-80de-62e8b961f3c5)
