### ISSUE TITLE
ENDK tariffs showing twice on MP (B-002). Issue also seen at enviroment U-001

### ISSUE THREAD

**Issue by IreneDataHub** [Energinet-DataHub/geh-charges#1209]
Create MP 575699978565416189 (17. March) envoiment B-002 Charge domain.

ml version="1.0" encoding="utf-8"?>
<cim:GenericNotification_MarketDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cim="urn:ediel.org:structure:genericnotification:0:1" xsi:schemaLocation="urn:ediel.org:structure:genericnotification:0:1 urn-ediel-org-structure-genericnotification-0-1.xsd">
  <cim:mRID>311acf4e-80c8-4e6c-8c6c-fb3905260aa1</cim:mRID>
  <cim:type>E44</cim:type>
  <cim:process.processType>E65</cim:process.processType>
  <cim:businessSector.type>E23</cim:businessSector.type>
  <cim:sender_MarketParticipant.mRID codingScheme="A10">5790001330552</cim:sender_MarketParticipant.mRID>
  <cim:sender_MarketParticipant.marketRole.type>DDZ</cim:sender_MarketParticipant.marketRole.type>
  <cim:receiver_MarketParticipant.mRID codingScheme="A10">8100000000047</cim:receiver_MarketParticipant.mRID>
  <cim:receiver_MarketParticipant.marketRole.type>DDM</cim:receiver_MarketParticipant.marketRole.type>
  <cim:createdDateTime>2022-03-17T11:37:04Z</cim:createdDateTime>
  <cim:MktActivityRecord>
    <cim:mRID>dae9b880-91a7-43cf-b75d-20bdc790621d</cim:mRID>
    <cim:originalTransactionIDReference_MktActivityRecord.mRID>252af655-2170-4693-aa65-327aad1e0aec</cim:originalTransactionIDReference_MktActivityRecord.mRID>
    <cim:marketEvaluationPoint.mRID codingScheme="A10">575699978565416189</cim:marketEvaluationPoint.mRID>
    <cim:validityStart_DateAndOrTime.dateTime>2022-03-10T23:00:00Z</cim:validityStart_DateAndOrTime.dateTime>
  </cim:MktActivityRecord>
</cim:GenericNotification_MarketDocument>

After peek and deque and update Frontend B-002 the MP shows ENDK tariffs twice

![image.png](https://images.zenhubusercontent.com/612f6568004bdd03eab7ca46/7a1e9ce4-a321-4093-96d5-33b44e8acacf)

Through the tool 0-data, I see that double tariffs have been logged at the meteringpoint twice. It is therefore not just a frontend error

**Comment by IreneDataHub** [comment]
MP 571313111290000000 environment U-001 - same issue. ENDK tariffs are connected 4 times at the same MP. Mogens inform that he may have submitted MPs several times in a row, but that must still not be possible.

![image.png](https://images.zenhubusercontent.com/612f6568004bdd03eab7ca46/02a2f9b9-33d4-4055-be51-4e9e5b6dd510)

**Comment by prtandrup** [comment]
Had a quick look in app insights in U-001; seems like we are receiving 4x request from MP domain, requesting default charge links:
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/096a94d9-25d1-4c2a-b068-0c3a8c1ddae6)

**Comment by Mech0z** [comment]
Blocked for now:
Awaiting info from MeteringPoint domain 

There is a spike on handling concurrency issues, this could solve this kind of issue https://github.com/Energinet-DataHub/geh-charges/issues/1143

A cheap solution could be to set max number of parallel executions to 1 https://stackoverflow.com/questions/63567085/azure-durable-functions-managing-parallelism
