### ISSUE TITLE
Updated: Upload template charge files for energinet.dk

### ISSUE THREAD

**Issue by PerTHenriksen** [Energinet-DataHub/geh-charges#1215]
Problem description:
Marked actors have difficulties complying with message format, and have requested that Energinet shares working files:

For charges domain, and subsequently metering point domain, the agreement is to prepare three example files without use of {variables}, that have been proven to function. 

Given the frequency of changes to the charges domain, we opt for a solution where such files reside in github, with public access, to ensure they are within testing reach of development. 

Thus:
- [x] AC: upload a WORKING subscription creation file to location in github, and name similar to  "BRS-031 - RSM-031 Create subscription monthly" )  
- [x] AC: upload a working fee creation file, and name it "BRS-032 - RSM-031 Create fee - monthly"
- [x] AC: upload a working tariff  creation file, and name it "BRS-033 RSM-031- create tariff - hourly"  
- [x] AC: The files needs to be accessible without github credentials. 
- [x] AC: Notify PO or Vicky (VJE - Vicki Jeppson), to ensure that a link is passed to collection of example files; 
![image.png](https://images.zenhubusercontent.com/60bdf7bbfa2182da7fd5cc6d/769c8937-e91c-4958-8358-a14b263117d5)

**Comment by HenrikSommer** [comment]
Implementation notes:
- files will be copied to energinet.dk, so they are named according to our naming scheme within charges domain
- three variables are used, in contrast to the problem description. This is done to avoid hardcoding sender, receiver, and timestamp. The variable {{$ISO8601Timestamp}} indicated the need to comply with the ISO8601 time format

**Comment by HenrikSommer** [comment]
@PerTHenriksen examplefiles are located here:
- [Fee monthly](https://github.com/Energinet-DataHub/geh-charges/blob/main/source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTest.Core/TestFiles/Charges/FeeMonthlyPriceExample.xml)
- [Subscription monthly](https://github.com/Energinet-DataHub/geh-charges/blob/main/source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTest.Core/TestFiles/Charges/SubscriptionMonthlyPriceExample.xml)
- [Tariff hourly](https://github.com/Energinet-DataHub/geh-charges/blob/main/source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTest.Core/TestFiles/Charges/TariffHourlyPricesExample.xml)
