### ISSUE TITLE
Danish character displayed as "?" in GUI - Indfødningstarif produktion

### ISSUE THREAD

**Issue by PerTHenriksen** [Energinet-DataHub/geh-charges#1225]
In the the default tariff for production metering point "Indfødningstarif production", the Danish character ø is displayed as a question mark. 

![Indfødningstarifbug.png](https://images.zenhubusercontent.com/60bdf7bbfa2182da7fd5cc6d/1e363b2a-6c25-4cd2-a627-c108834c4069)

**Comment by prtandrup** [comment]
Additional info, seen in database:
![image](https://user-images.githubusercontent.com/71757561/159877784-33c569ee-c542-414b-85e9-d664e89e3963.png)

**Comment by HenrikSommer** [comment]
Solution proposal: Change SQL server collation from _sql_latin1_general_cp1_ci_as_ to _danish_norwegian_ci_as_

**Comment by prtandrup** [comment]
Metering Point domain seems to handle this:
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/d6531d59-c0c6-4314-9d44-c6a6fd109a24)

**Comment by HenrikSommer** [comment]
It turns out to be a really stupid little thing, we save these texts with weird characters in our DbUp scripts
'Netafgiften, for b�de forbrugere og producenter, d�kker... '

**Comment by prtandrup** [comment]
:white_check_mark: Tested on B-002; MP ID: 577930160159068166

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/c2e8a175-afc1-4162-b901-934a323c8a9b)

**Comment by PerTHenriksen** [comment]
Tested and verified
