### ISSUE TITLE
Charge update must not have bound end date

### ISSUE THREAD

**Issue by Mech0z** [Energinet-DataHub/geh-charges#1231]
Instead of throwing an exception we should fail using a validation rule instead as the end user do not currently get a response when it fails.

**### Find out if this is still a problem, code have been refactored a lot since, if so create a validation rule instead of throwing an exception.**

Log https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/ComponentId/%7B%22SubscriptionId%22%3A%223c13ff3d-aad8-4ee8-94c6-8a938ace9699%22%2C%22ResourceGroup%22%3A%22rg-DataHub-SharedResouces-U-001%22%2C%22Name%22%3A%22appi-shared-sharedres-u-001%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%252Fsubscriptions%252F3c13ff3d-aad8-4ee8-94c6-8a938ace9699%252FresourceGroups%252Frg-DataHub-SharedResouces-U-001%252Fproviders%252FMicrosoft.Insights%252Fcomponents%252Fappi-shared-sharedres-u-001%22%2C%22ResourceType%22%3A%22microsoft.insights%252Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel/%7B%22eventId%22%3A%220241b406-ac13-11ec-997c-2818787a4d67%22%2C%22timestamp%22%3A%222022-03-25T08%3A09%3A33.788Z%22%2C%22cacheId%22%3A%227cbdf70f-691d-4338-9738-a820e03d6330%22%2C%22eventTable%22%3A%22exceptions%22%2C%22timeContext%22%3A%7B%22durationMs%22%3A86400000%2C%22endTime%22%3A%222022-03-25T12%3A21%3A15.064Z%22%7D%7D

GreenEnergyHub.Charges.Domain.Charges.Charges.cs
```
        public void Update(ChargePeriod newChargePeriod, TaxIndicator taxIndicator, Resolution resolution, string operationId)
        {
            ArgumentNullException.ThrowIfNull(newChargePeriod);
            ArgumentNullException.ThrowIfNull(operationId);

            // This should be in a separate rule and handled by ChargeOperationFailedException
            // in order to notify sender that operation failed because of this constraint
            if (newChargePeriod.EndDateTime != InstantExtensions.GetEndDefault())
            {
                throw new InvalidOperationException("Charge update must not have bound end date.");
            }
```

**Comment by prtandrup** [comment]
Suggest the following regression tests:

- [ ]  1: Create Charge. And then Update it. Verify it works
- [ ]  2: Create Charge. Then Stop it. Then do an Update before the stop date. Verify it works.

**Comment by prtandrup** [comment]
### Tested in T-001 :heavy_check_mark:
Pair-tested with Irene. 
Test1:
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/00816886-bdcd-4510-8287-dfdcda44bdf9)

Test2: 
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/1f31f833-be76-4d37-a1ff-83e203e17fe9)

**Comment by prtandrup** [comment]
### Tested in T-001 :heavy_check_mark:
Pair-tested with Irene. 
Test1:
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/00816886-bdcd-4510-8287-dfdcda44bdf9)

Test2: 
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/1f31f833-be76-4d37-a1ff-83e203e17fe9)
