### ISSUE TITLE
Enabler: ServiceBus Communication - 3 - Implement message serialization and deserialization

### ISSUE THREAD

**Issue by PerLysemose** [Energinet-DataHub/geh-charges#124]
**Acceptance criteria:**
AC1: An implementation of MessageSerializer supporting JSON has been implemented and shown to work through unit tests
AC2: An implementation of MessageDeserializer supporting JSON has been implemented and shown to work through unit tests

**Description:**
This story is part of moving the charge domain towards using the messaging-framework for sending messages within and between domains.

As part of this task, we need to ready implementations of MessageSerializer and MessageDeserializer that support raw JSON which we will be using internally in the charge domain.

MessageSerializer can be seen below:

```
    /// <summary>
    /// Abstract class for serializing outgoing messages.
    /// </summary>
    public abstract class MessageSerializer
    {
        /// <summary>
        /// Serialize a message
        /// </summary>
        /// <param name="message">Message to serialize</param>
        /// <param name="cancellationToken">Cancellation token for the request</param>
        /// <returns><see cref="byte"/> sequence for the message</returns>
        public abstract Task<byte[]> ToBytesAsync(IOutboundMessage message, CancellationToken cancellationToken = default);
    }
```

It will be called by the dispatcher and should make use of a mapper abstraction to map a IHubOutboundMessage to a DTO (if needed) as shown in the following diagram:

![image](https://user-images.githubusercontent.com/12642168/116399295-0d962000-a829-11eb-8a24-846ca9e51997.png)

Inspiration can be found in the current protobuf implementation found here:
https://github.com/Energinet-DataHub/geh-charges/blob/main/source/messaging/source/GreenEnergyHub.Messaging.Protobuf/ProtobufMessageSerializer.cs

Likewise, we need an implementation of MessageDeserializer that match the serializer implementation.

The abstract class looks like this:

```
    /// <summary>
    /// Abstract class for deserializing incoming messages.
    /// </summary>
    public abstract class MessageDeserializer
    {
        /// <summary>
        /// Deserialize <paramref name="data"/> to an inbound message
        /// </summary>
        /// <param name="data">Data to deserialize</param>
        /// <param name="cancellationToken">Cancellation token for the operation</param>
        /// <returns><see cref="IInboundMessage"/> extracted from <paramref name="data"/></returns>
        public abstract Task<IInboundMessage> FromBytesAsync(byte[] data, CancellationToken cancellationToken = default);
    }
```

It will be called by the MessageExtractor and should make sure of a mapper abstraction to map a DTO to a IInboundMessage (if needed) as shown in the following diagram:

![image](https://user-images.githubusercontent.com/12642168/116400356-3cf95c80-a82a-11eb-9ec2-9534c20775fc.png)

Inspiration can be found in the current protobuf implementation found here:
https://github.com/Energinet-DataHub/geh-charges/blob/main/source/messaging/source/GreenEnergyHub.Messaging.Protobuf/ProtobufMessageDeserializer.cs

**Comment by BjarkeMeier** [comment]
Notes for tester: Regarding AC 2: I consider the tests of our own JsonSerializer implementation to be sufficient. However, I'll be adding some more unit tests for our own extensions to the messaging framework in an upcoming PR.

**Comment by lasrinnil** [comment]
### Test

**AC1: An implementation of MessageSerializer supporting JSON has been implemented and shown to work through unit tests**
We have a test covering our implementation of serializing JSON.


**AC2: An implementation of MessageDeserializer supporting JSON has been implemented and shown to work through unit 
The test for the deserialization is still in progress atm.
