### ISSUE TITLE
Use shared implementation of CorrelationIdMiddleware

### ISSUE THREAD

**Issue by HenrikSommer** [Energinet-DataHub/geh-charges#1267]
**Synopsis**
Given the GreenForceArt
When sharable code is extracted to a NuGet-package
Then we import and use it in Charges domain

**Tech notes**
CorrelationIdMiddleware is located in the Energinet.DataHub.Core.App.FunctionApp as of version 2.2.0

**Acceptance criteria**
* [x] Replace the implementation of CorrelationIdMiddleware in Charges domian with the equivalent in Energinet.DataHub.Core.App.FunctionApp

**Comment by HenrikSommer** [comment]
Also done related to this story:
* [X] Update Energinet.DataHub.Core NuGet packages
* [X] Use shared version of FunctionTelemetryScopeMiddleware

**Comment by Mech0z** [comment]
Tested by sending a request and finding CorrelationId 132241265df871edba7897e780ce71d6 in the response

This was used to find the request flow in Application Insights and verify that the logging structure still is in place
![image](https://user-images.githubusercontent.com/2316684/164445458-db516205-5c5c-45fc-9807-8d3ff67f1f26.png)

**Comment by prtandrup** [comment]
Additionally; a CorrelationId response header is populated on below requests:
* Charge request
* Charge Link request
* Peek
* Dequeue

**Documented below:**

Charge request:

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/a85e8398-ef13-4187-84a4-3bb5b793b366)

Charge Link request:

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/d3441478-3949-4183-95b9-49570a19ffae)

Peek:

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/27ab28dc-e7f2-47d8-b8ad-30059951dc99)

Dequeue:

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/53708b83-f4e4-4c0c-b738-a9525f372861)

Supported by the following system logging [documentation](https://github.com/Energinet-DataHub/greenforce-art/blob/main/wiki/logging/logging.md), I verified that it is traceable through application insights.
