### ISSUE TITLE
#1494 - >Validation: A price list request must start at midnight and end at midnight

### ISSUE THREAD

**Issue by prtandrup** [Energinet-DataHub/geh-charges#1296]
As a Charges domain owner
I want to validate that the received Charge Price requests **starts and ends** at midnight Danish local time (UTC 22:00 / 23:00 depending on Daylight Saving Time / Normal Time)
So that I can reject any price series that does not conform to this requirement

**Acceptance criteria:**

- [x] 1 Given a valid Charge Price request is received with below listed start and end datetime values
When validating the request
Then it is accepted.

| Start (UTC) | End (UTC | Regime | Validation Result | Notes |
|---|---|---|---|---|
| 01-07-2022T22:00 | 02-07-2022T22:00 | DST | Accepted | |
| 31-12-2022T23:00 | 01-01-2023T23:00 | Normal Time | Accepted | |
| 31-12-2022T23:00 | 31-12-2022T23:00 | Normal Time | Accepted | Same date still passes validation |
| 26-03-2022T23:00 | 27-03-2022T22:00 | Switch to DST | Accepted | |
| 29-10-2022T22:00 | 30-10-2022T23:00 | Switch to Normal Time | Accepted | |
<br>

- [x] 2 Given a Charge Price request with a **start date time** that does not match 22:00 during DST OR 23:00 during Normal Time
When validating the request
Then it is rejected with error code = "**The time interval (start and end) of the price series must equal midnight local time, expressed in UTC+0.**"
And error text = **E86**
<br>

- [x] 3 Given a Charge Price request with a **end date time** that does not match 22:00 during DST OR 23:00 during Normal Time
When validating the request
Then it is rejected with error code = "**The time interval (start and end) of the price series must equal midnight local time, expressed in UTC+0.**"
And error text = **E86**

**Comment by PerTHenriksen** [comment]
To be estimated once the refactoring is done

**Comment by IreneDataHub** [comment]
Test 15 July, but bug 1494 need to be fix before ACC, 1 2 and 3 are as expeced. Be aware of reason code E87 and E86 in acc. 2 and 3.
[https://app.zenhub.com/files/345465244/c145186e-d060-4120-93e0-a24bab346aa6/download](https://app.zenhub.com/files/345465244/c145186e-d060-4120-93e0-a24bab346aa6/download)
