### ISSUE TITLE
Have a request for cancelling of a charge stop rejected, due to passed time limit (AC8)

### ISSUE THREAD

**Issue by PerTHenriksen** [Energinet-DataHub/geh-charges#1299]
AC; Might be handled already, added it as I've seen cancelling run though, but not rejections of cancelling requests..

**Comment by PerTHenriksen** [comment]
( (8) Given a Grid access provider,
when sending a charge stop of charge master data
then Grid access provider is able to cancel this, if within predefined time limits governing the environment (-720 days in U,T, B environments),
and if the stop is passed the time limit, then the request is denied.)

**Comment by PerTHenriksen** [comment]
mostly a test of wheter we adhere to the time limits.

**Comment by IreneDataHub** [comment]
Test 31. May 2022
Environment B-002

The test is performed with -719 as we have a bug #1289 which block to test for specific -720 passed limit.
However, have tested that we can create priceinformation subscription with -720

The test also includes tests of price elements can be created a max of 3 years into the future.

AC:
Given a Grid access provider,
when sending a charge stop of charge master data
then Grid access provider is able to cancel this, if within predefined time limits governing the environment (-720 days in U,T, B environments),

See the attached that shows specific request, confirm, reject for the create, stop and update.

Down below there are specific screenshot from charge logs: AB P1M 07

Create:
"ChargePeriods": [
{
"Id": "42cf309e-b584-48ea-87cc-50339a7d4519",
"ChargeId": "00386bc0-7b12-45ec-8815-13bdb7b7bcac",
"TransparentInvoicing": false,
"Description": "The charge description",
"Name": "Charge Sub Name start",
"VatClassification": 1,
"StartDateTime": "2020-06-09T22:00:00",
"EndDateTime": "9999-12-31T23:59:59"
}
],
"Id": "00386bc0-7b12-45ec-8815-13bdb7b7bcac",
"SenderProvidedChargeId": "AB P1M 07",
"Type": 1,
"OwnerId": "0e223e42-bed4-4778-a973-8d0ad9813f71",
"TaxIndicator": false,
"Resolution": 4
},

Stop:
"ChargePeriods": [
{
"Id": "42cf309e-b584-48ea-87cc-50339a7d4519",
"ChargeId": "00386bc0-7b12-45ec-8815-13bdb7b7bcac",
"TransparentInvoicing": false,
"Description": "The charge description",
"Name": "Charge Sub Name start",
"VatClassification": 1,
"StartDateTime": "2020-06-09T22:00:00",
"EndDateTime": "2020-06-10T22:00:00"
}
],
"Id": "00386bc0-7b12-45ec-8815-13bdb7b7bcac",
"SenderProvidedChargeId": "AB P1M 07",
"Type": 1,
"OwnerId": "0e223e42-bed4-4778-a973-8d0ad9813f71",
"TaxIndicator": false,
"Resolution": 4
},

Cancel stop:
"ChargePeriods": [
{
"Id": "42cf309e-b584-48ea-87cc-50339a7d4519",
"ChargeId": "00386bc0-7b12-45ec-8815-13bdb7b7bcac",
"TransparentInvoicing": false,
"Description": "The charge description",
"Name": "Charge Sub Name start",
"VatClassification": 1,
"StartDateTime": "2020-06-09T22:00:00",
"EndDateTime": "2020-06-10T22:00:00"
},
{
"Id": "18132ee7-89c7-4297-9b6d-36a79b9e2a04",
"ChargeId": "00386bc0-7b12-45ec-8815-13bdb7b7bcac",
"TransparentInvoicing": false,
"Description": "The charge description",
"Name": "Charge Sub Name stop",
"VatClassification": 1,
"StartDateTime": "2020-06-10T22:00:00",
"EndDateTime": "9999-12-31T23:59:59"
}
],
"Id": "00386bc0-7b12-45ec-8815-13bdb7b7bcac",
"SenderProvidedChargeId": "AB P1M 07",
"Type": 1,
"OwnerId": "0e223e42-bed4-4778-a973-8d0ad9813f71",
"TaxIndicator": false,
"Resolution": 4
},[https://app.zenhub.com/files/345465244/0bca034e-a907-4508-8bae-af31ad59b15a/download](https://app.zenhub.com/files/345465244/0bca034e-a907-4508-8bae-af31ad59b15a/download)
