### ISSUE TITLE
Add CIM mapping for RSM-033 (for Mighty Ducks)

### ISSUE THREAD

**Issue by PerLysemose** [Energinet-DataHub/geh-charges#131]
Description:
Mighty Ducks meldte ud at de nok ville have svært ved at nå at lave mapping færdig for os. Så de vil lave komponenten, og så vil de nok gerne have os selv til at lave et PR mod deres komponent (hvor end den ender med at bo) som de så reviewer.

ACs:
AC1: CIM mapping of RSM-033 has been added to main branch of the repo pointed out by Mighty Ducks.
AC2: Charges domain can process RSM-033 eBIX messages.
AC3: Each transaction (payload) from RSM-033 message is forwarded as individual events from sync ingestion.
AC4: Transactional control: Either all charge transactions must be published OR none must be published and function must return a non-success status code.

**Comment by PerTHenriksen** [comment]
please refine

**Comment by PerTHenriksen** [comment]
Candidate for PI6 - depending on refined scope.
