### ISSUE TITLE
Ensure all required master data fields are present and populated for Charge Information Request (D18) (Feature-AC4d)

### ISSUE THREAD

**Issue by prtandrup** [Energinet-DataHub/geh-charges#1326]
Notes:
Input validation on the following fields. Be aware that some of them might be caught by the schema validation, and thus should probably not be covered in the input validation as well... 

Null or empty checks of all the fields that are allowed set as 0:1 in schema, but are required for Charge Information requests:

- [x] - Name https://github.com/Energinet-DataHub/geh-charges/pull/1437
- [x] - Description https://github.com/Energinet-DataHub/geh-charges/pull/1437
- [x] - Resolution https://github.com/Energinet-DataHub/geh-charges/pull/1439

Content validation

- [x] * Owner => Length 13-16 https://github.com/Energinet-DataHub/geh-charges/pull/1444
- [x] * Type => Valid Enum check https://github.com/Energinet-DataHub/geh-charges/blob/main/source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeCommands/Validation/InputValidation/ValidationRules/ChargeTypeIsKnownValidationRule.cs
- [x] * Charge Id => Length Max 10 https://github.com/Energinet-DataHub/geh-charges/blob/main/source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeCommands/Validation/InputValidation/ValidationRules/ChargeIdLengthValidationRule.cs
- [x] * Name => Length limit 132 https://github.com/Energinet-DataHub/geh-charges/pull/1438
- [x] * Description => Max 2048 Length VR.447 https://github.com/Energinet-DataHub/geh-charges/blob/main/source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeCommands/Validation/InputValidation/ValidationRules/ChargeDescriptionHasMaximumLengthRule.cs
- [x] * VAT Classification => value provided => not unknown at this point https://github.com/Energinet-DataHub/geh-charges/blob/main/source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/Dtos/ChargeCommands/Validation/InputValidation/ValidationRules/VatClassificationValidationRule.cs
- [x] * Transparent Invoicing => value provided => not unknown at this point https://github.com/Energinet-DataHub/geh-charges/pull/1445
- [x] * Tax Indicator => value provided => not unknown at this point https://github.com/Energinet-DataHub/geh-charges/pull/1446
- [x] * Termination Date => == effective date

Acceptance criteria:
- [ ] Async validation documentation is updated with all error codes listed above

**Comment by IreneDataHub** [comment]
[https://app.zenhub.com/files/34546524[https://app.zenhub.com/files/345465244/93a569b6-c5ee-40d2-a19b-3f3ac7431f59/download](https://app.zenhub.com/files/345465244/93a569b6-c5ee-40d2-a19b-3f3ac7431f59/download)4/41ce9147-a754-4636-b81d-765c4b33ba55/download](https://app.zenhub.com/files/345465244/41ce9147-a754-4636-b81d-765c4b33ba55/download)

**Comment by IreneDataHub** [comment]
Test environment B-002, U-001
Test finish
[https://app.zenhub.com/files/34546524[https://app.zenhub.com/files/345465244/bb4609d5-0952-45d7-a3aa-5ee84b740a32/download](https://app.zenhub.com/files/345465244/bb4609d5-0952-45d7-a3aa-5ee84b740a32/download)4/2287d89a-0286-4b89-abae-2200f368a55d/download](https://app.zenhub.com/files/345465244/2287d89a-0286-4b89-abae-2200f368a55d/download)
