### ISSUE TITLE
BRS-031/032/033: Determine needed information for positive and negative acknowledgements

### ISSUE THREAD

**Issue by PerLysemose** [Energinet-DataHub/geh-charges#133]
Description:
As a developer
I want to determine what information is needed to send positive and negative acknowledgement about charge changes
So that know what to develop later

ACs:
An object model has been documented so that it is usuable in #101939  and #101940 
A name has been selected for the type of object (for use in the post office to determine what to do with it)
The model includes:
The mRID of the market participant to receive the information
The name of the type above
All information needed to later map the object to an RSM-033/D18 message
The model must cover both the positive acknowledgement and the negative acknowledgement
The object model uses CIM naming conventions.
CIM names can be found here

**Comment by bemwen** [comment]
Note https://github.com/Energinet-DataHub/geh-charges/blob/main/docs/document-type-mappings/RSM033-to-CIM.md which lists the fields needed.

The suggested naming is wrong the old CIM model; consider new naming when the DTO is created

**Comment by PerTHenriksen** [comment]
rejected.
