### ISSUE TITLE
Update the sample files for Charge Information (D18) and Charge Prices (D08)

### ISSUE THREAD

**Issue by IreneDataHub** [Energinet-DataHub/geh-charges#1338]
After separating Charge Information (D18) and Charge Prices (D08), we need to create new D08 sample files and update the existing D18 samples, so that the market participants / system vendors have those at hand.

**Acceptance criteria:**

- [x] 1 Update the Charge Information (D18) sample files in Github 
(for subscription, fee and tariff), 
so they no longer contains price series. 
<br>

- [x] 2 Add Charge Prices (D08) sample files to Github 
~~(remember that some master data values might still be needed for some time)~~
<br>

- [x] 3 All samples files are used in domain testing, so we are confident that they work.

Samples are located here: 
https://github.com/Energinet-DataHub/geh-charges/tree/main/source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTest.Core/TestFiles/Charges/Samples

**Comment by x-platformcoder** [comment]
[x] AC1: Controlled that priceseries is removed on all chargeinformation sample files on github
[x] AC2: Controlled that chargeprice samples are added to github and is correct
[x] AC3: Controlled all sample files are used in domain testing (used in following domain tests)
   * Given_ChargeInformationSampleFile_When_GridAccessProviderPeeks_Then_MessageHubReceivesReply
   * Given_ChargePriceSample_When_GridAccessProviderPeeks_Then_MessageHubReceivesReply
