### ISSUE TITLE
BRS-031/032/033: Create Positive Acknowledgement (RSM-033/D18) to sender and put on Service Bus (post office)

### ISSUE THREAD

**Issue by PerLysemose** [Energinet-DataHub/geh-charges#134]
**Description:**
As a Grid Access Provider
I want to receive a positive acknowledgement upon submitting a valid charge message
So that I know it has been accepted.

_Tech note:_
It has been agreed not use protobuf for this story.

**Acceptance criteria:**

- An object model for the acknowledgement has been implemented. 
Notes: 
The model must include attributes from: 
https://github.com/Energinet-DataHub/geh-charges/blob/main/docs/document-type-mappings/RSM033-to-CIM.md#dk_confirmupdatechargeinformation
And include information about the receiver and the role required.
The naming part of it will be handled by Michael or Peter. Please reach out to one of them, if naming has not been settled upon starting this task. The names provided in the link above are _not_ the ones to use.

-  Given a ChargeCommandAccepted event has been placed on the ServiceBus, the ChargeAcknowledgementSender must create positive acknowledgement event on the ServiceBus (representing the PostOffice).
(This must be done regardless of charge type and status in the ChargeCommandAccepted event (tariff, fees and subs), (add, update, stop))

- The positive acknowledgement event placed on the ServiceBus must contain the object model as well as reciever information, like Grid Access Provider ID and role. 

Comment from Michael:
As part of this task, please make sure our event between message receiver and chargecommandreceiver uses a separate topic instead of filtering

**Comment by PerTHenriksen** [comment]
PTA to clean up and include naming convention

**Comment by lasrinnil** [comment]
I was going to test this ticket, but my postman is blocked on my Dev machine when trying to reach our functions. @bemwen or @prtandrup can still test it on T

**Comment by bemwen** [comment]
It has been decided to only test this acknowledgement task towards creations which is the only operation supported by our charge functionality at the moment. Updates and Stops where not tested (it is impossible to get them to this point).


**Result:**
1. An object model for the acknowledgement has been implemented - PASSED
2. Given a ChargeCommandAccepted event has been placed on the ServiceBus, the ChargeAcknowledgementSender must create positive acknowledgement event on the ServiceBus (representing the PostOffice) - PARTIALLY PASSED - (update/stop not tested)
3. The positive acknowledgement event placed on the ServiceBus must contain the object model as well as reciever information, like Grid Access Provider ID and role. - FAILED - (role is missing)

**1**
A model has been impleted and reflects the needed fields listed in the link.

**2:**

_Subscription:_
A subscription was sent using our Submit Addition Subscription in postman as shown below:

![image](https://user-images.githubusercontent.com/12642168/117434858-7702e680-af2d-11eb-88df-45c322cce4c3.png)

The acknowledgement receipt ended up on the service bus representing the post office as expected.

![image](https://user-images.githubusercontent.com/12642168/117435382-16c07480-af2e-11eb-960a-019d72cbe089.png)
