### ISSUE TITLE
Receive time isn't showing correct in GUI

### ISSUE THREAD

**Issue by IreneDataHub** [Energinet-DataHub/geh-charges#1404]
Screen in GUI indicates wrong time for receiving the message
Perhaps it is because we use "cim:createdDateTimecim" specified in wrist watch time. Perhaps it has to been in UTC time. 

RSM-033 - > create time 2022-06-03T13:20:07Z<
?xml version="1.0" encoding="UTF-8"?>
<cim:RequestChangeOfPriceList_MarketDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cim="urn:ediel.org:structure:requestchangeofpricelist:0:1" xsi:schemaLocation="urn:ediel.org:structure:requestchangeofpricelist:0:1 urn-ediel-org-structure-requestchangeofpricelist-0-1.xsd">
	<cim:mRID>DocId2022-06-03T11:20:07.349Z</cim:mRID>
	<cim:type>D10</cim:type>
	<cim:process.processType>D18</cim:process.processType>
	<cim:businessSector.type>23</cim:businessSector.type>
	<cim:sender_MarketParticipant.mRID codingScheme="A10">8100000000047</cim:sender_MarketParticipant.mRID>
	<cim:sender_MarketParticipant.marketRole.type>DDM</cim:sender_MarketParticipant.marketRole.type>
	<cim:receiver_MarketParticipant.mRID codingScheme="A10">5790001330552</cim:receiver_MarketParticipant.mRID>
	<cim:receiver_MarketParticipant.marketRole.type>DDZ</cim:receiver_MarketParticipant.marketRole.type>
	<cim:createdDateTime>2022-06-03T13:20:07Z</cim:createdDateTime>
	<cim:MktActivityRecord>
		<cim:mRID>OpId2022-06-03T11:20:07.349Z</cim:mRID>
		<cim:ChargeGroup>
			<cim:ChargeType>
				<cim:chargeTypeOwner_MarketParticipant.mRID codingScheme="A10">8100000000047</cim:chargeTypeOwner_MarketParticipant.mRID>
				<cim:type>D03</cim:type>
				<cim:mRID>TarId036</cim:mRID>
				<cim:name>Charge name</cim:name>
				<cim:description>The charge description</cim:description>
				<cim:priceTimeFrame_Period.resolution>PT1H</cim:priceTimeFrame_Period.resolution>
				<cim:effectiveDate>2022-08-14T22:00:00Z</cim:effectiveDate>
				
				<cim:VATPayer>D01</cim:VATPayer>
				<cim:transparentInvoicing>false</cim:transparentInvoicing>
				<cim:taxIndicator>true</cim:taxIndicator>
			</cim:ChargeType>
		</cim:ChargeGroup>
	</cim:MktActivityRecord>
</cim:RequestChangeOfPriceList_MarketDocument>

GUI - screenshot

![image.png](https://images.zenhubusercontent.com/612f6568004bdd03eab7ca46/5b9d04f9-ee3a-4308-ae50-ffe9e3595011)

Team Batmat has the same issue # 306 (event board). Therefore it will be a good idea to find out jointly, which time set up we have to use in createddatetime for all domains.

**Comment by prtandrup** [comment]
Made a small change in postman, in the pre-request script where `moment()` was changed to `moment.utc()`. 
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/da81f9b6-4788-4409-a264-9012439a7ec5)
So now, when any Charges request is submitted, it will use UTC time, and when searched in GUI, it will display wrist band time (local time)

**Comment by prtandrup** [comment]
**How to test it:** 
Select one of your charge requests in Postman and submit it. 
Then use the Search Messages page in GUI (Fremsøg forretningsbesked) and verify that it displays the time (Tid) correctly for your request; as Danish local time.
