### ISSUE TITLE
BRS-031/032/033 When updating or stopping a charge, existing active charge data records must be ended (by setting an end date)

### ISSUE THREAD

**Issue by PerLysemose** [Energinet-DataHub/geh-charges#141]
Description:
Lige en placeholder:
Når vi opdaterer eller sletter en charge, så får vi ikke sat end date på de eksisterende aktive charge data records i databasen.
Vi vil formentlig også genbesøge koncepterne og kodedesignet o
![When updating](https://user-images.githubusercontent.com/71811581/116206437-16122c00-a73f-11eb-8161-f27369476155.png)
mkring persistering (ChargeRepository.cs m.m.).
[](url)

**Comment by prtandrup** [comment]
It has been decided to replace this story with a new one, #288, which will implement the defined rule set for persisting charges (See #287). 288 will be covering the above-mentioned problem.
