### ISSUE TITLE
Missing confirm or reject after request - using unknown chargeTypeOwner

### ISSUE THREAD

**Issue by IreneDataHub** [Energinet-DataHub/geh-charges#1421]
Environment B-002
Using unknown charge type owner "8100000000099" in request REM-033 / create price information - expect an reject, but I didn't get anything at all ( confirm/reject)

Please investigate and make a work around solution until we have full validation of chargeTypeOwner when the market roles are integrated.

AC1)
Receive a reject after using unknown Chargetypeowner 

Request:
<cim:businessSector.type>23</cim:businessSector.type>
	<cim:sender_MarketParticipant.mRID codingScheme="A10">8100000000047</cim:sender_MarketParticipant.mRID>
	<cim:sender_MarketParticipant.marketRole.type>DDM</cim:sender_MarketParticipant.marketRole.type>
	<cim:receiver_MarketParticipant.mRID codingScheme="A10">5790001330552</cim:receiver_MarketParticipant.mRID>
	<cim:receiver_MarketParticipant.marketRole.type>DDZ</cim:receiver_MarketParticipant.marketRole.type>
	<cim:createdDateTime>{{ISO8601Timestamp}}</cim:createdDateTime>
	<cim:MktActivityRecord>
		<cim:mRID>OpId{{$isoTimestamp}}</cim:mRID>
		<cim:ChargeGroup>
			<cim:ChargeType>
				<cim:chargeTypeOwner_MarketParticipant.mRID codingScheme="A10">8100000000099</cim:chargeTypeOwner_MarketParticipant.mRID>
				<cim:type>D02</cim:type>
				<cim:mRID>PI8_fee01</cim:mRID>
				<cim:name>PI8 Charge Fee Name</cim:name>
				<cim:description>The charge description</cim:description>
				<cim:priceTimeFrame_Period.resolution>P1M</cim:priceTimeFrame_Period.resolution>
                <cim:effectiveDate>2021-11-30T23:00:00Z</cim:effectiveDate>				
				<cim:VATPayer>D01</cim:VATPayer>
				<cim:transparentInvoicing>false</cim:transparentInvoicing>
				<cim:taxIndicator>false</cim:taxIndicator>

![image.png](https://images.zenhubusercontent.com/612f6568004bdd03eab7ca46/d2cb64aa-8d23-4054-a551-f7afd55103f6)

**Comment by PerTHenriksen** [comment]
Likely to be solved by #1418

**Comment by prtandrup** [comment]
Solved by #1418 (Charge Information) / #1419 (Charge Prices)
