### ISSUE TITLE
Notify the team if MessageReceiver isn't responding correctly

### ISSUE THREAD

**Issue by PerLysemose** [Energinet-DataHub/geh-charges#143]
In order to ensure working software we take a step in direction of surveilling health state of our Azure functions.

**Tech notes**

Energinet has shut down webhooks of Teams channels due to security concerns. So it is assumed that the Microsoft Teams email is being set up in GitHub repo secrets settings and passed on to Terraform through the GitHub infrastructure pipeline.
Teams channel email can be found in the teams channel you want to target.

**Acceptance criteria**

1. In case one of the existing availability tests in the charges domain fail a notification is shown in team Volts channel in Microsoft Teams

**Comment by BjarkeMeier** [comment]
Original text:

_It is fairly easy to add tooling to continously monitor the message receiver to verify that it is responding to HTTP requests. E.g. using availability tests deployed using Terraform. These can send mails or other kinds of notification. Wouldn't it be nice to be notified within 5ish minutes when the endpoint is down - e.g. due to breaking PRs or other reasons?_

**Comment by bemwen** [comment]
Note: Availibility test of the time series domain has been postponed and moved to #471

The AC has been updated to reflect this by added charges as the only target.

**Comment by bemwen** [comment]
To the tester.

You can test an alert by simply stopping an Azure Function and waiting for the alert to raise.

**Comment by prtandrup** [comment]
**Tested :white_check_mark: in T environment.** 

Turned off `message-receiver-charges`:

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/c4b9d829-c91c-44b2-9611-dafa3892b564)

Notifications sent to, and shown in Teams:

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/66c1af78-288e-4c39-ae97-9bc56accfca8)
