### ISSUE TITLE
Enabler: ServiceBus Communication - 4 - Move to messaging strategy

### ISSUE THREAD

**Issue by PerLysemose** [Energinet-DataHub/geh-charges#144]
**Acceptance criteria:**

1. We make use of the messaging framework when sending messages to the ServicesBus
2. We make use of the messaging framework when receiving messages from the ServiceBus

**Description:**
This task is part of the enabler to move communication with the ServiceBus to the messaging-framework in the Charge-domain.

This task will complete the move.

_Sending data:_

The flow of sending data through the messaging-framework can be seen here:

![image](https://user-images.githubusercontent.com/12642168/117426934-c55fb780-af24-11eb-888d-7c8793600866.png)

We have previously made our needed classes needed for the Serializer, Mapper and Channel, as well as made sure our messages implement IInboundMessage and IOutboundMessage.

What is left now is:
* Make a message dispatcher for each event we need to send
* Dependency inject the needed classes
* Use the dispatchers when sending messages to the service bus.

_Receiving data:_

The flow for receiving data through the messaging-framework can be seen here:

![image](https://user-images.githubusercontent.com/12642168/117427844-b9c0c080-af25-11eb-9a10-9bba4a6cc04c.png)

We have previously made our needed classes for Deserializer, Mapper and made sure we receive data from the trigger as a byte array. The MessageExtractor already exist in the messaging framework. The handler is a remnant which is deprecated and will be removed and out of scope of this story.

What is left now is:
* Dependency inject the needed classes
* In the hosts that read from the ServiceBus, pass the byte array to the MessageExtractor to receive the message.
* Hook up ICorrelationContext as needed

**Comment by lasrinnil** [comment]
### Test
I have verified we are using the messaging framework for sending and receiving messages from the service bus.  
And tested sending a message which triggers sending and receiving of the message until it reaches the post office's service bus.
