### ISSUE TITLE
Charge price D08: Valid charge request for period where there are a switch DST to normal time - > getting a reject

### ISSUE THREAD

**Issue by IreneDataHub** [Energinet-DataHub/geh-charges#1494]
Test #1296
Expect an confirm after a request for charge price for date where we switch DST to normal time, but I receive a reject

Request:
<cim:mRID>Irenetest</cim:mRID>
                
                
                <cim:priceTimeFrame_Period.resolution>P1D</cim:priceTimeFrame_Period.resolution>
                <cim:effectiveDate>2022-10-29T22:00:00Z</cim:effectiveDate>
                
                
                
                
                <cim:Series_Period>
                    <cim:resolution>P1D</cim:resolution>
                    <cim:timeInterval>
                        <cim:start>2022-10-29T22:00Z</cim:start>
                        <cim:end>2022-10-30T23:00Z</cim:end>
                    </cim:timeInterval>
                    <cim:Point>
                        <cim:position>1</cim:position>
                        <cim:price.amount>200.001</cim:price.amount>
                    </cim:Point>

But instead of a confirm I got a reject:
   <cim:code>E87</cim:code>
            <cim:text>The number of prices received does not match the expected number of prices given the time interval and resolution provided for charge with ID Irenetest of type Tariff owned by 8100000000047.</cim:text>

There are a issue for "calculate of day", as there only are 1. postion, and not 2.
Its works as expect for PT1H ( 23 or 25 positions)

**Comment by Mech0z** [comment]
Error is in NumberOfPointsMatchTimeIntervalAndResolutionRule

The interval we calculate returns a decimal value and use to get total days returns a decimal value

_expectedPointCount = Resolution.P1D => interval.Duration.TotalDays,

So when we compare that
IsValid => _expectedPointCount == _actualPointCount;

Is is a mismatch.

Maybe we should just round down the value from total days?

**Comment by IreneDataHub** [comment]
Be aware that this also applies resolution P1M
