### ISSUE TITLE
Verify that prices are sent to all Grid Access Providers when charge is a tax tariff (AC 5A)

### ISSUE THREAD

**Issue by Mech0z** [Energinet-DataHub/geh-charges#1523]
Grid Access Providers must be informed about accepted price series for tax tariffs. This happens through a notification with business reason code (D08) which contains the prices.
Given its' importance, this must be covered by a domain test to guard regression.

**Acceptance criteria:**

- [x] 1 Domain test added:
Given a tax tariff exist (owned by the System Operator)
When a valid charge price request (D08) is received
Then (our test) grid access provider receives a notification (D08) with the prices.
(It is considered adequate verifying that one of our grid access providers receive such a notification.)

**Comment by prtandrup** [comment]
Will probably be solved by #1203

**Comment by HenrikSommer** [comment]
This story is considered solved with the introduction of the _Given_ChargePriceMessageWithChargeInformationData_WhenPosted_ThenChargePriceDataAvailableNotificationToGridAccessProviderContainsMandatoryChargeInformationOnly_ test in #1203.

It is considered adequate verifying that one of our grid access providers receive such a notification.)
