### ISSUE TITLE
Outbox V2: <to be refined>

### ISSUE THREAD

**Issue by jonasdmoeller** [Energinet-DataHub/geh-charges#1529]
![outbox-v2.jpg](https://images.zenhubusercontent.com/60dafff3568c156496e54f35/d7cda8c7-59ff-4dce-aced-7a84bb7147ee)

[Link til Miro board](https://miro.com/app/board/uXjVO74hWqo=/)

Refinement questions:
* Should this story handle this potential short-coming?: Same function to create available data and notify message hub (data available notification)
* Idempotency - this story later?
* Integration events in scope? ChargePricesUpdated
* When do we refactor ChargeInformation flow to resemble Price flow? -> #1527

**Tasks**
Small stories covering;
* Rejection; data available by handing rejection via service bus
* Confirmations; data available by handing confirmaion via service bus (implies the 'left side' of the architectural drawing) 
* Confirmation; confirmation event
* Notifications to MDR; Delivery to all involved MDR's - likely to be handled via service bus functionality "batch". 

1 Introduce service bus events for notifying message hub 
2 Expand outbox with confirmed event
3 Special notifications (tax tariff)
4 Introduce service bus event for raising integration events * 

**Tech notes:**
* Investigate possible solutions to the "50 receivers" problem, is Service Bus batch our savior?

**Comment by HenrikSommer** [comment]
This story is replaced by #1559, #1660, #1661 and #1662, collectively.
