### ISSUE TITLE
Mighty Ducks - NuGet Workshop #331 24/8

### ISSUE THREAD

**Issue by PerTHenriksen** [Energinet-DataHub/geh-charges#1535]
Assignment of 1-2 guys to a 3 hours NuGet workshop, by request from MD.

@HenrikSommer will attend the workshop.

The aim of the workshop is to align NuGet build pipelines in all DataHub repositories with the NuGet build pipeline in the _geh-core_ repository.

**Comment by HenrikSommer** [comment]
For the tester: This is a technical story, only affecting our NuGet build pipeline. Test by comparing our NuGet build pipeline with the similar pipeline in the _geh-core_ repository.

**Comment by prtandrup** [comment]
Compared **geh-core's** [app-common-bundle-publish.yml](https://github.com/Energinet-DataHub/geh-core/blob/main/.github/workflows/app-common-bundle-publish.yml) with **Charges**' [charges-libraries-publish.yml](https://github.com/Energinet-DataHub/geh-charges/blob/main/.github/workflows/charges-libraries-publish.yml). Looks good to me.
