### ISSUE TITLE
Add existing price validation rules to new price flow

### ISSUE THREAD

**Issue by jonasdmoeller** [Energinet-DataHub/geh-charges#1549]
Existing flow for ingesting charge updates has input validation of D08 messages, i.e. MaximumPriceRule, NumberOfPointsMatchTimeIntervalAndResolutionRule, ChargeTypeTariffPriceCountRule, etc.

These validations must be added to the new price flow in order to have the same level of validation as already is.

**Note**
This addition is first manually testable when the outbox v1 story is completed and the new price flow enabled. An automated integration test will be added to ensure validation rules are applied to the new flow.

**Comment by prtandrup** [comment]
### Tested in T-001 :white_check_mark:

**ChargeIdLengthValidationRule**

    <cim:MktActivityRecord>
        <cim:mRID>606229982fe64022862c536eebabe182</cim:mRID>
        <cim:originalTransactionIDReference_MktActivityRecord.mRID>OpId2022-08-19T12:04:21.757Z</cim:originalTransactionIDReference_MktActivityRecord.mRID>
        <cim:Reason>
            <cim:code>E86</cim:code>
            <cim:text>Charge ID FeeId101TooLong of type Fee owned by 8100000000016 has a length that exceeds 10.</cim:text>
        </cim:Reason>
    </cim:MktActivityRecord>

**ChargeIdRequiredValidationRule** => Not possible to test (HTTP 500 internal error: on empty or whitespace / HTTP 400 bad request: if tag not present)
**ChargeOperationIdRequiredRule** => Not possible to test (HTTP 500 internal error: on empty or whitespace / HTTP 400 bad request: if tag not present)

**ChargeOperationIdLengthValidationRule**

    <cim:MktActivityRecord>
        <cim:mRID>af557c01e35a464cbccce051146ac131</cim:mRID>
        <cim:originalTransactionIDReference_MktActivityRecord.mRID>0123456789012345678901234567890123456</cim:originalTransactionIDReference_MktActivityRecord.mRID>
        <cim:Reason>
            <cim:code>E86</cim:code>
            <cim:text>The document with ID DocId2022-08-19T12:10:17.710Z contains a transaction ID 0123456789012345678901234567890123456 that is longer than the allowed length of 36 characters.</cim:text>
        </cim:Reason>
    </cim:MktActivityRecord>
	
**ChargeOwnerIsRequiredValidationRule** => Not possible to test (HTTP 500 internal error: on empty or whitespace / HTTP 400 bad request: if tag not present)
	
**ChargeTypeIsKnownValidationRule**

    <cim:MktActivityRecord>
        <cim:mRID>a3f328eaf23f4db989030b5c8c60b8db</cim:mRID>
        <cim:originalTransactionIDReference_MktActivityRecord.mRID>OpId2022-08-19T12:12:20.753Z</cim:originalTransactionIDReference_MktActivityRecord.mRID>
        <cim:Reason>
            <cim:code>E86</cim:code>
            <cim:text>Charge type is missing for charge with ID FeeId101 owned by 8100000000016.</cim:text>
        </cim:Reason>
    </cim:MktActivityRecord>
	
**StartDateTimeRequiredValidationRule** => only possible to test with 1970-01-01 00:00:00 in effectiveDate

    <cim:MktActivityRecord>
        <cim:mRID>439955954571499390ba301a4b0253b4</cim:mRID>
        <cim:originalTransactionIDReference_MktActivityRecord.mRID>OpId2022-08-19T12:22:13.932Z</cim:originalTransactionIDReference_MktActivityRecord.mRID>
        <cim:Reason>
            <cim:code>E0H</cim:code>
            <cim:text>Effective date is missing for charge with ID FeeId101 of type Fee owned by 8100000000016.</cim:text>
        </cim:Reason>
    </cim:MktActivityRecord>

**ChargeOwnerTextLengthRule**
&
**ChargeOwnerMustMatchSenderRule**

    <cim:MktActivityRecord>
        <cim:mRID>0d595a91b0ea44eca1cdf89342dfb1ea</cim:mRID>
        <cim:originalTransactionIDReference_MktActivityRecord.mRID>OpId2022-08-19T12:24:26.859Z</cim:originalTransactionIDReference_MktActivityRecord.mRID>
        <cim:Reason>
            <cim:code>E0I</cim:code>
            <cim:text>The specified charge owner OwnerNotOk do not match sender 8100000000016 and is therefore not authorized to change charge id FeeId101 of type Fee</cim:text>
        </cim:Reason>
        <cim:Reason>
            <cim:code>E86</cim:code>
            <cim:text>Charge owner for type Fee with charge ID FeeId101 must have a length of 13 or 16.</cim:text>
        </cim:Reason>
    </cim:MktActivityRecord>
	
Perhaps we should get rid off ChargeOwnerTextLengthRule, as we check the owner now.

**Comment by prtandrup** [comment]
The following four additional validation rules has been added to the new price flow, and is ready for testing:

* ChargePriceMaximumDigitsAndDecimalsRule (8,6)
* ChargeTypeTariffPriceCountRule (min. 92 points for 15 min / 1 point for day)
* NumberOfPointsMatchTimeIntervalAndResolutionRule
* PriceListMustStartAndStopAtMidnightValidationRule
