### ISSUE TITLE
Delete old subscriptions (New SB strategy 3/3)

### ISSUE THREAD

**Issue by Mech0z** [Energinet-DataHub/geh-charges#1591]
**Synopsis**
We clean up and delete the old subscriptions from 
https://github.com/Energinet-DataHub/geh-shared-resources/blob/main/build/infrastructure/main/sbt-metering-point-created.tf 
kvs_sbs_metering_point_created_sub_charges_name

https://github.com/Energinet-DataHub/geh-shared-resources/blob/main/build/infrastructure/main/sbt-market-participant-changed.tf 
kvs_sbs_market_participant_changed_to_charges_name

And delete the Charges Service bus namespace.

**Acceptance criteria**

- [x] The old subscriptions have been removed
~~- [X] The charges service bus namespace have been deleted~~ done in #1597

![image.png](https://images.zenhubusercontent.com/60bdbd325b600c62f9576fbb/df1f73ec-e1b3-4c06-b293-82da68f90691)

**Comment by x-platformcoder** [comment]
Visually identified that "market-participant-changed-to-charges" is removed:

![marketparticipant.png](https://images.zenhubusercontent.com/621e27789626c44a088a5ee9/89a73716-0ea1-4e9d-aa2f-3aae0a134b46)

**Comment by x-platformcoder** [comment]
Visually identified that "metering-point-created-sub-charges" is removed:
![meteringpoint.png](https://images.zenhubusercontent.com/621e27789626c44a088a5ee9/a342fe38-1d4d-4d7e-83d5-b5f0cee3baec)
