### ISSUE TITLE
BRS-031/032/033: Design session - Persistence strategy for charges

### ISSUE THREAD

**Issue by bemwen** [Energinet-DataHub/geh-charges#160]
**Acceptance criteria:**
AC1: The team have held a design session to discuss the model for how to persist charges
AC2: Issue #141 have been updated and refined to reflect the design agreed upon

**Description:**
We have a SQL data model which was originally conceived based on the following two facts:

* Charges would include a stop date (unlike today where  it is open-ended)
* Tariffs would be communicated as a price time series instead of 1 or 24 fixed prices.

It has now been determined that neither of these two changes will actually happen.

We have been asked to consider if we would handle tariffs as a price time series internally anyway, making it more ready for a change planned for the future.

We need to consider whether our current DB design is correct given our new reality, and whether its feasible to still handle tariffs as price time series internally.

**Comment by PerTHenriksen** [comment]
prerequisite: We are receiving CIM XML as inbound format. 
In front of this, a service is mapping inbound ebix XML to CIM, thus the charges domain is to focus on cim only.

**Comment by PerTHenriksen** [comment]
The XSLT mapper is likely to be handled by MD team. 
Postal office might be expanded to support the mapping, by splitting the cim into several messages.

**Comment by PerTHenriksen** [comment]
Communcation between domain;, protobuff. 
Communication to postal office; not determined yet - design session pending.

**Comment by prtandrup** [comment]
We have decided to close this story and continue the work of "how to persist charges" in #205. For now we have a work-in-progress data model, which still needs to be validated against 'new/changing' business requirements. Once the data model is validated, implementing it will be carried out in stories #201 and #202

**Comment by prtandrup** [comment]
We have decided to close this story and continue the work of "how to persist charges" in #205. For now we have a work-in-progress data model, which still needs to be validated against 'new/changing' business requirements. Once the data model is validated, implementing it will be carried out in stories #201 and #202
