### ISSUE TITLE
SendBatchAsync; a Servicebus batch mechanism approach 

### ISSUE THREAD

**Issue by PerTHenriksen** [Energinet-DataHub/geh-charges#1601]
When a "tax tariff" in the "charges-domain" is created or updated all actors must be notified of the change, and "charges-domain" must guarantee that all actors are notified.

Up till now, each actor is notified one by one, this is cumbersome and "charges-domain" can either; not guarantee that all actors are notified or some actors will possibly receive the same notification multiple times.

"charges-domain" therefore need to utilize the servicebus batch mechanism, to make sure all actors are notified once and only once for a "tax tariff" change.
The "IDatavailableNotificationSender" interface in package "Energinet.DataHub.MessageHub.Client" has not implemented support for servicebus batches, so the "dream scenario" would be a SendBatchAsync method in DataAvailableNotificationSender, that takes a collection of dataAvailableNotificationDto alongside a correlationId.

```
public interface IDataAvailableNotificationSender
{
    /// <summary>
    /// Encodes the specified DataAvailableNotification and places it onto the post office DataAvailable queue.
    /// </summary>
    /// <param name="correlationId">The correlation id that can be used to track the data represented by the notification.</param>
    /// <param name="dataAvailableNotificationDto">The notification to send to the post office.</param>
    Task SendAsync(string correlationId, DataAvailableNotificationDto dataAvailableNotificationDto);

    Task SendBatchAsync(string correlationId,
        IReadOnlyCollection<DataAvailableNotificationDto> dataAvailableNotificationDtos);
}

```

**Comment by PerLysemose** [comment]
@PerTHenriksen ingen i teamet vidste noget om denne, så derfor flyttet tilbage til Product Backlog.
