### ISSUE TITLE
Balance supplier charge notification AC 4 + AC 5 - bundling and business reason codes

### ISSUE THREAD

**Issue by PerTHenriksen** [Energinet-DataHub/geh-charges#1649]
### Synopsis

As a datahub user, I would like to verify that the messages generated adhere to bundling rules, and use the business reason code provided in the update request

### Acceptance Criteria

- [x] Implement tests to ensure that business reason codes and bundling functionality.

**Comment by x-platformcoder** [comment]
These test is already included in the testharness as unittests.
The tests, creates a bundle of 10 (D18) operations and comparing that to the corresponding NotifyPriceList of type (D18), same goes for bundle of 10 (D08) and the corresponding NotifyPriceList of type (D08).

**Tests are located in:**
ChargeInformationCimSerializer and ChargePriceCimSerializerTests
