### ISSUE TITLE
GUI - Documentation of price page functionality

### ISSUE THREAD

**Issue by IreneDataHub** [Energinet-DataHub/geh-charges#1657]
Create documentation for GUI functionalities.

Acceptance criteria
- [ ] Document implemented GUI sceen in: https://energinet.atlassian.net/wiki/spaces/D3/pages/217546753/UX+for+charges

**Comment by HenrikSommer** [comment]
Charge UI is in constant development. The current state is documented and upcoming new features should be documented in as they are implemented.
