### ISSUE TITLE
Integration test

### ISSUE THREAD

**Issue by PerLysemose** [Energinet-DataHub/geh-charges#167]
**Reasoning:**
We don´t want to wait for the Integration test enabler to be prioritized so can we do something in the meantime that can cover our need?

**Description:**
We aim for a simple (temporary) solution that can provide us fast feedback once integrations break.

**Acceptance Criterias**

1. Integration test verifies that charges domain can receive a valid Create Charge message and store the data (including price elements) and publish a ChargeCommandAccepted on the ServiceBus.
2. Integration test verifies that charges domain can receive a invalid Create Charge message and publish a ChargeCommandRejected on the ServiceBus, and optionally verify that the charge was not stored.
3. The integration test(s) are executed at least once every day and/or at least per squash merge
4. The integration tests are executed against the U environments.
5. When integration test fails, the team must be informed. 
6. Nice to have: Integration tests can be executed on personal branches and environments

**Comment by HenrikSommer** [comment]
Ready for test.
Comments to ACs:

1. The test verifies that the system publishes confirmation to Postoffice ServiceBus topic. Price elements are not yet implemented in the Charge domain 
2. The test verifies that the system publishes rejection to Postoffice ServiceBus topic
3. The integration test(s) are executed per squash merge
4. The integration tests are executed against the U environment only as per team descision
5. Team is informed by failing pipeline
6. Nice to have: Two dedicated Integration tests can be executed on localhost using personal branches and environments

**Comment by BjarkeMeier** [comment]
@HenrikSommer, is there a highly prioritized bug or issue addressing failure of `GreenEnergyHub.Charges.IntegrationTests.Application.ChangeOfCharges.ChangeOfChargePipelineTests` when running all unit tests in solution? Because otherwise, I'm afraid I cannot accept the issue.

**Comment by HenrikSommer** [comment]
@BjarkeMeier at our team dev session we agreed to address the issue concerning integration test execution in solution before this issue can be accepted. I'm working on a PR with a simple solution.

**Comment by HenrikSommer** [comment]
Integration tests do not test for price elements in the Charges database as per AC4 on [issue 202](https://github.com/Energinet-DataHub/geh-charges/issues/202)
