### ISSUE TITLE
Receive RSM-034 file when peeking and requesting a JSON format

### ISSUE THREAD

**Issue by PerTHenriksen** [Energinet-DataHub/geh-charges#1670]
*Synopsis:*
As a datahub user, 
I want to receive an RSM-034 in json format when Peeking

*Acceptance criteria:*
- [x] (1) When peeking in JSON, Datahub will deliver an RSM-034 in JSON format

**Comment by prtandrup** [comment]
Blocked due system test stopping deployment (authorization issue with client secret)
