### ISSUE TITLE
GUI - Add tabs view to price details drawer

### ISSUE THREAD

**Issue by ManBearTM** [Energinet-DataHub/geh-charges#1686]
We would like to be able to switch between different views within the drawer.

![tabs.png](https://images.zenhubusercontent.com/626fbc6d95e6587091961d95/bb20dfaf-7047-4ec1-a076-7d3b73567b57
)

**Tasks**
- [ ] Create a tabs view 3 tabs (Priser, Beskeder, Historik). They should be blank for now.

**Acceptance Criteria**
- [ ] As a GUI user, I want to be able to switch between different views within the drawer

**Comment by IreneDataHub** [comment]
Test 11.10.2022 
Environment T-001
Acc As a GUI user, I want to be able to switch between different views within the drawer = OK
Prices, messages, history
![image.png](https://images.zenhubusercontent.com/612f6568004bdd03eab7ca46/093fa3a3-f359-4fa0-9e9e-92f0013401e6)

![image.png](https://images.zenhubusercontent.com/612f6568004bdd03eab7ca46/1fa45805-32c9-46a6-bb44-419a83f27687)
