### ISSUE TITLE
Unify InputValidation with BusinessValidation

### ISSUE THREAD

**Issue by PerLysemose** [Energinet-DataHub/geh-charges#171]
Results of current inputvalidation is mapped to the validationresult of businessvalidation.
Inputvalidation should carry out work just like businessvalidation, making mapping obsolete.

ACs
AC1: Inputvalidation is performed like businessvalidation
AC2: Unit test of current inputvalidation

**Comment by bemwen** [comment]
Tested by:
* Verifying the ACs by looking at the code
* Testing that a valid message still gets through on T-environment, manually
* Testing that a single input validation still ends as rejected on T-environment, manually

The unit tests take care of the rest.

AC1: Inputvalidation is performed like businessvalidation - PASS
AC2: Unit test of current inputvalidation - PASS

**AC1:**
The code has been validated to use the same basic concept as business validation. For example they both now inherit from IValidationRule.

**AC2:**
The three existing input validations all have unit tests that pass when run.

![image](https://user-images.githubusercontent.com/12642168/116995640-99e98c80-acda-11eb-877a-d379c7fdc0e9.png)

**Valid message on T-environment:**
A valid charge was sent to T using our "Submit Addition Subscription" postman request with ID "XMDJESUB06"

![image](https://user-images.githubusercontent.com/12642168/116992789-e03cec80-acd6-11eb-9056-999aacce7866.png)

And ended up as accepted on the service bus:

![image](https://user-images.githubusercontent.com/12642168/116993140-55a8bd00-acd7-11eb-9b6a-169e2437c5a0.png)

**Invalid input validation on T-environment:**
An invalid charge was sent to T using our "Submit Addition Subscription With Failed VR.150" postman request.

![image](https://user-images.githubusercontent.com/12642168/116993813-3fe7c780-acd8-11eb-9ddf-143115baea12.png)

The request ended as rejected as expected:

![image](https://user-images.githubusercontent.com/12642168/116993874-542bc480-acd8-11eb-9399-dd95e1ae15d4.png)
