### ISSUE TITLE
Deployment monitoring with notification in Teams when deployment fails

### ISSUE THREAD

**Issue by PerTHenriksen** [Energinet-DataHub/geh-charges#1720]
### Synopsis
Deployment to development, test, and production environments fails from time to time. As a devops team, we want to be notified through Teams whenever a deployment fails.

### Acceptance Criteria
- [x] Given a deployment to development, test, and production environments, when a deployment is not successful, then the proper Teams channel is notified.

### Tech notes
Health checks in Azure notify a Teams channel, whenever a function or one of its dependencies is not healthy. Similar functionality is desired when a deployment fails in GitHub Actions.

**Comment by x-platformcoder** [comment]
Loos like Mighty Ducks fixed this one for us: https://teams.microsoft.com/l/message/19:91c8a12a0ed34734b72b5678596377f5@thread.tacv2/1668172358823?tenantId=f7619355-6c67-4100-9a78-1847f30742e2&groupId=e1b7877a-ee7d-4505-a4b2-4989abc2d22a&parentMessageId=1668172358823&teamName=GreenForce&channelName=Developers&createdTime=1668172358823&allowXTenantAccess=false
