### ISSUE TITLE
Update dependencies october 2022

### ISSUE THREAD

**Issue by x-platformcoder** [Energinet-DataHub/geh-charges#1724]
Upgrading nuget packages for charges and charge client library, reported from depandabot.

Bumps Energinet.DataHub.MessageHub.Client from 3.1.0 to 3.3.0.
Bumps Energinet.DataHub.Core.TestCommon from 3.4.0 to 3.5.0.
Bumps Energinet.DataHub.Core.App.WebApp from 7.0.0 to 7.1.0.
Bumps Microsoft.Extensions.Diagnostics.HealthChecks from 6.0.8 to 6.0.9.
Bumps Energinet.DataHub.Core.SchemaValidation from 1.0.13 to 2.1.1.
Bumps SimpleInjector from 5.4.0 to 5.4.1.
Bumps Microsoft.NET.Test.Sdk from 17.3.1 to 17.3.2.
Bumps Google.Protobuf from 3.21.5 to 3.21.7.
Bumps NodaTime from 3.1.2 to 3.1.3.
Bumps Grpc.Tools from 2.48.1 to 2.49.1.

**Comment by prtandrup** [comment]
Blocked due system test stopping deployment (authorization issue with client secret)
