### ISSUE TITLE
Consume ActorCreated event from marketparticipant domain

### ISSUE THREAD

**Issue by x-platformcoder** [Energinet-DataHub/geh-charges#1726]
### Synopsis
Implement ActorCreatedIntegrationEvent, to handle all newly created actors from marketparticipant domain

### Acceptance Criteria
- [x] Given an ActorCreatedIntegrationEvent is received 
When a new Actor is created 
Then create the actor in Charges Marketparticipant table

### Tech notes
Use protobuf contracts directly, because the SharedIntegrationParser in the client will be discontinued in the future.
These events will co-exist with the mega-events, thus a created actor will result in two events.

**Comment by prtandrup** [comment]
### Initial test in U-001: 
:x: new market participant not stored.

**Test flow:**
Turned off `MarketParticipantPersisterEndpoint` in Azure to avoid it from persisting the new market participant by using the `ActorUpdatedIntegrationEvent`.

Through the frontend, I created a new organization and added a new actor to it (with role Energy Supplier). 

That resulted in two integration events from the market participant domain as expected:
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/1500bef8-f064-4119-b26e-a77a1a623446)

The `ActorCreatedIntegrationEvent` below:
````
{
	"actorId": "6631b43e-ea51-480a-924e-2aec2b99d9c9",
	"organizationId": {
		"value": "d456e76e-3abc-4bc3-4496-08daad154029"
	},
	"actorNumber": {
		"value": "8100000000993",
		"type": 1
	},
	"status": 1,
	"name": {
		"value": "xTestEnergySupplier"
	},
	"businessRoles": [
		3
	],
	"actorMarketRoles": [
		{
			"gridAreas": [
				{
					"id": "0cf56e44-d021-411c-936d-3979d8b2c49c",
					"meteringPointTypes": [
						"Unknown",
						"D01VeProduction",
						"D02Analysis",
						"D03NotUsed",
						"D04SurplusProductionGroup6",
						"D05NetProduction",
						"D06SupplyToGrid",
						"D07ConsumptionFromGrid",
						"D08WholeSaleServicesInformation",
						"D09OwnProduction",
						"D10NetFromGrid",
						"D11NetToGrid",
						"D12TotalConsumption",
						"D13NetLossCorrection",
						"D14ElectricalHeating",
						"D15NetConsumption",
						"D17OtherConsumption",
						"D18OtherProduction",
						"D20ExchangeReactiveEnergy",
						"D99InternalUse",
						"E17Consumption",
						"E18Production",
						"E20Exchange"
					]
				}
			],
			"function": 12
		}
	],
	"id": "99e318e6-ab39-49b2-92f1-abee64d15d2a",
	"eventCreated": "2022-10-13T12:33:21.1569706Z"
}
````

This was not persisted in Charges:
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/825ccfc8-0b83-46b6-959f-3dd9a1611fec)

And application insights shows **no requests** for the `MarketParticipantCreatedEndpoint`:
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/32b4500e-e827-4f83-be54-c6795cea4203)

**Comment by prtandrup** [comment]
### Re-tested in U-001

MarketParticipantPersister is disabled:
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/3f791096-be9b-4599-9c02-c966b403e2c4)
New organisation created in frontend.
Actor added to organisation with ID: 8100000001020:
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/1831886c-3479-4fcf-a6b9-b9cad84242e0)

The `ActorCreatedIntegrationEvent` below:
````
{
	"actorId": "e4ff8282-0b0f-4428-ba64-4c804ed5b169",
	"organizationId": {
		"value": "2e248bf4-5b28-4bd9-4498-08daad154029"
	},
	"actorNumber": {
		"value": "8100000001020",
		"type": 1
	},
	"status": 1,
	"name": {
		"value": "xTestEnergySupplier"
	},
	"businessRoles": [
		3
	],
	"actorMarketRoles": [
		{
			"gridAreas": [
				{
					"id": "0cf56e44-d021-411c-936d-3979d8b2c49c",
					"meteringPointTypes": [
						"Unknown",
						"D01VeProduction",
						"D02Analysis",
						"D03NotUsed",
						"D04SurplusProductionGroup6",
						"D05NetProduction",
						"D06SupplyToGrid",
						"D07ConsumptionFromGrid",
						"D08WholeSaleServicesInformation",
						"D09OwnProduction",
						"D10NetFromGrid",
						"D11NetToGrid",
						"D12TotalConsumption",
						"D13NetLossCorrection",
						"D14ElectricalHeating",
						"D15NetConsumption",
						"D17OtherConsumption",
						"D18OtherProduction",
						"D20ExchangeReactiveEnergy",
						"D99InternalUse",
						"E17Consumption",
						"E18Production",
						"E20Exchange"
					]
				}
			],
			"function": 12
		}
	],
	"id": "85e59187-6e7c-4d51-9276-13d8e781696e",
	"eventCreated": "2022-10-17T12:30:27.1075608Z"
}
````

Persisted in ChargesDB: 
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/3d0384a4-2c3b-4a04-9f81-db763cbe0bb4)

**Comment by prtandrup** [comment]
### Another test in U-001 with both Functions enabled

:x: Issue: When persisting, the `organizationId` is persisted as `B2CActorId`. 

Created new organisation and actor with ID 8100000001037.
In this case `MarketParticipantCreated` was apparently the last to execute, why B2CActorId was set:

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/3f2f877b-84f4-48cf-a04d-80485c54fb5d)

**ActorCreatedntegrationEvent**
````
{"actorId":"37af8d14-1933-44ca-8d84-a74dde61aec7","organizationId":{"value":"3773c979-602f-4dca-449b-08daad154029"},"actorNumber":{"value":"8100000001037","type":1},"status":1,"name":{"value":"xTestEnergySupplier"},"businessRoles":[3],"actorMarketRoles":[{"gridAreas":[{"id":"0cf56e44-d021-411c-936d-3979d8b2c49c","meteringPointTypes":["Unknown","D01VeProduction","D02Analysis","D03NotUsed","D04SurplusProductionGroup6","D05NetProduction","D06SupplyToGrid","D07ConsumptionFromGrid","D08WholeSaleServicesInformation","D09OwnProduction","D10NetFromGrid","D11NetToGrid","D12TotalConsumption","D13NetLossCorrection","D14ElectricalHeating","D15NetConsumption","D17OtherConsumption","D18OtherProduction","D20ExchangeReactiveEnergy","D99InternalUse","E17Consumption","E18Production","E20Exchange"]}],"function":12}],"id":"0be2030e-de8a-4ece-8b81-1eebaaad45a5","eventCreated":"2022-10-17T12:53:25.7828768Z"}
````

**Comment by prtandrup** [comment]
### Re-tested in U-001 :heavy_check_mark:

Created new organisation and added new actor with ID: 8100000001044

`ActorCreatedIntegrationEvent`:
````
{
	"actorId": "31cfdd3b-f9bb-4ecc-8213-3a0e55cf9c5f",
	"organizationId": {
		"value": "a50edee5-cccb-4255-449c-08daad154029"
	},
	"actorNumber": {
		"value": "8100000001044",
		"type": 1
	},
	"status": 1,
	"name": {
		"value": "xTestEnergySupplier"
	},
	"businessRoles": [
		3
	],
	"actorMarketRoles": [
		{
			"gridAreas": [
				{
					"id": "0cf56e44-d021-411c-936d-3979d8b2c49c",
					"meteringPointTypes": [
						"Unknown",
						"D01VeProduction",
						"D02Analysis",
						"D03NotUsed",
						"D04SurplusProductionGroup6",
						"D05NetProduction",
						"D06SupplyToGrid",
						"D07ConsumptionFromGrid",
						"D08WholeSaleServicesInformation",
						"D09OwnProduction",
						"D10NetFromGrid",
						"D11NetToGrid",
						"D12TotalConsumption",
						"D13NetLossCorrection",
						"D14ElectricalHeating",
						"D15NetConsumption",
						"D17OtherConsumption",
						"D18OtherProduction",
						"D20ExchangeReactiveEnergy",
						"D99InternalUse",
						"E17Consumption",
						"E18Production",
						"E20Exchange"
					]
				}
			],
			"function": 12
		}
	],
	"id": "cb46d64d-a3cf-4894-98ec-b20e1c0c09e7",
	"eventCreated": "2022-10-18T06:10:50.3897882Z"
}
````

Persisted in ChargesDB: 
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/a4e66ff1-97c8-4111-92b2-57106fa72610)

Also verified this with MarketParticipantPersister disabled.

**Comment by prtandrup** [comment]
### Tested in T-001:

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/60c0a69b-04c4-452b-91a4-548279f2f9c7)

Created new organisation with new actor ID: 8100000001068

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/5058f8af-f4bf-49ea-9527-02e68dbab6b2)

`ActorCreatedIntegrationEvent`:
````
{
	"actorId": "d14ed244-f391-4f9d-b027-6cd2755d2b7c",
	"organizationId": {
		"value": "35963115-3a94-431a-8de9-08dab0d18528"
	},
	"actorNumber": {
		"value": "8100000001068",
		"type": 1
	},
	"status": 1,
	"name": {
		"value": "xTestEnergySupplier"
	},
	"businessRoles": [
		3
	],
	"actorMarketRoles": [
		{
			"gridAreas": [
				{
					"id": "0cf56e44-d021-411c-936d-3979d8b2c49c",
					"meteringPointTypes": [
						"Unknown",
						"D01VeProduction",
						"D02Analysis",
						"D03NotUsed",
						"D04SurplusProductionGroup6",
						"D05NetProduction",
						"D06SupplyToGrid",
						"D07ConsumptionFromGrid",
						"D08WholeSaleServicesInformation",
						"D09OwnProduction",
						"D10NetFromGrid",
						"D11NetToGrid",
						"D12TotalConsumption",
						"D13NetLossCorrection",
						"D14ElectricalHeating",
						"D15NetConsumption",
						"D17OtherConsumption",
						"D18OtherProduction",
						"D20ExchangeReactiveEnergy",
						"D99InternalUse",
						"E17Consumption",
						"E18Production",
						"E20Exchange"
					]
				}
			],
			"function": 12
		}
	],
	"id": "3ac0679d-7cf6-4375-a717-51af727ff78b",
	"eventCreated": "2022-10-18T06:25:58.8918793Z"
}
````

Persisted in ChargesDB:

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/c68a8c4a-83de-4238-916e-81a2e673755f)

We came to realize that Name wasn't updated. So another PR is on the way.
