### ISSUE TITLE
 Consume ActorStatusChanged & ActorExternalIdChanged event from marketparticipant domain

### ISSUE THREAD

**Issue by x-platformcoder** [Energinet-DataHub/geh-charges#1727]
### Synopsis
Implement ActorStatusChangedIntegrationEvent and ActorExternalIdChangedIntegrationEvent , to handle the changes on an actor

### Acceptance Criteria
- [ ] Given an ActorStatusChangedIntegrationEvent is received When an Actor has changed status Then update status on actor in Charges Marketparticipant table
- [ ] Given an ActorExternalIdChangedIntegrationEvent is received When an Actor has changed external id Then update BC2ActorId on actor in Charges Marketparticipant table

### Tech notes
~~Use protobuf contracts directly, because the SharedIntegrationParser in the client will be discontinued in the future.~~ moved to 1732

**Comment by Mech0z** [comment]
Tested OK, when changing from New to Active, Status and B2CactorId is updated in Charges db.
