### ISSUE TITLE
Domain test: Chronological order is correct when peeking in JSON

### ISSUE THREAD

**Issue by prtandrup** [Energinet-DataHub/geh-charges#1735]
Currently our domain test verifies chronological order in outgoing XML notifications (D18 and D08)

With the introduction of outgoing JSON messages, we want to extend our domain test to verify chronological order in outgoing JSON notifications (D18 and D08) as well.

Out of scope: 
- Rejections and confirmation, not relevant.

**Acceptance criteria:**

Below are covered by domain tests:

- [x] 1 Given a grid access provider sends a Charge Information (D18) request with multiple operations for the same Charge
When an energy supplier peeks
Then it gets a Notification (D18) message with the multiple operations listed in the same chronological order as they were received in the request.
<br>

- [x] 2 Given a grid access provider sends a Charge Prices (D08) request with multiple price series for the same Charge
When an energy supplier peeks
Then it gets a Notification (D08) message with the multiple price series listed in the same chronological order as they were received in the request.

**Comment by prtandrup** [comment]
For the tester:

AC1: Look for `Ingestion_BundleWithMultipleOperationsForSameCharge_NotificationsWithChronologicallyOrderedOperationsAsJson()`

AC2: Look for this test: `Ingestion_BundleWithMultiplePriceSeriesForSameSubscription__NotificationsWithChronologicallyOrderedPriceSeriesAsJson()`

**Comment by HenrikSommer** [comment]
With an extra Pull Request during the test, the AC's are now covered.
