### ISSUE TITLE
Ensure (or document) that we have working software

### ISSUE THREAD

**Issue by PerLysemose** [Energinet-DataHub/geh-charges#174]
-- Charge domæne mvp application insight, der er ikke vendor agnostic løsning.  -- 
inddrage SME for at høste datahub monitoreringsforventninger på den længere bane. 

Telemetry dashboard?
Monitor uptime?
Automated domain/integration tests?

Differentiate dev and test environment and gates?
Automatic notifications to the team?

ACs:
AC: dashboard der viser oversigt med events i hvilke køer. 
AC: indhold af dead letter køer. 
~|ac: time tracking, på transaktioner.~
~nice to know ac: hvor lang tid ligger events i køer.~

**Comment by BjarkeMeier** [comment]
**Notes for tester**
The following ACs has been discarded due to prioritization in team Volt:

ac: time tracking, på transaktioner.
nice to know ac: hvor lang tid ligger events i køer.

**Comment by prtandrup** [comment]
Tested OK on T

AC# Dashboard provides an overview of the different events in queue -> PASS
AC# Deadletter queue added -> PASS 

The stats in DeadLetter and Active messages were not verified by any test here. I suggest we take a look at this later to get a better understanding of the stats.

![image](https://user-images.githubusercontent.com/71757561/117251800-6aa35e80-ae45-11eb-975a-9b5df2b908a8.png)
