### ISSUE TITLE
When notification is peeked as JSON, it does not show 'Besked ID', 'RSM' and 'Aktør' values in Frontend page 'Fremsøg forretningsbesked'

### ISSUE THREAD

**Issue by prtandrup** [Energinet-DataHub/geh-charges#1761]
### Current Behavior
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/1e801acf-9516-44a1-acc8-4c0471ac65c7)

### How to reproduce
As Grid Access Provider submits valid Charge Information Request (D18)
As Energy Supplier, peek the notification as JSON
In Frontend, search the notification in 'Fremsøg forretningsbesked'

### Additional context/screenshots

Team Titans is working on a story, that will solve this "bug", which is actually just a missing feature:
https://app.zenhub.com/workspaces/titans-60d029726fc7570010362aa7/issues/energinet-datahub/geh-post-office/565

**Comment by HenrikSommer** [comment]
Closed, Team Titans is working on a story, that will solve this "bug", which is actually just a missing feature:
https://app.zenhub.com/workspaces/titans-60d029726fc7570010362aa7/issues/energinet-datahub/geh-post-office/565
