### ISSUE TITLE
D08 request - >Reject missing - effectiveDate does not match start date

### ISSUE THREAD

**Issue by IreneDataHub** [Energinet-DataHub/geh-charges#1762]
Grid / DDM receive an confirm when they request RSM-033 with reason code D08 even if there is no match between effective date and start date.
Expected a rejection
Also be aware that the supllier DDQ get a notify RSM-034 for the period 1. July til 1. August, and not that the DDM made the requst for 15. June to 1. July

Please also investigate ticket #1763 - Maybe they are related

RSM-033 specifying different dates:

Besked Id: DocId2022-10-14T11:44:02.908Z
Trace Id: 380216f9c7bae1459ddd55dfcda0df90
<?xml version="1.0" encoding="UTF-8"?>
<cim:RequestChangeOfPriceList_MarketDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cim="urn:ediel.org:structure:requestchangeofpricelist:0:1" xsi:schemaLocation="urn:ediel.org:structure:requestchangeofpricelist:0:1 urn-ediel-org-structure-requestchangeofpricelist-0-1.xsd">
	<cim:mRID>DocId2022-10-14T11:44:02.908Z</cim:mRID>
	<cim:type>D10</cim:type>
	<cim:process.processType>D08</cim:process.processType>
	<cim:businessSector.type>23</cim:businessSector.type>
	<cim:sender_MarketParticipant.mRID codingScheme="A10">8100000000016</cim:sender_MarketParticipant.mRID>
	<cim:sender_MarketParticipant.marketRole.type>DDM</cim:sender_MarketParticipant.marketRole.type>
	<cim:receiver_MarketParticipant.mRID codingScheme="A10">5790001330552</cim:receiver_MarketParticipant.mRID>
	<cim:receiver_MarketParticipant.marketRole.type>DDZ</cim:receiver_MarketParticipant.marketRole.type>
	<cim:createdDateTime>2022-10-14T11:44:02Z</cim:createdDateTime>
	<cim:MktActivityRecord>
		<cim:mRID>OpId2022-10-14T11:44:02.908Z</cim:mRID>
		<cim:ChargeGroup>
			<cim:ChargeType>
				<cim:chargeTypeOwner_MarketParticipant.mRID codingScheme="A10">8100000000016</cim:chargeTypeOwner_MarketParticipant.mRID>
				<cim:type>D01</cim:type>
				<cim:mRID>ABO01</cim:mRID>
				<cim:effectiveDate>2022-06-30T22:00:00Z</cim:effectiveDate>
				<cim:Series_Period>
					<cim:resolution>P1M</cim:resolution>
					<cim:timeInterval>
						<cim:start>2022-06-14T22:00Z</cim:start>
						<cim:end>2022-06-30T22:00Z</cim:end>
					</cim:timeInterval>
					<cim:Point>
						<cim:position>1</cim:position>
						<cim:price.amount>200.001</cim:price.amount>
					</cim:Point>
				</cim:Series_Period>
			</cim:ChargeType>
		</cim:ChargeGroup>
	</cim:MktActivityRecord>
</cim:RequestChangeOfPriceList_MarketDocument>

Confirm:
Besked Id: 10a848cdbf0b4845bee94d181e196ef0
Trace Id: dc6fdab27a2c924ca3a21b063fe941ee
<?xml version="1.0" encoding="utf-8"?>
<cim:ConfirmRequestChangeOfPriceList_MarketDocument xmlns:cim="urn:ediel.org:structure:confirmrequestchangeofpricelist:0:1">
  <cim:mRID>10a848cdbf0b4845bee94d181e196ef0</cim:mRID>
  <cim:type>D11</cim:type>
  <cim:process.processType>D08</cim:process.processType>
  <cim:businessSector.type>23</cim:businessSector.type>
  <cim:sender_MarketParticipant.mRID codingScheme="A10">5790001330552</cim:sender_MarketParticipant.mRID>
  <cim:sender_MarketParticipant.marketRole.type>DDZ</cim:sender_MarketParticipant.marketRole.type>
  <cim:receiver_MarketParticipant.mRID codingScheme="A10">8100000000016</cim:receiver_MarketParticipant.mRID>
  <cim:receiver_MarketParticipant.marketRole.type>DDM</cim:receiver_MarketParticipant.marketRole.type>
  <cim:createdDateTime>2022-10-14T10:04:06Z</cim:createdDateTime>
  <cim:reason.code>A01</cim:reason.code>
  <cim:MktActivityRecord>
    <cim:mRID>3d032a3ff02b4f2c8aa96fdce7bca997</cim:mRID>
    <cim:originalTransactionIDReference_MktActivityRecord.mRID>OpId2022-10-14T10:03:55.339Z</cim:originalTransactionIDReference_MktActivityRecord.mRID>
  </cim:MktActivityRecord>
</cim:ConfirmRequestChangeOfPriceList_MarketDocument>

RSM-034

?xml version="1.0" encoding="utf-8"?>
<cim:NotifyPriceList_MarketDocument xmlns:cim="urn:ediel.org:structure:notifypricelist:0:1">
    <cim:mRID>c151836829f743bbb19645d71e512081</cim:mRID>
    <cim:type>D12</cim:type>
    <cim:process.processType>D08</cim:process.processType>
    <cim:businessSector.type>23</cim:businessSector.type>
    <cim:sender_MarketParticipant.mRID codingScheme="A10">5790001330552</cim:sender_MarketParticipant.mRID>
    <cim:sender_MarketParticipant.marketRole.type>DDZ</cim:sender_MarketParticipant.marketRole.type>
    <cim:receiver_MarketParticipant.mRID codingScheme="A10">8100000000122</cim:receiver_MarketParticipant.mRID>
    <cim:receiver_MarketParticipant.marketRole.type>DDQ</cim:receiver_MarketParticipant.marketRole.type>
    <cim:createdDateTime>2022-10-14T11:59:31Z</cim:createdDateTime>
    <cim:MktActivityRecord>
        <cim:mRID>6da4fe2f0a5b4a788d6da9204e9ab968</cim:mRID>
        <cim:ChargeGroup>
            <cim:ChargeType>
                <cim:chargeTypeOwner_MarketParticipant.mRID codingScheme="A10">8100000000016</cim:chargeTypeOwner_MarketParticipant.mRID>
                <cim:type>D01</cim:type>
                <cim:mRID>ABO01</cim:mRID>
                <cim:effectiveDate>2022-06-30T22:00:00Z</cim:effectiveDate>
                <cim:Series_Period>
                    <cim:resolution>P1M</cim:resolution>
                    <cim:timeInterval>
                        <cim:start>2022-06-30T22:00Z</cim:start>
                        <cim:end>2022-07-31T22:00Z</cim:end>
                    </cim:timeInterval>
                    <cim:Point>
                        <cim:position>1</cim:position>
                        <cim:price.amount>200.001000</cim:price.amount>
                    </cim:Point>
                </cim:Series_Period>
            </cim:ChargeType>
        </cim:ChargeGroup>
    </cim:MktActivityRecord>
</cim:NotifyPriceList_MarketDocument>

**Comment by prtandrup** [comment]
Fixed by story #1765
