### ISSUE TITLE
RSM-033 RequestChangeOfPriceList D08 - Position doesn't match the indication of start and end, but the message is confirm instead of rejectingf a reject

### ISSUE THREAD

**Issue by IreneDataHub** [Energinet-DataHub/geh-charges#1763]
When DDM/Grid send a request RequestChangeOfPriceList/ RSM-033 D08 they get an confirm, but we expect a rejecting when position doesn't match timeperiod in the RequestChangeOfPriceList D08

Expect a reject 
![image.png](https://images.zenhubusercontent.com/612f6568004bdd03eab7ca46/ae37de20-0298-4ff9-8a6d-b79113a57d4f)

Please also investigate ticket #1762 - Maybe they are related
RSM-033 request RequestChangeOfPriceList D08 

<?xml version="1.0" encoding="UTF-8"?>
<cim:RequestChangeOfPriceList_MarketDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cim="urn:ediel.org:structure:requestchangeofpricelist:0:1" xsi:schemaLocation="urn:ediel.org:structure:requestchangeofpricelist:0:1 urn-ediel-org-structure-requestchangeofpricelist-0-1.xsd">
	<cim:mRID>DocId{{$isoTimestamp}}</cim:mRID>
	<cim:type>D10</cim:type>
	<cim:process.processType>D08</cim:process.processType>
	<cim:businessSector.type>23</cim:businessSector.type>
	<cim:sender_MarketParticipant.mRID codingScheme="A10">{{MarketParticipantGln}}</cim:sender_MarketParticipant.mRID>
	<cim:sender_MarketParticipant.marketRole.type>{{MarketParticipantRole}}</cim:sender_MarketParticipant.marketRole.type>
	<cim:receiver_MarketParticipant.mRID codingScheme="A10">5790001330552</cim:receiver_MarketParticipant.mRID>
	<cim:receiver_MarketParticipant.marketRole.type>DDZ</cim:receiver_MarketParticipant.marketRole.type>
	<cim:createdDateTime>{{ISO8601Timestamp}}</cim:createdDateTime>
	<cim:MktActivityRecord>
		<cim:mRID>OpId{{$isoTimestamp}}</cim:mRID>
		<cim:ChargeGroup>
			<cim:ChargeType>
				<cim:chargeTypeOwner_MarketParticipant.mRID codingScheme="A10">{{MarketParticipantGln}}</cim:chargeTypeOwner_MarketParticipant.mRID>
				<cim:type>D01</cim:type>
				<cim:mRID>ABO01</cim:mRID>
				<cim:effectiveDate>2022-06-14T22:00:00Z</cim:effectiveDate>
				<cim:Series_Period>
					<cim:resolution>P1M</cim:resolution>
					<cim:timeInterval>
						<cim:start>2022-06-14T22:00Z</cim:start>
						<cim:end>2022-07-31T22:00Z</cim:end>
					</cim:timeInterval>
					<cim:Point>
						<cim:position>1</cim:position>
						<cim:price.amount>200.001</cim:price.amount>
					</cim:Point>
				</cim:Series_Period>
			</cim:ChargeType>
		</cim:ChargeGroup>
	</cim:MktActivityRecord>
</cim:RequestChangeOfPriceList_MarketDocument>

Confirm
?xml version="1.0" encoding="utf-8"?>
<cim:ConfirmRequestChangeOfPriceList_MarketDocument xmlns:cim="urn:ediel.org:structure:confirmrequestchangeofpricelist:0:1">
    <cim:mRID>8147eb2bb4b24214b1d8441ffb8da9b9</cim:mRID>
    <cim:type>D11</cim:type>
    <cim:process.processType>D08</cim:process.processType>
    <cim:businessSector.type>23</cim:businessSector.type>
    <cim:sender_MarketParticipant.mRID codingScheme="A10">5790001330552</cim:sender_MarketParticipant.mRID>
    <cim:sender_MarketParticipant.marketRole.type>DDZ</cim:sender_MarketParticipant.marketRole.type>
    <cim:receiver_MarketParticipant.mRID codingScheme="A10">8100000000016</cim:receiver_MarketParticipant.mRID>
    <cim:receiver_MarketParticipant.marketRole.type>DDM</cim:receiver_MarketParticipant.marketRole.type>
    <cim:createdDateTime>2022-10-14T12:14:01Z</cim:createdDateTime>
    <cim:reason.code>A01</cim:reason.code>
    <cim:MktActivityRecord>
        <cim:mRID>c4af5bd8752149d3a389ae8df165ba77</cim:mRID>
        <cim:originalTransactionIDReference_MktActivityRecord.mRID>OpId2022-10-14T12:13:51.744Z</cim:originalTransactionIDReference_MktActivityRecord.mRID>
    </cim:MktActivityRecord>
</cim:ConfirmRequestChangeOfPriceList_MarketDocument>

Notify to supplier - doesn't match request from DDM
It change the notify to 15. June to 1. July but the request was to 1. August

Besked Id:
Trace Id: 2149eed8e8424240bd7463eec2316dc0
{
  "NotifyPriceList_MarketDocument": {
    "mRID": "95527bb9e0dc4cabae1123552b39945b",
    "businessSector.type": {
      "value": "23"
    },
    "createdDateTime": "2022-10-14T12:17:40.6732047Z",
    "process.processType": {
      "value": "D08"
    },
    "receiver_MarketParticipant.mRID": {
      "codingScheme": "A10",
      "value": "8100000000122"
    },
    "receiver_MarketParticipant.marketRole.type": {
      "value": "DDQ"
    },
    "sender_MarketParticipant.mRID": {
      "codingScheme": "A10",
      "value": "5790001330552"
    },
    "sender_MarketParticipant.marketRole.type": {
      "value": "DDZ"
    },
    "type": {
      "value": "D12"
    },
    "MktActivityRecord": [
      {
        "mRID": "5cf416a332654ef28f012524eb2e6552",
        "ChargeGroup": {
          "ChargeType": [
            {
              "mRID": "ABO01",
              "chargeTypeOwner_MarketParticipant.mRID": {
                "codingScheme": "A10",
                "value": "8100000000016"
              },
              "effectiveDate": "2022-06-14T22:00:00Z",
              "type": {
                "value": "D01"
              },
              "Series_Period": [
                {
                  "resolution": "P1M",
                  "timeInterval": {
                    "start": {
                      "value": "2022-06-14T22:00Z"
                    },
                    "end": {
                      "value": "2022-06-30T22:00Z"
                    }
                  },
                  "Point": [
                    {
                      "position": {
                        "value": 1
                      },
                      "price.amount": {
                        "value": 200.001000

**Comment by prtandrup** [comment]
Verified on T-001. Ready for test.

**Comment by prtandrup** [comment]
### Tested in T-001 :heavy_check_mark:
Pair-tested with Irene

We had a look at the written unit tests and then we submitted an irregular price series crossing leap year, which worked. We also violated the `NumberOfPointsMatchTimeIntervalAndResolutionRule` and saw the rejection.

And here is a notification of the one crossing leap year: 
````
    <cim:MktActivityRecord>
        <cim:mRID>4a8886d30ff4413e90c1e17d754304d1</cim:mRID>
        <cim:ChargeGroup>
            <cim:ChargeType>
                <cim:chargeTypeOwner_MarketParticipant.mRID codingScheme="A10">8100000000016</cim:chargeTypeOwner_MarketParticipant.mRID>
                <cim:type>D02</cim:type>
                <cim:mRID>FeeId039</cim:mRID>
                <cim:effectiveDate>2023-02-11T23:00:00Z</cim:effectiveDate>
                <cim:Series_Period>
                    <cim:resolution>P1M</cim:resolution>
                    <cim:timeInterval>
                        <cim:start>2023-02-11T23:00Z</cim:start>
                        <cim:end>2023-03-31T22:00Z</cim:end>
                    </cim:timeInterval>
                    <cim:Point>
                        <cim:position>1</cim:position>
                        <cim:price.amount>199.950000</cim:price.amount>
                    </cim:Point>
                    <cim:Point>
                        <cim:position>2</cim:position>
                        <cim:price.amount>299.950000</cim:price.amount>
                    </cim:Point>
                </cim:Series_Period>
            </cim:ChargeType>
        </cim:ChargeGroup>
    </cim:MktActivityRecord>
````
