### ISSUE TITLE
GUI - support download of charges

### ISSUE THREAD

**Issue by PerTHenriksen** [Energinet-DataHub/geh-charges#1766]
We would like to be able to download charge details. 

### Accept criteria 
- [ ] 1 Pressing the dowload will save all fetched data, not only the shown. I.e. in case of the screenshot, the file is to contain 107 records. 

- [ ] 2 Download format is expected to be in semicolon delimited CSV UTF-8 (CSV), as it can imported in excel directly. See attached example file. ![image.png](https://images.zenhubusercontent.com/60bdf7bbfa2182da7fd5cc6d/aa0f7e90-42bd-4e02-af89-19f0331cf0ab)

- [ ] 3 Header in downloaded file reflect the chosen language (DA | ENG)

- [ ] 4 The file is to be named either "Prisinformationer " Timestamp, when language is Danish, and "Charge information" timestamp, when English. Timestamp is YYYY-MM-DD HH_MI_SS
Example: "Prisinformationer 2022-10-17 15_39_01.CSV"

- [ ] 5 Include VAT (Da: Moms) and Description (DA: Beskrivelse)

![image.png](https://images.zenhubusercontent.com/60bdf7bbfa2182da7fd5cc6d/74c0ee75-b9d1-499b-a57f-d63db7984dfb)

Example file here - CAPS LOCK FOR VISIBILITY:
[Charges_download_CSV.csv](https://github.com/Energinet-DataHub/geh-charges/files/9800921/Charges_download_CSV.csv)

**Comment by PerTHenriksen** [comment]
[Charges_download_CSV.csv](https://github.com/Energinet-DataHub/geh-charges/files/9800916/Charges_download_CSV.csv)

**Comment by IreneDataHub** [comment]
Small change after test:
ID change to Pris ID or Price ID
Sort by Pris ID
Owner shows with GLN and owner name in two colouns
