### ISSUE TITLE
Extend the Charges results list in GUI with Charge Periods, including future states

### ISSUE THREAD

**Issue by prtandrup** [Energinet-DataHub/geh-charges#1799]
Currently, only one row per charge is listed in the search results, although more charge periods for it may exist.

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/a513f3b9-f96a-4439-a135-06af4a717024)

With this story, all active charge periods for a charge matching the search criteria must be listed in the search result list.
This includes future charges and future charge periods, e.g. created in 2023 or later.

**Assumption:**
The data layer used is unchanged, i.e. still based on the command stack data.

**Acceptance criteria**

- [ ] 1 Given a charge exists with the following charge periods 

1st valid from 01/10/2022
2nd from 02/10/2022 
3rd from 01/01/2023, which is also stopped at 01/06/2023

When searching charges in frontend with default search criteria
Then all 3 charge period results are displayed in the list with their own data, sorted by ChargeID (Ascending) and then by FromDateTime (Descending).
<br>

- [ ] 2 Given a charge is created with effective date next year
When searching charges in frontend with default search criteria
Then it appears in the results list
<br>

- [ ] 3 ~~Given a period is clicked and the drawer is opened
When looking at the date range picker
Then the start date = the period's start date
AND the end date is either
**the period's end date (if filled)**
OR
**today (if period's end date is not filled + start is today or earlier)**
OR 
**same as start (if period's end date is not filled + start is in the future)**~~
<br>

- [ ] 4. Any changes done to frontend must be reflected in the [GUI documentation](https://energinet.atlassian.net/wiki/spaces/D3/pages/217546753/UX+for+charges) in Confluence

**Comment by prtandrup** [comment]
Ready for test.
For AC1 and AC2; search for SubId038 in T-001.
For AC4 => follow this link:
https://energinet.atlassian.net/wiki/spaces/D3/pages/217546753/UX+for+charges#S%C3%B8geresultat

**Comment by IreneDataHub** [comment]
16.11.2022 Environment T-001
Test
AC 1: Status OK
![image.png](https://images.zenhubusercontent.com/612f6568004bdd03eab7ca46/3ff9c30d-f5d8-4bc5-9ed9-8d12579435cd)
Message ID shows correct
![image.png](https://images.zenhubusercontent.com/612f6568004bdd03eab7ca46/388198fb-d62e-4d78-bf16-599e77abe8fe)
AC 2:
![image.png](https://images.zenhubusercontent.com/612f6568004bdd03eab7ca46/4f23a9eb-c90a-41e7-93d8-2efe18d0760e)
Message ID shows correct
AC4: OK
De fremsøgte priser vises i en liste, med et valgfrit antal priser pr. side, samt mulighed for at se øvrige sider. Det totale antal priser vises som overskrift, samt i sideviseren til højre. Sortering som udgangspunkt på pris id (stigende) og derefter gyldig fra (faldende),
