### ISSUE TITLE
AC 1 + AC 2 Create a charge via the GUI 

### ISSUE THREAD

**Issue by PerTHenriksen** [Energinet-DataHub/geh-charges#1836]
We need to be able to create a charge information via GUI

charges to be created via events. Rejected charges are not displayed. 

![image.png](https://images.zenhubusercontent.com/60bdf7bbfa2182da7fd5cc6d/84d1f491-a709-4481-bca2-4093b8c487f1)

![image.png](https://images.zenhubusercontent.com/60bdf7bbfa2182da7fd5cc6d/46e747d2-2f94-41fc-a904-0bccd793104b)
## Accept criterias

- [x] AC 1 Make a menu option to create a charge, 

- [x] AC 2 the menu option is feature flagged away from B-environment

- [x] AC 3 Via a modal, display a window for creating a charge. 

- [x] AC 4 Via a drop down, enable the user to choose whether to create a fee, subscription, tariff. The list of fields are updated, depending on the chosen type. 

- [x] AC 5 Have a create button

- [ ] AC 6 Input options are filthered, to allow only valid charges

**Comment by IreneDataHub** [comment]
24.11.2022
Test Environment T-001
 AC 1 Make a menu option to create a charge,
OK danish and english
![image.png](https://images.zenhubusercontent.com/612f6568004bdd03eab7ca46/2fb36b7b-cada-43af-aab8-d4ba7dee8f78)

 AC 2 the menu option is feature flagged away from B-environment
OK

 AC 3 Via a modal, display a window for creating a charge.
OK, but...
- I don't expect transparent invoicing is marked default - please uncheck for subcription and tariff
- "Skæringsdato" please change it to "gyldig fra" - Is it possible to make a default date (today + 31 days)?
- It is possible to create a pris info more than 3 years out in the future - I expect a reject after 3 years from today to create start date and I also get in for create B2B

 AC 4 Via a drop down, enable the user to choose whether to create a fee, subscription, tariff. The list of fields are updated, depending on the chosen type.
Ok - works great and great with default tranparent invoicing 

 AC 5 Have a create button
When using creat button - there are a "S" to much in succes

![image.png](https://images.zenhubusercontent.com/612f6568004bdd03eab7ca46/7843efd2-fa52-474b-b255-c14716994683)

 AC 6 Input options are filthered, to allow only valid charges
OK - but please be aware for 3 yest out in the future

Is a bug or is it a new storie?
Message ID gehUI8890dd80b28d4a19b8d27059418a888 - it isn't possible to click into the message ID or find in request and response messages

**Comment by ShaBloze** [comment]
> Is a bug or is it a new storie?
Message ID gehUI8890dd80b28d4a19b8d27059418a888 - it isn't possible to click into the message ID or find in request and response messages

This will be a new story.
We cannot search for the message in message archive, because the message we create does not go through ChargeIngestion.

**Comment by IreneDataHub** [comment]
5.12.2022
Environment t-001

Skæringsdato change to Gyldig fra/ valid from= OK
![image.png](https://images.zenhubusercontent.com/612f6568004bdd03eab7ca46/6266ce26-a1c1-4f3b-aaba-86b9192e1720)

Date is set up fro 31 days e.g 5.12.2022 - > 5.1.2023 = 31 days = OK

Box is correct success change to succes
![image.png](https://images.zenhubusercontent.com/612f6568004bdd03eab7ca46/619c77b1-41b6-469f-97fc-15f6cd2ceb88)

Transparent invoicing  isn't defaulet make = OK
![image.png](https://images.zenhubusercontent.com/612f6568004bdd03eab7ca46/0bf1ba16-dfdc-48cc-ad20-8f011362b8cd)

Missing full validation - set the acc at storie 1771
3 years also
