### ISSUE TITLE
GUI: Error message displayed when retrieving price series that crossed a switch in daylight savings time

### ISSUE THREAD

**Issue by PerTHenriksen** [Energinet-DataHub/geh-charges#1851]
In T-environment. 
We get an unexpected error when searching for prices on charge information TarID060

In T-001: 
A price series was submitted through B2B for Charge ID **TarId060** that covered the 30th October 2022. Due to the switch to daylight savings time, the price series contained 25 positions/prices. 

When you search for this price series in the frontend, below message is shown: 

Application insights [shows](https://portal.azure.com/#view/AppInsightsExtension/DetailsV2Blade/ComponentId~/%7B%22SubscriptionId%22%3A%227b7ffd68-d27e-4c75-936a-2653ecc36450%22%2C%22ResourceGroup%22%3A%22rg-DataHub-SharedResouces-T-001%22%2C%22Name%22%3A%22appi-shared-sharedres-t-001%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%252Fsubscriptions%252F7b7ffd68-d27e-4c75-936a-2653ecc36450%252FresourceGroups%252Frg-DataHub-SharedResouces-T-001%252Fproviders%252FMicrosoft.Insights%252Fcomponents%252Fappi-shared-sharedres-t-001%22%2C%22ResourceType%22%3A%22microsoft.insights%252Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel~/%7B%22eventId%22%3A%2239e20c74-5c38-11ed-94ee-6045bd950a2c%22%2C%22timestamp%22%3A%222022-11-04T11%3A59%3A42.710Z%22%2C%22cacheId%22%3A%22945071e9-894d-4f8e-9d90-9d1cf24103f0%22%2C%22eventTable%22%3A%22exceptions%22%2C%22timeContext%22%3A%7B%22durationMs%22%3A21600000%2C%22endTime%22%3A%222022-11-04T12%3A27%3A14.502Z%22%7D%7D) that backend throws an exception:
Upon calling `/v1/ChargePrices/Search` this exception is thrown: `NodaTime.AmbiguousTimeException`

`Specified argument was out of the range of valid values. (Parameter 'Local time 10/30/2022 2:00:00 AM is ambiguous in time zone Europe/Copenhagen')`

Application insights also show another exception type: `RangeError` with message `RangeError: Invalid time value`

**Acceptance criteria:**
- [ ] 1 - It is possible to search and view price series that crosses switch in daylight savings time.
<br>

- [ ] 2 - 23 prices displayed the day we switch to normal time (in March) and charge resolution = hourly AND the hour 02-03 is not shown.
<br>

- [ ] 3 - 25 prices displayed the day we switch to DST (in October) and charge resolution = hourly AND the hour 02-03 is shown twice (the price might differ)

**Comment by Mech0z** [comment]
Error provoked in https://github.com/Energinet-DataHub/geh-charges/commit/d6fdce366afce8b32ab1c7093649dcc361bf2ca2 
![image](https://user-images.githubusercontent.com/2316684/199991483-2b39d062-42b5-46e4-b8cb-0e0f0b066051.png)

**Comment by prtandrup** [comment]
After discussing the test results with our SME, the following must be fixed:

When switching to normal time in March, then the time intervals shown in the search results must be:
00-01
01-02
02-03  Either shown with no value or simply a dash / or interval not shown at all
03-04

When switching to DST in October, then the time intervals shown in the search results must be:
00-01
01-02
02-03
02-03
03-04

**Comment by PerTHenriksen** [comment]
AC1: ![image.png](https://images.zenhubusercontent.com/60bdf7bbfa2182da7fd5cc6d/841f0743-b617-4af4-96ea-6a41196f137e)

AC2: 
![image.png](https://images.zenhubusercontent.com/60bdf7bbfa2182da7fd5cc6d/dddbad16-25ed-425d-bbea-2cfec224ddbd)
