### ISSUE TITLE
Charges: Replace `Retired` and `RetiredDateTime` with `RetiredByChargeOperation`

### ISSUE THREAD

**Issue by prtandrup** [Energinet-DataHub/geh-charges#303]
**Description:**
With this story we want to implement the data model improvement, suggested by @BjarkeMeier.

In the existing [Charges data model](https://github.com/Energinet-DataHub/geh-charges/blob/main/docs/data-models/ChargesDataModel.png), `Retired` and `RetiredDateTime` are used in both the `ChargePrice` and `ChargePeriodDetails` tables to indicate that a record is no longer current/valid. A record could be retired due to a price update or a charge period change. 

By introducing `RetiredByChargeOperation` in both tables, we no longer need `Retired` and `RetiredDateTime` as we simply point to the ChargeOperation record that retired them. Hence, when `RetiredByChargeOperation` is filled , the record is considered retired.

**Acceptance Criteria:**

1. `RetiredByChargeOperation` has replaced `Retired` and `RetiredDateTime` in tables; `ChargePrice` and `ChargePeriodDetails` in in the database
2. Code that handles persistence has been refactored to align with AC#1
3. Existing [charges data model diagram](https://github.com/Energinet-DataHub/geh-charges/tree/main/docs/data-models) has been updated and uploaded to the Charges repo.

**Comment by lasrinnil** [comment]
What is `RetiredByChargeOperation` ? I am having trouble figuring it out from the description.

**Comment by prtandrup** [comment]
> What is `RetiredByChargeOperation` ? I am having trouble figuring it out from the description.

I've tried to elaborate on this. Hope it helps.
