### ISSUE TITLE
Extend existing integration tests with a check that charge prices were added to the database

### ISSUE THREAD

**Issue by prtandrup** [Energinet-DataHub/geh-charges#323]
Description:
To be sure that both charge master data and prices are stored, the existing integration tests must be extended with an assert that verifies that charge prices were stored.

Acceptance criteria:
AC#1: Integration tests that integrate with Charges database are extended with an assert that verifies that Charge prices were stored
AC#2: Repository test is extended to assert charge prices were stored

**Comment by HenrikSommer** [comment]
AC#2 is added following comments to pull request

**Comment by lasrinnil** [comment]
###Test

I have verified that upon creation and retrieval of a charge, that points are present:
![image.png](https://images.zenhubusercontent.com/60bdfcb3effb2082025638c1/04be3ea5-6c3a-4c35-9964-4abb269482a1)

I have verified that the integration test which is run upon deploying the charge receiver now checks for points:
![image.png](https://images.zenhubusercontent.com/60bdfcb3effb2082025638c1/48de5c0a-ff03-44c6-a07b-5c0e2488f684)
