### ISSUE TITLE
Charge links: (BRS-004) Consume "Metering Point created" event and store the Metering Point

### ISSUE THREAD

**Issue by prtandrup** [Energinet-DataHub/geh-charges#331]
**Description:** 
Given a **Metering Point Created Event** this message is persisted.
Given an **Internal Metering Point Created,** this message is published as a **Metering Point Created Event**

**Acceptance criteria:** 

- Metering Points Created Events (BRS-037) are mapped and stored
- Internal Metering Point Created messages (BRS-004) are published to the EventHub in CIM the same way as external messages (BRS-037) are once they have been mapped

**Tech notes:** 
- Internal events are received in Protobuf
- The internal message receiver should be placed in Charges domain as a separate EventHub triggered function
- Find out how to test this if a service bus in another domain is unavailable

**Comment by bemwen** [comment]
Replaced by:

* 360
* 361
* 363
* 364
