### ISSUE TITLE
Charge links: (BRS-004) CreateChargeLinkCommand function

### ISSUE THREAD

**Issue by prtandrup** [Energinet-DataHub/geh-charges#332]
**Synopsis**
When a new metering point is created, we will receive a command to add "default" charge links to the metering point.

This story will create a function that listens to a service bus topic and receives the command.

**Scope**
* The actual protobuf contract is unknown for now, we will use a simple placeholder containing a metering point ID, metering point type and a date
* We will be using a topic in our own domain as to not polute shared resources until the actual contract has been decided

**Accept criteria**
* A new function has been added, capable of receiving our placeholder command
* When the command is received, the metering point id, metering point type and the date is written to the log in application insights

![image.png](https://images.zenhubusercontent.com/60bdd871726f411a853d94a9/de63054a-9a8f-4b07-a365-85c6fe5a47a8)

**Comment by bemwen** [comment]
The protobuf contract needed for testing can be found here: 
https://github.com/Energinet-DataHub/geh-charges/blob/main/source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Integration/MeteringPointDomain/CreateLinkCommand.proto

The tester will need to use the protobuf util in the hackaton repo and add/replace the contract in this with the above. Lastly you need to modify the SendTestHelper GenerateMessage method as follows:

        private static MyContractMessage GenerateMessage()
        {
            var message = new MyContractMessage
            {
                MeteringPointId = "MeteringPointID123",
                MeteringPointType = MeteringPointTypeContract.MptConsumption,
                StartDateTime = Timestamp.FromDateTime(DateTime.UtcNow),
            };

            return message;
        }

**Comment by prtandrup** [comment]
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/52804790-20be-46fe-b1d6-4f25066f9f7b)
