### ISSUE TITLE
Preparation work for making data contracts between Charges and Aggregations domains (Charge + Charge links)

### ISSUE THREAD

**Issue by prtandrup** [Energinet-DataHub/geh-charges#336]
**Description:**
First step towards having a Charge and Charge Links data contracts to be used between the Charges and Aggregations domains.

**Precondition:** 
- A list containing data requirements received from code owners of the Aggregations domain; what is expected to be published by the Charges domain.

**Acceptance criteria:** 
AC#1 Based on the list, a draft text document has been created containing the following for both Charges and Charge Links: 
- The properties, their data types, possible null values, 
~~- And when we expect to throw event(s) conforming to the data contract~~
AC#2 Draft document has been shared with the Aggregations code owners before the 'Data contract session'.
AC#3 Draft document is attached to this story in GitHub.

**Comment by prtandrup** [comment]
**AC#1 + AC#3:** draft documented can be found below. The png file has the drawio file embedded within:
![20210621-Charges-Aggregation domain data contracts.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/ecf27990-561e-4502-b514-c93494a91877)

AC#2: Draft document was shared with the Aggregations code owners before the meeting.

The part "when the event" is thrown/published, has been moved to another story (#352)

**Comment by bemwen** [comment]
**Test result:**
AC1 - PASSED
AC2 - PASSED
AC3 - PASSED

**AC1:**
The draft document has been created as required.

**AC2:** 
The document was shared with the aggregation domain before the mentioned meeting.

**AC3:**
The draft document is attached as a comment to this story.

**Comment by BjarkeMeier** [comment]
A few thoughts:
- Diagram notes are not in english
- I believe the diagram needs some explanation if it supposed to be generally understandable (open-source...)
