### ISSUE TITLE
Charge and Charge Links data contract session with Aggregations domain code-owners

### ISSUE THREAD

**Issue by prtandrup** [Energinet-DataHub/geh-charges#337]
**Description:** 
Code-owners of Charges and Aggregations domains align on a data contract content for charges and charge links.

**Precondition:**
- Story #336 is a predecessor.

**Acceptance criteria**
- Meeting done
- Further data contract development stories have been created and the responsibility of completing those are clear.

**Comment by prtandrup** [comment]
Meeting held today, 18-06-2021
New story added to our backlog #336

**Comment by bemwen** [comment]
**Test result:**
AC1 - PASSED
AC2 - PASSED

**AC1:**
Meeting held as per previous comment.

**AC2:**
Story has been created and responsibility of this story is mentioned.
