### ISSUE TITLE
Charge Links: (BRS-037) Receive sync CIM and returns a ChargeLink Command to sender

### ISSUE THREAD

**Issue by Mech0z** [Energinet-DataHub/geh-charges#357]
**Synopsis**
The Charge Link received CIM XML message is mapped and returned to sender ~~to the internal protobuf contract type and published~~

**ACs**
- CIM/XML can be mapped to a ChargeLink Command object
- The mapped object is returned to sender
~~- The LinkCommand object is publish on a service bus using protobuf~~

Example of mapping (Do note that the old implementation based on EBIX have a header section not present in CIM)
https://github.com/Energinet-DataHub/ARCHIVED-green-energy-hub/blob/main/samples/energinet/soap-to-json-adapter/source/Energinet.DataHub.SoapAdapter.Application/Converters/TimeSeriesConverter.cs

https://github.com/Energinet-DataHub/ARCHIVED-green-energy-hub/blob/main/samples/energinet/soap-to-json-adapter/source/Energinet.DataHub.SoapAdapter.Application/Converters/ChangeSupplierConverter.cs

![image.png](https://images.zenhubusercontent.com/60bdbd325b600c62f9576fbb/259beccb-fa2f-434c-a883-8b76076661d2)

**Comment by prtandrup** [comment]
**Tested OK in T env.**
Acceptance criteria met:
Charge link CIM XML request submitted -> response returned ChargeLinkCommand object in JSON:
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/e21031ff-42cf-4f68-bfc8-0f88964f5e69)

Also tested with unexpected content in cim xml request -> still returning a ChargeLinkCommand object:
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/802a3dba-f98f-49ad-aabb-8384ddd26adb)
