### ISSUE TITLE
Ensure sufficient metering point data is provided by MeteringPointCreatedEvent to create a charge link

### ISSUE THREAD

**Issue by Mech0z** [Energinet-DataHub/geh-charges#360]
**Synopsis:**

With this task we ensure that enough metering point data is provided with the MeteringPointCreatedEvent to fulfill the Charges domain's needs when establishing a charge link. 
With this task we also expect to run through the defined validation rules for the existing Danish DataHub2 to ensure no other unfulfilled master data needs are hidden there.

**Sources:**
Metering Point Created Event
- proto file: [here](https://github.com/Energinet-DataHub/geh-metering-point/blob/main/source/Energinet.DataHub.MeteringPoints.Infrastructure/Integration/Contracts/IntegrationEventContract.proto)
- Documented [here]( 
https://github.com/Energinet-DataHub/geh-metering-point/blob/main/docs/contracts.md#meteringpointcreatedeventmessage)
- Existing charge links val rules for DH2 is an internal document, hence no link.  Team Volt or specifically @prtandrup has it. 
- CIM XML for charge link request is provided below acceptance criteria.

** Notes: **
It is a fact that we need data from at least one more domain in order to create and distribute the charge links created upon a MeteringPointCreatedEvent, e.g. the grid area owner is needed (this is a Grid Access Provider). This will not be supplied by the Metering Point domain.

**Acceptance criteria**

1. Verify that the MeteringPointCreatedEvent (proto file, see sources) contains the following information: 
- Metering Point Id
- Type of Metering Point
- Grid area
- Effective Date (also known as Metering Point creation date)
- Connection State
- Settlement method (nice to have)

2. Existing validation rules for creating charge links in DataHub2 has been analyzed and if determined that additional metering point data is needed, the Metering Point code-owners have been informed.

**CIM XML Charge link requests (aka RequestChangeBillingMasterData):**

```
<?xml version="1.0" encoding="utf-8"?>
<RequestChangeBillingMasterData_MarketDocument xmlns="urn:ebix:org:RequestChangeBillingMasterData:1:0">
  <mRID>mRID1</mRID>
  <type>A01</type>
  <process.processType>A01</process.processType>
  <businessSector.type>E13</businessSector.type>
  <sender_MarketParticipant.mRID codingScheme="A01">sender_MarketPa1</sender_MarketParticipant.mRID>
  <sender_MarketParticipant.marketRole.type>A01</sender_MarketParticipant.marketRole.type>
  <receiver_MarketParticipant.mRID codingScheme="A01">receiver_Market1</receiver_MarketParticipant.mRID>
  <receiver_MarketParticipant.marketRole.type>A01</receiver_MarketParticipant.marketRole.type>
  <createdDateTime>1900-01-01T01:01:01+01:00</createdDateTime>
  <MktActivityRecord>
    <mRID>mRID1</mRID>
    <businessProcessReference_MktActivityRecord.mRID>businessProcessReference_MktActivityRecord.mRID1</businessProcessReference_MktActivityRecord.mRID>
    <marketEvaluationPoint.mRID codingScheme="A01">marketEvaluationPoint.mRID1</marketEvaluationPoint.mRID>
    <start_DateAndOrTime.dateTime>1900-01-01T01:01:01+01:00</start_DateAndOrTime.dateTime>
    <end_DateAndOrTime.dateTime>1900-01-01T01:01:01+01:00</end_DateAndOrTime.dateTime>
    <chargeGroup.chargeType.mRID>chargeGroup.chargeType.mRID1</chargeGroup.chargeType.mRID>
    <chargeGroup.chargeType.factor>chargeGroup.chargeType.factor1</chargeGroup.chargeType.factor>
    <chargeGroup.chargeType.chargeTypeOwner_MarketParticipant.mRID codingScheme="A01">chargeGroup.cha1</chargeGroup.chargeType.chargeTypeOwner_MarketParticipant.mRID>
    <chargeGroup.chargeType.type>D01</chargeGroup.chargeType.type>
  </MktActivityRecord>
</RequestChangeBillingMasterData_MarketDocument>
```

**Comment by prtandrup** [comment]
**AC1:** The MeteringPointCreatedEvent contains the expected data, see dump below: 
**AC2:** I have been through the defined validation rules for charge links for DataHub2. Conclusion: No other metering point data are required. For Reviewer: reach out to me, than I will show you what I did in the _internal_ validation rule document.

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/2ad05bd0-128f-4427-bbbc-eb2618b6c0a3)
Note: The MeteringPointCreatedEvent includes more data than is needed for charge links. This is expected as the event is used by other domains as well.
