### ISSUE TITLE
Metering Point: (BRS-004) Design Datamodel and DbUp

### ISSUE THREAD

**Issue by Mech0z** [Energinet-DataHub/geh-charges#361]
**Synopsis**
Design a database model for storing Metering Points in the Charge domain

**Scope**
Note that only the MP datamodel is needed at this pint. The links are added later.

**ACs**
- Designed model contains metering point fields needed in the Charge domain
- Write DbUp SQL code for deploying the database model

**Comment by Mech0z** [comment]
**Synopsis**
Design a database model for storing Metering Points in the Charge domain

**Scope**
Note that only the MP datamodel is needed at this pint. The links are added later.

**ACs**
- Designed model contains metering point fields needed in the Charge domain
- Write DbUp SQL code for deploying the database model

**Comment by prtandrup** [comment]
AC1: Data model for containing metering points, [here](https://github.com/Energinet-DataHub/geh-charges/blob/main/docs/data-models/ChargeLinkDataModel.png)
AC2: Metering Point SQL script, [here](https://github.com/Energinet-DataHub/geh-charges/blob/main/source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ApplyDBMigrationsApp/Scripts/Model/202107011226%20New%20Metering%20Point.sql)
