### ISSUE TITLE
Charge Links: (BRS-037) Link Receiver Returning 200 OK

### ISSUE THREAD

**Issue by Mech0z** [Energinet-DataHub/geh-charges#362]
Synopsis
A HTTP trigger that receives an XML payload and returns 200 OK

Scope
At this point we do not need to understand the CIM/XML or process its content

ACs

- Valid Charge Link Created Postman script with CIM/XML links added
- Using postman a 200 OK is received

Tech Note
@prtandrup have knowledge on how to get a valid CIM XML

![image.png](https://images.zenhubusercontent.com/60bdbd325b600c62f9576fbb/b7e9a9de-b125-4fe0-838b-2d32d2db95dd)

**Comment by prtandrup** [comment]
**Tested OK against T environment:**

**AC1**: Valid script available in Postman (Charges workspace)
**AC2**: ChargelinkHttpTrigger (Charge link receiver) returns '200 OK'

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/f6371c39-0a7e-48ec-8baf-f6d854d0c65b)
