### ISSUE TITLE
Metering Point: (BRS-004) MP Created Receiver

### ISSUE THREAD

**Issue by Mech0z** [Energinet-DataHub/geh-charges#363]
Create a EventHub trigger capable of receiving a BRS-004 using Protobuf

**ACs**

Given a MeteringPointCreatedEvent is published in U environment by Charges domain
When consuming this event
Then we log the event content (where?)

Given a MeteringPointCreatedEvent is published in T environment Metering Point domain
When consuming this event
Then we log the event content (where?)

![image.png](https://images.zenhubusercontent.com/60bdd871726f411a853d94a9/139230bc-78d4-45d5-a76e-31e8a4c11cdf)

**Comment by BjarkeMeier** [comment]
@Mech0z, should dashboard health monitoring of the new function have an AC?

**Comment by Mech0z** [comment]
https://github.com/Energinet-DataHub/geh-charges/tree/msp/feat_358_ChargeLinkCommandReceiver
