### ISSUE TITLE
Metering Point: (BRS-004) Store MP

### ISSUE THREAD

**Issue by Mech0z** [Energinet-DataHub/geh-charges#364]
**Synapsis**
Store the received Metering points

**ACs**

- Received Metering Points are stored in the database

![image.png](https://images.zenhubusercontent.com/60bdd871726f411a853d94a9/0dad111d-ab33-47bc-9c69-465dd71512ab)

**Comment by PerTHenriksen** [comment]
drawing is outdated, but task is unchanged

**Comment by lasrinnil** [comment]
### Test

I have sent a message through the shared servicebus which now creates a new MeteringPoint in the Charge database.
![image.png](https://images.zenhubusercontent.com/60bdfcb3effb2082025638c1/8cb9c8a4-8bc9-45c9-a8a9-962adcdf126e)
