### ISSUE TITLE
Establish a way to inspect protobuf messages in EventHub/ServiceBus

### ISSUE THREAD

**Issue by Mech0z** [Energinet-DataHub/geh-charges#365]
**Synopsis**
Either find a tool or develop a way to inspect Protobuf messages for debugging and testing

**Acceptance criteria**

* The unserialized content of messages placed on a ServiceBus using a protobuf contract can be inspected (preferably without extra work for each contract)
* The unserialized content of messages placde on an EventHub using a protobuf contract can be inspected (preferably without extra work for each contract)

**Comment by HenrikSommer** [comment]
We could have a look at https://github.com/protobuf-net/protobuf-net for a start
