### ISSUE TITLE
Charges: Use protobuf for events sent internally

### ISSUE THREAD

**Issue by bemwen** [Energinet-DataHub/geh-charges#373]
**Synopsis**

As per the ADR decision, we need to move our communication from JSON-based to protobuf-based internally in the Charge domain.

**Out of scope**
Messages sent to our own internal post office which we will need to replace is out of scope of this task.

**Acceptance criteria**

1. ChargeCommands sent between MessageReceiver and ChargeCommandReceiver must use Protobuf
2. ChargeCommandAccepted events sent between the ChargeCommandReceiver and the ChargeConfirmationSender must use Protobuf
3. ChargeCommandRejected events sent between the ChargeCommandReceiver and the ChargeRejectionSender must use protobuf

**Testing**

1. Send a valid Charge HTTP Trigger "Create Tariff message" using postman and validate that a Protobuf message is received in topic sbs-post-office
2. Send a invalid by changing StartDateTime to a date less than 30 days from now and see that a Protobuf message is received containing "StartDateValidation" meaning it failed validation in topic sbs-post-office

**Comment by prtandrup** [comment]
Tested :white_check_mark: in T environment

````
Test procedure
- Disable the following functions: ChargeCommandReceiver and ChargeConfirmationSender
- Submit valid charge message via Postman to the MessageReceiver
- Inspect (peek) the service bus subscription for command-received (and verify content is protobuf, or at least not plain JSON)
- Enable the ChargeCommandReceiver
- Inspect (peek) the service bus subscription for command-accepted (protobuf, not plain JSON)
- Enable the ChargeConfirmationSender
- Inspect (peek) the service bus subscription for post-office (protobuf, not plain JSON)
- Using the hackathon project AzureProtobufHelper to read from the post office subscription, and verify the readable content in the console application

Test procedure can be repeated for the invalid scenario replacing ChargeConfirmationSender with ChargeRejectionSender and submitting an invalid charge message. 
````
AzureProtobufHelper project [link](https://github.com/Energinet-DataHub/hackathon-projects/tree/master/AzureProtobufHelper)

**Test: valid charge message**:
Submitted valid charge message, got correlation id = e6ea2c4a-0c56-4189-aaef-c7082ce4f6f5
Verified message in `command-received` is proto, not plain JSON: 
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/5c00a156-3be1-473e-a68b-2ccffcff5968)

After enabling ChargeCommandReceiver again, I verified that the message in `command-accepted` is also proto:
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/ba50b7dc-f2d7-4f8d-9c65-c6325026f2de)

After enabling ChargeConfirmationSender again, I verified that the message in `post-office` is also proto:
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/afb3dbc0-c8f3-41c4-ba64-5eaa69ef812e)

Deserialized message from post-office subscription with tool:
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/98d640b0-9ab2-49f7-85bb-e61bd3ea272f)

Test: :white_check_mark:

**Test invalid charge message (violating chargeID length validation)**
Disabled ChargeRejectionSender.
Submitted invalid charge message, got correlation id = 35160ce4-3ba5-4edc-855d-3e9ad45bc638

Verified message in `command-rejected` is proto:
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/640e3a47-0676-40a9-94c6-c5eae11fdd3d)

After enabling ChargeRejectionSender again, I verified that the message in `post-office` is also proto:
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/c361ff3a-ad94-4538-8513-6ff474b2d143)

Deserialized message from post-office subscription with tool:
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/0d830064-4d0e-47e6-920c-9ac59bef1e40)

Test: :white_check_mark:
