### ISSUE TITLE
Charges - BRS 031/032/033

### ISSUE THREAD

**Issue by PerLysemose** [Energinet-DataHub/geh-charges#375]

**Comment by MadsBloendAndersen** [comment]
Hej @PerLysemose, er der forskel på dette issue og denne?

https://app.zenhub.com/workspaces/feature-board-60e2eb437d96850014aa15ab/issues/energinet-datahub/geh-charges/258

**Comment by PerLysemose** [comment]
@MadsBloendAndersen tror Per og jeg er gået fejl af hinanden. Det er kun #375, der skal beholdes, så den skal på feature board. Jeg får lige ryddet op på #258 og så lukker jeg den efterfølgende.
