### ISSUE TITLE
Miscellaneous

### ISSUE THREAD

**Issue by PerLysemose** [Energinet-DataHub/geh-charges#376]

**Comment by MadsBloendAndersen** [comment]
Hej @PerLysemose, er dette en feature? eller hvor hører denne hjemme?

**Comment by PerLysemose** [comment]
@MadsBloendAndersen, det er ikke en feature, der skal på feature board. Vi har "misbrugt" Zenhub en smule til at skabe en "snyde-feature", der indeholder alle de issues, der ikke hører hjemme under en prioriteret feature. Fx Set-up PC, Cross team collaboration etc. Blot for at kunne følge med i, hvor mange SP vi faktisk benytter på aktiviteter, der ikke hører hjemme nogen steder. Så..., den skal ikke have et label, der gør, at den kommer med på feature board.

**Comment by MadsBloendAndersen** [comment]
@PerLysemose Check :) Vi tagger alle features med "epic" og "feature", så når vi på feature boarded får vist de tags som default, så vil denne automatisk også forsvinde. Det er super fint.
