### ISSUE TITLE
Shared resources: Metering Point Created Event available to Charge domain

### ISSUE THREAD

**Issue by bemwen** [Energinet-DataHub/geh-charges#436]
**Synopsis**
In charges, we want to use a servicebus in shared resources for integration events with other domains.

The shared resources pipeline is currently broken and needs to be fixed in order to connect the charges domain to the shared resources correctly.

**Acceptance criteria**
AC1: Metering point created topic and subscription needed by Volt has been created and deployes to the shared resource T environment.
AC2: Charges T environment can be deployed using the metering point created subscription made available in the shared resource domain.

**Comment by lasrinnil** [comment]
AC1: Metering point created topic and subscription needed by Volt has been created and deployes to the shared resource T environment.

I have verified that the metering-point-created is deployable to the T envoriment.

![image.png](https://images.zenhubusercontent.com/60bdfcb3effb2082025638c1/56586535-5547-4b06-a90d-957fc29cd660)

_AC2: Charges T environment can be deployed using the metering point created subscription made available in the shared resource domain._

I have verifed the subscription is being created from the shared-resources domain. 

![image.png](https://images.zenhubusercontent.com/60bdfcb3effb2082025638c1/f7314e6e-78b9-4c98-9b11-1bb77146d2ea)
