### ISSUE TITLE
Charge Link: The ChargeType value in `link-command-received` event is not the same as submitted to ChargeLinkHttpTrigger

### ISSUE THREAD

**Issue by prtandrup** [Energinet-DataHub/geh-charges#440]
### Current Behavior
1) Submit a `Charge Link request` from Postman with ChargeType set to D03, which is a tariff
2) Using the [AzureProtobufHelper](https://github.com/Energinet-DataHub/hackathon-projects/tree/master/AzureProtobufHelper) and this [protofile](https://app.zenhub.com/files/345465244/30c815a8-2354-49fb-914f-a37ff6aa5f8d/download), read the published `link-command-received` event from the ServiceBus. 
3) When comparing the event value for ChargeType to the .proto [file](https://github.com/Energinet-DataHub/geh-charges/blob/main/source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Internal/ChargeLink.proto), you'll see that it has become a Fee:

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/7b419919-b38c-4f40-aa7d-bdf43a7fe9ba)
.proto file:
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/a5a87833-4640-4e01-81c6-afe1aef58439)

### Expected behavior
Given I submit a `tariff link` to the ChargeLinkHttpTrigger
When I inspect the `link-command-received` event placed on the service bus
Then the Charge type equals `tariff`

Same for `fee link`.
Same for `subscription link` 

### How to reproduce
See current behavior.

### Environment
Charges T env.

### Possible Solution
Please have a look at `ChargeType.cs` 
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/8e3abcb9-1f92-44ca-af85-a0d0d558f468)
And the .proto file
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/a5a87833-4640-4e01-81c6-afe1aef58439)

Either align the two files - or handle the differences through mapping.

**Comment by lasrinnil** [comment]
Solved

![image.png](https://images.zenhubusercontent.com/60bdfcb3effb2082025638c1/3263f9ba-7244-4bfc-b16d-d1cd8510eecb)

**Comment by bemwen** [comment]
Test passed

Test:
Tested on T-environment.

When a Tariff is sent to the service bus, it ChargeType is now correctly 3 as expected.

![image.png](https://images.zenhubusercontent.com/60bdd871726f411a853d94a9/c1003230-a6dd-4faf-a66e-91c77f8f1509)

When a fee is sent to the service bus, the ChargeType is now correctly 2 as expected.

![image.png](https://images.zenhubusercontent.com/60bdd871726f411a853d94a9/42d407b9-d0dc-4d62-97a5-c35252437cc2)

When a subscription is sent to the service bus, the ChargeType is now correctly 1 as expected.

![image.png](https://images.zenhubusercontent.com/60bdd871726f411a853d94a9/5e2ba009-75f5-437b-b7ed-5fd963ddf84d)
