### ISSUE TITLE
Charges: Analysis of changed ebiX/CIM strategy

### ISSUE THREAD

**Issue by bemwen** [Energinet-DataHub/geh-charges#466]
**Synopsis**
A change in the usage of the CIM format for charges means that we need to revisit how we are going to handle and store charges.

**Acceptance criteria**
- [x] New drawing with [updated rules for persisting master data](https://github.com/Energinet-DataHub/geh-charges/blob/main/docs/images/PersistingChargesRuleSet_ProcessFlow.png) has been made
- [x] [Data model](https://github.com/Energinet-DataHub/geh-charges/tree/main/docs/data-models) changes has been identified and a new story to implement this has been created
- [x] If needed, the [integration events](https://github.com/Energinet-DataHub/geh-charges/blob/main/docs/contracts.md) for Charges (and prices) are updated/aligned with the changes
- [x] If needed, new stories has been created with any further analysis
- [x] Backlog has been revisited and stories updated where applicable

**Known issues that need an update:**
#288

**Comment by bemwen** [comment]
**Synopsis**
A change in the usage of the CIM format for charges means that we need to revisit how we are going to handle and store charges.

**Acceptance criteria**
* New drawing with update rules for master data has been made
* New stories has been created with any further analysis if needed
* Backlog has been revisited and stories updated where applicable, or this AC has been moved the a new analysis story if the analysis was not completed.

**Comment by prtandrup** [comment]
**AC status:**
- Rule set updated, [PR](https://github.com/Energinet-DataHub/geh-charges/pull/481) is up for review.
- Data model analysis completed, no changes required. 
One observation point though; it is assumed that charge properties like charge name, description and VAT classification will not be part of an incoming STOP charge message, hence we will be re-using/transferring the values of the existing overlapping period. 
- Integration analysis completed: No changes required. 
- No new stories created for further analysis.
- IN PROGRESS: Backlog stories have been updated [288]
