### ISSUE TITLE
Coordinate Terraform Modules with MightyDucks

### ISSUE THREAD

**Issue by bemwen** [Energinet-DataHub/geh-charges#471]
**Synopsis**
We currently have three Terraform modules in Charges and TimeSeries which adds availability tests, availability alerts and monitor alert groups with email notification.

We need to coordinate with MightyDucks and our architect about whether and how to move these modules to a general repo like geh-terraform-modules so that all teams can benefit from the work.

The modules support specific use scenarios, but are general in nature, and could potentially be reused in other domains that wish to add availibility tests and monitoring of these.

**Accept criteria**
* AC1: Agree with MightyDucks on where ping-webtest should be moved and move it.
* AC2: Agree with MightyDucks on where monitor-action-group-email should be moved and move it.
* AC3: Agree with MightyDucks on where availability-alert should be moved and move it.
* AC4: Update charges to use the new location
* AC5: Perform the needed updates to timeseries to enable availability test monitoring of the timeseries domain

**Comment by BjarkeMeier** [comment]
I think we should consider including the actual work of migrating the modules from geh-charges to geh-terraform-modules, and also the software architect regarding general monitoring concepts.

**Comment by bemwen** [comment]
Put on the Mighty Duck radar today. Daniel will start a discussion internally in MightyDucks about it

**Comment by PerLysemose** [comment]
@bemwen er denne stadig relevant?
