### ISSUE TITLE
Charge links: (BRS-004) Default link settings

### ISSUE THREAD

**Issue by bemwen** [Energinet-DataHub/geh-charges#475]
**Synopsis**
We need a place to store our settings about which links should be added to new metering points when we receive a create link command.

This story will define and add a settings datamodel and add it to our DB deployment scripts, so that the model is ready for use later.

**Note**
Coordinate with PO about seed data values for both charges and links on fields not mentioned in the table.

**Acceptance criteria**
* A datamodel for storing settings about which links to add when receiving a command has been defined and documented
* It must be possible to define different default links based on the MeteringPointType
* A MeteringPointType must be able to have 0-* default links
* It must be possible to define open-ended and specific periods a default link should be used (to prepare for changes to defaults in the future)
* The datamodel should be added to deployment
* Seed data should be added to deployment corresponding to the below table (metering point types not mentioned have no defaults)

|ChargeId|Name|Consumption Metering Points|Production Metering Points|Electrical Heating Metering Points|
|-----|-----|----|----|----|
|40000|Transmissions nettariff|X|||
|40010|Indfødningstariff||X||
|41000|Systemtariff|X|||
|45012|Balancetarif for produktion||X|| 
|45013|Balancetariff for forbrug|X|||
|EA-001|Elafgift|X||X|
|EA-003|Negativt reduceret elafgift|||X|

![image.png](https://images.zenhubusercontent.com/60bdd871726f411a853d94a9/e3e658a6-6cdb-4d53-b040-addc325320fc)

**Comment by bemwen** [comment]
Added data model to repo, can be found here: https://github.com/Energinet-DataHub/geh-charges/blob/main/docs/data-models/DefaultChargeLinkSettingDataModel.png

Deployed to T as required being moving to test.

**Comment by prtandrup** [comment]
Test result: :white_check_mark:
Env used: T

Data model for charge link settings: 
- [x] defined and [documented](https://github.com/Energinet-DataHub/geh-charges/blob/main/docs/data-models/DefaultChargeLinkSettingDataModel.png) in GitHub
- [x] Default charge links are based upon MeteringPointType, illustrated by the data model.
- [x] A `MeteringPointType` may have 0-many default charge link settings defined. See the actual `DefaultChargeLinkSetting` dump from T below.
- [x] With the implementation of `StartDateTime` and `EndDateTime` it is possible to have open-ended and specific periods, where a charge must be linked to a metering point type by default.
- [x] Model + Seed scripts and they are part of deployment:
- Model [Default Charge Links](https://github.com/Energinet-DataHub/geh-charges/blob/main/source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ApplyDBMigrationsApp/Scripts/Model/202108130551%20Default%20Charge%20Links.sql)
- Seed [Default Charges](https://github.com/Energinet-DataHub/geh-charges/blob/main/source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ApplyDBMigrationsApp/Scripts/Seed/202108130629%20Default%20charges.sql)
- Seed [Default charge links](https://github.com/Energinet-DataHub/geh-charges/blob/main/source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ApplyDBMigrationsApp/Scripts/Seed/202108131029%20Default%20charge%20links.sql)
- Seed [System Operator Market Participant](https://github.com/Energinet-DataHub/geh-charges/blob/main/source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.ApplyDBMigrationsApp/Scripts/Seed/202108130611%20System%20operator%20market%20participant.sql)

<hr>

**DefaultChargeLinkSetting table:**
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/3c132b53-bb80-4b9b-8283-34dd2e3d21d9)

<hr>

**Charges table with charges used by default charge linking:**
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/10d8e736-3b2a-4cdb-8a19-61eac060b8c3)

<hr>

**And the MeteringPointType values, to ensure that the DefaultLinkSettings are indeed valid:**
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/c0581ed3-43fc-4bf1-a7bf-016f2f80843b)
