### ISSUE TITLE
Charge links: (BRS-004) Link commands based on defaults

### ISSUE THREAD

**Issue by bemwen** [Energinet-DataHub/geh-charges#476]
**Synopsis**
When receiving a request for adding default charge links to a metering point, we need to use our settings to determine which links to actually add, which period to add them in, and create charge link commands corresponding to these settings.

**Relevance of setting links**
A setting link is considered relevant if
* The metering point type of the setting link matches the metering point type of the metering point to add links to
* The period of the setting link includes the date supplied in the command to add links (start is inclusive, end is exclusive)
* The start date of the setting link is later than the date supplied in the command to add links.

**Acceptance Criteria**
* For each link in the settings that is relevant (as described above), a charge link command received event should be sent to the service bus topic for received link commands
* The start date of the link command must be the latest of either: the supplied start date, or the start date of the link from the settings.
* The end date of the link command must be the end date for the link in the settings

![image.png](https://images.zenhubusercontent.com/60bdd871726f411a853d94a9/db36f7fc-0562-4d82-b363-9e37e97262a5)

**Tech note**
Consider whether it would be smarter to extend our ChargeLinkCommand to support a list of links. This could potentially save us alot of trouble with receipts.

**Comment by lasrinnil** [comment]
### Tasks
[] - Read default links based on metering point type.

**Comment by lasrinnil** [comment]
For testing:

Branch to use with AzureProtobuf project: 
Link-commands-based-on-defaults-476

**Comment by bemwen** [comment]
Test result:
AC - For each link in the settings that is relevant (as described above), a charge link command received event should be sent to the service bus topic for received link commands - PASSED
AC - The start date of the link command must be the latest of either: the supplied start date, or the start date of the link from the settings. - PASSED
AC - The end date of the link command must be the end date for the link in the settings - PASSED

For all the tests, the following default settings where setup in the database

![image.png](https://images.zenhubusercontent.com/60bdd871726f411a853d94a9/da3d3895-60fe-470f-9ce2-4f7f8fb32d35)

**Consumption:**
The following was sent to the T-enviroment function:

![image.png](https://images.zenhubusercontent.com/60bdd871726f411a853d94a9/3f559370-be87-4da3-8c62-a8fcea552c46)

The result was four events with links to add in the received queue

![image.png](https://images.zenhubusercontent.com/60bdd871726f411a853d94a9/e7d53eae-2115-41c6-b2ea-d049df79ef2b)

40000, 41000, 45013 and EA-001 with a start date as shown below

AC1 - PASSED

The start date of all four are the following:

![image.png](https://images.zenhubusercontent.com/60bdd871726f411a853d94a9/55f0f8f9-890a-4bed-8a12-8658e3d7dabb)

AC 2 - PASSED

The end date is appropriatly long into the future as indicated by the null value of the settings.

AC 3 - PASSED

A new creation command is sent using the following information (note the year):

![image.png](https://images.zenhubusercontent.com/60bdd871726f411a853d94a9/512ce586-10aa-40bf-9125-1f6e3d21a065)

Again, the same four links are created.

AC 1 - PASSED

The start date is now the start date from the settings as expected, and not the one from the created command.

![image.png](https://images.zenhubusercontent.com/60bdd871726f411a853d94a9/b6da2304-d234-4d3d-a686-3690c612a78c)

AC 2 - PASSED

And end date is again appropriately long in the future.

AC 3 - PASSED

**Production:**

The following command is sent to the service:

![image.png](https://images.zenhubusercontent.com/60bdd871726f411a853d94a9/f6e3db58-2817-4571-99f6-8f4f09667c5b)

Two links are created as a result, 40010 and 45012.

![image.png](https://images.zenhubusercontent.com/60bdd871726f411a853d94a9/5e574420-0fcd-45c7-9264-095e0b4cfb31)

AC 1 - PASSED

The start date is of both is as shown below

![image.png](https://images.zenhubusercontent.com/60bdd871726f411a853d94a9/926a46f0-0ef0-4596-b33d-710c3fd59333)

AC 2 - PASSED

And again the end date is appropriately long into the future.

AC 3 - PASSED

The following is send to the function:

![image.png](https://images.zenhubusercontent.com/60bdd871726f411a853d94a9/16cdb2f1-33c5-46bb-9199-8221d6a02103)

Again the expected two charges links added as events.

AC 1 - PASSED

The start date is now the one from the settings and not the command as expected:

![image.png](https://images.zenhubusercontent.com/60bdd871726f411a853d94a9/f1f0fcb0-b64a-4679-89be-147bf06ab91c)

AC 2 - PASSED

And again end date is appropriatly long in the future.

AC 3 - PASSED

**Electrical heating: **

The following is sent to the function:

![image.png](https://images.zenhubusercontent.com/60bdd871726f411a853d94a9/ed544148-9f74-47e8-8173-282f4e006577)

Two charge links requests are added, EA-001, EA-003

![image.png](https://images.zenhubusercontent.com/60bdd871726f411a853d94a9/6172e77f-dca2-4427-9317-1eff5aebd7e7)

AC 1 - PASSED

Start time is set as follows: 

![image.png](https://images.zenhubusercontent.com/60bdd871726f411a853d94a9/0e5b1bbb-d1b8-4b82-a677-906ce0c31d08)

AC 2 - PASSED

And end time is again long in the future.

AC 3 - PASSED
