### ISSUE TITLE
Charge links: Expand integration events to handle updates

### ISSUE THREAD

**Issue by bemwen** [Energinet-DataHub/geh-charges#480]
**Synopsis**
We have implemented a flow where a CIM/XML with a charge link is communicated through our domain and ends up as a `ChargeLinkCreated` integration event.

We need to expand this functionality so that it is not always a `ChargeLinkCreated` event that is raised, but a `ChargeLinkUpdated` instead, if it is not the first event about the link.

[ChargeLinkUpdated contract](https://github.com/Energinet-DataHub/geh-charges/blob/main/docs/contracts.md#chargelinkupdated)

**Acceptance criteria**
TO BE FILLED, REMEMBER THIS INCLUDES ANY UPDATE DATABASE WORK...
- [ ] Simple update -> remember to adjust existing link -> one event with two periods
- [ ] Overwrite existing link -> remember to retire -> one int event
- [ ] Stopping existing link -> set end date on existing vs two periods one with start=end? -> one int event
- [ ] [Contract documentation](https://github.com/Energinet-DataHub/geh-charges/blob/main/docs/contracts.md) for charge links has been moved to protobuf contracts and page has been updated with links to the protobuf contracts

![ChargeLinkProcessFlow_story480.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/bf42230a-0ce0-4f63-a1ee-fdc0ddfe496c)

**Comment by PerTHenriksen** [comment]
integration intended as push, not pull, hence closed.
