### ISSUE TITLE
Define data model for Charge Link (and Metering Point)

### ISSUE THREAD

**Issue by prtandrup** [Energinet-DataHub/geh-charges#492]
**Synopsis**
Define the data model needed for storing charge links

**Acceptance criteria:**
1) The [data model](https://github.com/Energinet-DataHub/geh-charges/tree/main/docs/data-models) has been defined and documented in GitHub
2) It has been approved by PO (and preferably a SME)
3) If new stories are needed to implement/refactor this data model output, they have been added.

**Comment by prtandrup** [comment]
Draft PR is up: https://github.com/Energinet-DataHub/geh-charges/pull/506

**Comment by BjarkeMeier** [comment]
@prtandrup, we use the term "data model" for both the .NET/EFCore data model and the storage model. Could we perhaps agree on a naming without this ambiguity?
