### ISSUE TITLE
First step towards tracking Metering Point state over time (by implementing and deploying the updated MeteringPointDataModel)

### ISSUE THREAD

**Issue by prtandrup** [Energinet-DataHub/geh-charges#507]
**Synopsis**
When linking a charge to a Metering Point, the state of the metering point at the time of linking influences the business validation result and thus whether or not the link will be created. An example of this could be a Metering Point with connection state closed down, which would cause a rejection when attempting to link a charge to it. Had the Metering Point instead been connected, the linking would be allowed (assuming all other validations pass). 

As it is possible to link a charge both back and forth in time, the charges domain need to keep track of a metering point state over time. Hence we need to extend our [initial data model](https://github.com/Energinet-DataHub/geh-charges/blob/main/docs/data-models/ChargeLinkDataModel.png) to fit this need. 

With this story we will refactor the current metering point table implementation to match the 3 tables below.
It won't be possible to demonstrate that we ensure metering point state over time, as we need more metering point integration events to prove this.

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/40d4272e-9c39-4575-9838-0983a250912b)
![ChargeLinkProcessFlow_507.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/90b7dc4f-dd9e-41f8-911d-69d121c7dc18)

**Acceptance criteria**
- The Metering Point data model has been implemented and is deployed to U + T environments.
- The existing procedure for storing a "Metering Point Created" integration event must be refactored to also fill tables `MeteringPointDetails` and `MeteringPointOperation`

**Comment by BjarkeMeier** [comment]
@prtandrup, @Mech0z doesn't the current work on #364 use this model? I would assume this story to no longer be relevant.

**Comment by prtandrup** [comment]
> @prtandrup, @Mech0z doesn't the current work on #364 use this model? I would assume this story to no longer be relevant.
> 
> Also, the synopsis and ACs doesn't reflect the title? I think we are missing the business perspective.

@BjarkeMeier, #364 does not use the model depicted above, as it was planned before looking into the charge link data model.
It uses this initial [one](https://github.com/Energinet-DataHub/geh-charges/blob/main/docs/data-models/ChargeLinkDataModel.png). For now we continue implementing 364, and see what the outcome of our "data model team dev session" will be and act on it. 

And I have added some more context to the synopsis and edited the 2nd AC. Hopefully it's better now 😄
