### ISSUE TITLE
EF configure datacontracts through FluentConfiguration

### ISSUE THREAD

**Issue by lasrinnil** [Energinet-DataHub/geh-charges#516]
**Synopsis**
To better align with ART decisions we are going to remove our `Entity `models and configure our database contracts through `FluentConfiguration`.

Edit: Only Metering Point is to be ported as Charge will requires a bit refactoring which will happen at a later point https://github.com/Energinet-DataHub/geh-charges/issues/628

**Tech notes**
It is possible to configure EFCore to handle the Instant datatype see this GitHub repo for further instructions:
https://github.com/StevenRasmussen/EFCore.SqlServer.NodaTime

An example from Team Batman:
https://github.com/Energinet-DataHub/geh-metering-point/blob/main/source/Energinet.DataHub.MeteringPoints.Infrastructure/DataAccess/MeteringPoints/MeteringPointEntityConfiguration.cs

**Acceptance criteria**
~~1) No models are used only to configure DBSet.~~
2) All Unit/integration tests pass.
3) Metering Point is ported

**Comment by BjarkeMeier** [comment]
@lasrinnil, where did the discussion about completely getting rid of the data model end?

**Comment by BjarkeMeier** [comment]
Test of story:
- AC1: I accept that it has been deferred to #628
- AC2: Ensured by PR gate
- AC3: Verified by inspection

Conclusion: Story is tested OK.
