### ISSUE TITLE
Create new context for assert in database tests

### ISSUE THREAD

**Issue by Mech0z** [Energinet-DataHub/geh-charges#555]
To ensure we are not just reading from memory in the old context, its been decided to create a new database context for the assert part of database tests

ACs
1. The context used to arrange and act is not the same as the one used to assert that data is valid

**Comment by HenrikSommer** [comment]
[Pinal Dave - SQL-server login failures](https://logicalread.com/errors-sql-server-login-failures-pd01/#.YTfYdvdxeF4) describes a lot of SQL server login errors.
State 7 is the one in question here: 

> This would appear if _login is disabled_ AND _incorrect password is provided_.

**Comment by BjarkeMeier** [comment]
Test of story:
- All tests using `SquadronContextFactory` have been manually confirmed to use different context for read and write
- I consider the integration tests that uses the `ChargeDatabaseContext` to be out of scope for this story
- All unit tests passes

Conclusion: Story is tested to be correct
