### ISSUE TITLE
Update stylecop to allow IF to not have brackets

### ISSUE THREAD

**Issue by Mech0z** [Energinet-DataHub/geh-charges#556]
To enable simple one liners or 2 liners stylecop rules need to get updated

Currently 
`if (meteringPointCreatedEvent == null)
                throw new ArgumentNullException(nameof(meteringPointCreatedEvent));`

And
`if (meteringPointCreatedEvent == null) throw new ArgumentNullException(nameof(meteringPointCreatedEvent));`

Gives an error

> Error IDE0011	Add braces to 'if' statement.

**ACs**
1. Rider do not show an error when using either an 1 or 2 liner style without bracers
2. Visual Studio do not show an error when using either an 1 or 2 liner style without bracers

**Comment by HenrikSommer** [comment]
.EditorConfig seems to be the place for a more specific, yet IDE-agnostic setting.
