### ISSUE TITLE
Reminder: Update technical documentation for Charges (BRS-031/032/033)

### ISSUE THREAD

**Issue by PerLysemose** [Energinet-DataHub/geh-charges#585]
** Synopsis **
The main objective of this assignment is to make sure existing documentation is updated before we are able to close the feature.

** Acceptance-Criteria ** _Please don't consider this a complete to-do list, but just an inspiration on stuff we need to check is up to date_

~~ - [ ] [Domain flows](https://github.com/Energinet-DataHub/green-energy-hub/blob/main/docs/domainflows.drawio) Make sure the diagrams relevant to BRS-031/032/033 are added to charge repository WIP https://github.com/Energinet-DataHub/geh-charges/pull/722 ~~

- [x] [Architecture diagram](https://github.com/Energinet-DataHub/geh-charges#architecture) Change the format of this to use this style https://github.com/Energinet-DataHub/geh-timeseries/blob/main/ARCHITECTURE.png and include domain integrations => [PR](https://github.com/Energinet-DataHub/geh-charges/pull/736)

- [x] [Process flows](https://github.com/Energinet-DataHub/geh-charges/tree/main/docs/process-flows) Validate these are up to date => [PR](https://github.com/Energinet-DataHub/geh-charges/pull/724)

- [x] Update the contracts.md according to this [dev session topic/task](https://app.zenhub.com/workspaces/team-volt-dev-session-615167844e83ef001107e157/issues/energinet-datahub/geh-timeseries/256) => [PR](https://github.com/Energinet-DataHub/geh-charges/pull/734)

- [ ] ~~Have we added some sort of diagram reflecting our communication with the PostOffice domain?~~ _Removed as we curently have no communication from BRS-031/032/033 and the documentation should be added together with the implementation_

**Comment by PerTHenriksen** [comment]
Ready to be closed, once references to Postal office has been replaced by Messagehub on https://github.com/Energinet-DataHub/geh-charges#architecture

**Comment by prtandrup** [comment]
Fixed both the Post office ref in the README and in the context stream diagram. Move to closed
