### ISSUE TITLE
Create contracts for creating charge links for new metering points (Batman dependency)

### ISSUE THREAD

**Issue by PerLysemose** [Energinet-DataHub/geh-charges#587]
**Synopsis**
Define the contracts for communication with the metering point domain to support creation of charge links for newly created metering points.

See image in tech notes for details about the decided business process orchestration, which is owned by the metering point domain.

**Acceptance-Criteria**
Protobuf contracts for communication with the metering point domain to support the creation of charge links for newly created metering points have been:

1. Agreed with the metering point domain team
2. Added to source code
3. Added to documentation
4. Ensure #588 and #591 are updated if the outcome of this story affects them.

The contracts are:
- Create metering point command
- Create charge link command
- Receipt for create metering point command
- Receipt for create link command

**Tech Notes**
IMPORTANT: Settle with software architect whether the charges domain can/must rely on it's anticipated metering point state (based on received integration events)!

![domainflows-Create MeteringPoint.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/ee4cf623-a521-4524-9e23-cb777e25253c)

**Comment by PerTHenriksen** [comment]
update w. drawings Martin made. 

Include additional communication flow regarding forwarding to grid company, incl recipt

**Comment by prtandrup** [comment]
Topics currently being clarified: 

- Is it really necessary to have 3x commands from MP domain for the charges domain to fulfill the requirements? Wouldn't it suffice with just 1 command (Create Links)
- Do we need a request_id (or command_id) as part of the command's meta data?
- Is the Charges domain owning the receipt contract?

**Comment by prtandrup** [comment]
Note: Only CreateMP for Consumption MPs are in scope for first sprint.

**Comment by prtandrup** [comment]
Regarding the request-reply pattern for 'CreateChargeLinks'. Different ways to handle this exist, yet some insights into the needs/thoughts behind the "process management idea" is required in order to select the most feasible solution. 

I have had a talk with team member of team Batman, and we both lean towards solution 2 in the picture below, which is the simplest of them. Yet, there seems to be some underlying requirements in the "process mgmt idea or in logging" which might make this option inadequate. Therefore, I am trying to get hold of Martin (Architect) to get some clarification.

![BRS-004_flow_integrationEventsAndCommands.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/8bd254f7-89be-44fa-bcea-51d61c7df2fd)

**Comment by prtandrup** [comment]
Had a talk with our architect. The reasoning behind the process mgmt idea appears to be rooted in "Statistics/optimization/error handling". Hence, when looking at the 'Create Metering Point process flow' the Metering Point domain will have an easy way to detect if the Charges domain is not responding/takes a lot of time/doesn't complete its tasks. One could argue that this should be the responsibility of the Charges domain to detect and handle, but this is currently the approach the architect wants to go.

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/3f874e40-9fa2-4891-9dff-d9381b2f5cf5)

So right now, this solution seems to be the way. Now we need to establish the data to be transferred over the wire, including a way to tell that "Charges is finished with the process"

**Comment by prtandrup** [comment]
I'm somewhat shifting towards presenting a solution to the architects that rely on the below solution instead:
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/c1f7534e-a0a1-4b9b-ba94-516bd08c8bdf)

**Comment by prtandrup** [comment]
After having presented to the architects and adding their feedback, the chosen solution can be seen below.

Regarding ACs:
- 1) Contracts cleared with MP domain (Daniel P)
- 2) Contracts defined and added to source with this [PR](https://github.com/Energinet-DataHub/geh-charges/pull/643). 
- 3) Documentation-wise a link to our contracts.md have been added to the repo's README, which has links to all the contracts defined as a result of this story. Please see the PR mentioned above.
- 4) I've had a look at the two stories 588 and 591 and updated them.

![BRS-004_flow_integrationEventsAndCommands-Chosen-Solution.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/e18e8970-2db9-4c55-b3c3-b912aa86123a)
