### ISSUE TITLE
Reimplement creation of default charge links - now orchestrated by metering point domain

### ISSUE THREAD

**Issue by PerLysemose** [Energinet-DataHub/geh-charges#588]
**Synopsis**

Currently, the assumption was to listen to the loosely typed contract for metering point created event and then create charge links for the metering point. However, architects has decided to go with orchestration and it has now become the responsibility of the metering point domain to explicitly request when the charges domain must create the default charge links and when default charge link message are to be made available for the PostOffice.

**Tech Notes**

With the rise of the request-reply pattern we need to refactor our default charge link related event to be handled as requests and replies as shown below:
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/c889bc25-5000-4993-a143-575ff85ed49a)
For further details about this, please see this [PR](https://github.com/Energinet-DataHub/geh-charges/pull/643)

Following assumptions stems from a talk between @kft, @Sondergaard  and @BjarkeMeier:
- Volt defines the contracts - done by 587, see [this](https://github.com/Energinet-DataHub/geh-charges/blob/pta/definingContractsForDefaultChargeLinks-587/docs/contracts.md#charge-link-requests-and-replies). 
- Communication uses request-reply (async) semantics
- Transport uses queues
- Volt provides functionality by means of NuGet packages

Team assumptions
- logging according to ADR-008 is out of scope atm.

**Acceptance-Criteria**

AC 1:
Given the metering point domain
   And a metering point is known in the charges domain from integration events
When the metering point domain requests the charges domain to link charges to the metering point
Then the charges domain links charges from default charges (if any applies to the metering point type in question)
   And replies to the metering point domain (regardless if any charge links were created)

AC 2:
Given a developer that want to `create default charge links`
When he search nuget.org for a package 
Then a package is presented in the search result

AC 3:
Given a developer that is using the package
When he integrates the package into his solution
Then he does not see the underlying technology except for when configuring the client.

### Tasklist V2
- [x]   implement "Reply" functionality in Charges after a CreateDefaultChargeLinkMessagesRequestAsync is recieved (stub implementation) @lasrinnil 
- [x]   Write integrationtest for CreateDefaultLinksRequest (https://github.com/Energinet-DataHub/green-force-art/tree/33d2b40bf32d764cade9cc8e8771d4deb31a3640/tools/green-force/intra-domain-test-squadron/Samples.Tests)
- [x]   Write integrationtest for CreateDefaultLinkMessagesRequest - only for replies, request is done
- [x]    Avoid multiple copies of the same protobuf contracts by moving all request/reply-related protobuf contracts to a single common place to be used in both Charges.Clients and elsewhere in the Charges domain 
- [x]    Replace the simple types _replyToQueueName_ and _createLinkRequestQueueName_ with a configuration object to avoid the mix of complex and simple types for DI registration. This change is requested by Team Batman.
- [X]    Add missing releasenotes
- [X]    Upgrade Energinet.DataHub.Core.FunctionApp.TestCommon to latest version.
- [x]    Remove dependencies from GreenEnergyHub.Charges.TestCore, and use this project instead of Energinet.DataHub.Charges.TestCore
- [x] Update architechture diagram + align contracts.md to the reduced number of request/reply and URLs to the new proto file location.

### Unresolved Tasklist -> moved to dev session board
- [x]   Replace `should_skip` with `has_changes` in all workflows within the Charges domain @BjarkeMeier? [Dev board topic](https://app.zenhub.com/workspaces/team-volt-dev-session-615167844e83ef001107e157/issues/energinet-datahub/geh-charges/774)
- [x]   Is `CreateLinkCommandEvent` a command or an event? [Dev board topic](https://app.zenhub.com/workspaces/team-volt-dev-session-615167844e83ef001107e157/issues/energinet-datahub/geh-charges/775)

### Move to separate stories
- [x]   Write integration tests for Charges when using the package. #772
- [x]   Write initial documentation and release notes for the Nuget package @HenrikSommer #773

### Tasklist Historic
- [X]   Remove topic _sbt-create-link-command_ and subscription _sbs-create-link-command-charges_ from Charges
- [X]  Create queue `create-link-request` in Charges "Shared"
- [X]  Create queue `create-link-reply` in Charges "Shared"
- [X]  Create queue `create-link-request` in Shared
- [X]  Create queue `create-link-reply` in Shared
- [X]   Create NuGet package with CreateDefaultChargeLinkRequestAsync(string meteringpointId) @lasrinnil 
- [X]   Create in NuGet package CreateDefaultChargeLinkReplyAsync(string respondQueue)
- [x]   implement "Reply" functionality in Charges after a CreateDefaultChargeLinkRequestAsync is recieved
   - [x]   Refactor the event to contain a list of commands to ensure bundling is handled (needs team approvel in dev session) @lasrinnil 
- [X]   implement Read(byte[] message) in Nuget package (delegate solution requested) @HenrikSommer 
- [X]   Create queue `create-link-messages-request` in Charges "Shared"
- [X]   Create queue `create-link-messages-reply` in Charges "Shared"
- [X]   Create queue `create-link-messages-request` in Shared
- [X]   Create queue `create-link-messages-reply` in Shared
- [X]   Implement CreateDefaultChargeLinkMessagesRequestAsync in Nuget package
- [X]   Setup a pipeline able to build / test / build nuget package, and upload to nuget.org (there is excisting examples in our hackathon repo) - ensure package version is bumped witch checking the version number is not occupied on nuget ((NUGET_TOKEN))
- [X]   Unit test CreateDefaultChargeLinkRequestAsync() functionality
- [X]   Unit test Read(byte[] message) functionality
- [X]   Unit test CreateDefaultChargeLinkMessagesRequestAsync() functionality
- [x]   implement Read(byte[] message) in Nuget package for Messages reply
- [x]   Unit test Read(byte[] message) for Messages reply functionality
- [x]   Re-visit Proto documentation (.proto files have moved into NuGet-package)
- [x]   According to ART decision the NuGet package must support Service Bus queue name overriding with the purpose of enabling system tests
~~- [ ]   Consider moving `DefaultChargeLinkReplyReaderBase`, `DefaultChargeLinkMessagesReplyReaderBase` and other parts to separate projects~~
- [x]   Use Protobuf oneof to differentiate between _succeeded_ and _failed_ reply

**Comment by lasrinnil** [comment]
To whoever tests this ticket, ping me so I can give you a quick introduction on how to use the NuGet package to request Charges to create default charge links.

**Comment by Mech0z** [comment]
Tested by sending a message using the nuget package for metering point 575391908025497398

The message flowed through Charges domain as expected and was received by Metering Point domain
![image](https://user-images.githubusercontent.com/2316684/143871891-c79fb0ad-5f12-4452-b9fa-edc47eb21fe4.png)
