### ISSUE TITLE
Extend "på tværs" test suite with charge link tests (related to MP created only)

### ISSUE THREAD

**Issue by PerLysemose** [Energinet-DataHub/geh-charges#590]
In scope: 
From Metering Points domain (Create MP) to Charges => Outbound integration event (ChargeLinkCreated)

Nothing Charge Link related hits the post office at the time of writing this story, hence that part is considered out of scope

**Comment by PerTHenriksen** [comment]
system testing is out of scope of current pi, thus not a pi6 task.
