### ISSUE TITLE
Create, save and publish information about accepted charge links to the post office

### ISSUE THREAD

**Issue by PerLysemose** [Energinet-DataHub/geh-charges#598]
We need to:
* Determine if the grid needs to receive information
* Create the CIM/XML if information is needed
* Save the CIM/XML to blob storage
* Publish information about the message to the post office

**Comment by BjarkeMeier** [comment]
@PerTHenriksen , @PerLysemose: I close this issue as it is being replaced by #642 and #646.

**Comment by PerLysemose** [comment]
@BjarkeMeier got it :-)
