### ISSUE TITLE
Joules  initiated meeting: How to enable Joules in consuming validated time series from (Volt) Delta lake

### ISSUE THREAD

**Issue by PerLysemose** [Energinet-DataHub/geh-charges#604]
Joules will be the initiator of this meeting. The meeting will be about:

Following the new architectural decision to closer integrate Timeseries and Aggregation domains by sharing data in Delta Lake we need to set up a meeting with Joules with these agenda items:
- how do we enable Joules in consuming validated time series from Timeseries domain?
- can Joules enable Volt to fulfill the PI objective of consuming Timeseries data by sharing validated metering points

**Comment by PerTHenriksen** [comment]
include talk about shareing of validated metering points

**Comment by HenrikSommer** [comment]
I have talked to @MadsBloendAndersen regarding this story, and we have agreed to wait until our system and software architects have decided whether to keep Timeseries and Aggregation as separate domains or unite them in one domain. Following that decision, we can return to the agenda of this story.

**Comment by BjarkeMeier** [comment]
@PerTHenriksen , @PerLysemose I talked to @mknic from Joules. Joules will initiate the meeting when they are ready. It will not be in this sprint so I've moved the issue back to the top of the product backlog.
