### ISSUE TITLE
Enable Grid Access Providers to peek confirmation messages for valid Charges they've submitted

### ISSUE THREAD

**Issue by PerLysemose** [Energinet-DataHub/geh-charges#607]
**Synopsis:** 
As a Grid Access Provider that has submitted a valid `Charge (w/wo prices)` message
I want the ability to get (peek) a confirmation message for it
So that I know the GreenEnergyHub has (processed and) accepted it

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/e1a849b7-6bff-4a2e-8423-da57c9c9a2fe)

**Tech notes:**
* The `ChargeConfirmation` event is temporarily placed in the Charges domain's Service Bus. This should no longer be the case when this story is done.
* RSM-033 CIM XML confirmation message name: ConfirmRequestChangeOfPriceList
* Rejection messages are out of scope.
* It is expected that this story includes as a minimum the following unit, integration and domain tests:
- Unit tests: Create CIM XML bundle for confirmation for `ConfirmRequestChangeOfPriceList`
- Integration test: Write/Read from the new data available table that will be created as part of this story.
- Domain test: Submit Charge -> Asserts: DataAvailableNotification (on CorrelationId) & Confirmation message (on correlationId if possible, otherwise on some identifying content)
* Decided on team dev session: While doing this story, please search the entire solution and ensure that Post Office is renamed to MessageHub. 

**Acceptance criteria:**
**AC1** 
Given a valid Charge is submitted by a Grid Access Provider, 
When the Grid Access Provider peeks for messages
Then a CIM XML confirmation message (RSM-033) is provided with correct content informing that the submitted Charge was accepted.

~~**AC2**: The Grid Access Provider must be able to dequeue a peeked confirmation message, and move on to peek the next available message, which could be another confirmation message.~~

~~**AC3**: 
Given a confirmation for a Charge is peeked, but not dequeued.
When the Grid Access Provider submits another Charge that is accepted and confirmation data is made available to the MessageHub
When the Grid Access Provider peeks again (same bundleId), then the peek response remains the same as the first time it was peeked.~~

**Comment by prtandrup** [comment]
### Tested in U-002:

````
AC1
Given a valid Charge is submitted by a Grid Access Provider,
When the Grid Access Provider peeks for messages
Then a CIM XML confirmation message (RSM-033) is provided 
with correct content informing that the submitted Charge was accepted.
````

**Submitted a new Charge (Tariff, Id: ChargeId01, GridAccessProvider/Owner: 8100000000023)**

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/591e39ec-792c-4e24-a392-7673d8dafee8)

**Look-up database:**

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/73cfe1a4-60fe-4dad-b19b-ddd0d5b733d7)

**Grid Access Provider peeks and receives the confirmation:** 
.... Currently not functioning => Blocked status => reaching out to Titans.

**Comment by prtandrup** [comment]
In agreement with PO, AC2 and AC3 are crossed out. As there is a known MessageHub peek-dequeue issue right now, the failure of AC2 and AC3 would potentially block this story. This was not the intention with those ACs. 
AC1 can be verified with a few "twists and pulls" here and there and this is considered ok.

**Comment by prtandrup** [comment]
### Tested in U-002:

````
AC1
Given a valid Charge is submitted by a Grid Access Provider,
When the Grid Access Provider peeks for messages
Then a CIM XML confirmation message (RSM-033) is provided 
with correct content informing that the submitted Charge was accepted.
````

**Submitted a new Charge (Tariff, Id: ChargeId05, GridAccessProvider/Owner: 8100000000023)**
Note the mRID: OpId2021-12-16T11:52:00.004Z this will be our reference ID in the confirmation.

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/6bbab8dd-dc95-48a1-af90-df66a4cb4bc2)

**Verify created in database:**

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/a5cbb163-97c6-42f8-80ef-e903a5ff3818)

**Grid Access Provider peeks for confirmation message:**
Content is OK, and the <cim:originalTransactionIDReference_MktActivityRecord.mRID> points to the submitted charge message:

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/f573efc8-62ee-4086-8a85-773410f4d645)

### Extra

It is stated that rejection messages are out of scope, but currently the solution can provide rejection message (although not with correct error texts. Just wanted to document it here :smiley:

**Peeked rejection message:**
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/5d666159-00d6-4fd3-8b99-c1df32d5a433)
