### ISSUE TITLE
Prepare input for GUI - alignment on charge link data to be presented in GUI

### ISSUE THREAD

**Issue by PerLysemose** [Energinet-DataHub/geh-charges#611]
**Synopsis:**
Upon searching and viewing a single consumption metering point in a Graphical User Interface (GUI), the Charges domain must be able to provide required charge links data to fulfill any metering point viewer's needs (viewer could be Grid Access Provider, Electricity Supplier, Admin/support or the TSO). 
With this story team Volt is to clarify charge link data needed, so we later can built the right API's to serve this data to a GUI. Another story will take care of the actual implementation.

The user is expected to search and view a single metering and within that screen it is possible to view a simplistic overview of the active charge links associated with the given metering point. 
Additionally some action can be performed within the screen, which will display any historical charge links associated with the given metering point. 
Note: The displayed charge link data will vary depending on the user's rights, market participant role, association with the metering point, etc.

**Active versus Historical charge links:**
- A tariff/subscription link is active when it has no end date (stop date) OR end date >= today's date, else its' historical.
- A fee link is a special case, it is active 90 days after its' start date. 91 days after its' start date it is considered historical.

~~Ved fremsøgning af et målepunkt, skal alle former for aktive chargelink for både tariffer, abonnement og gebyr fremvises simpel og danne et hurtigt overblik for brugeren.
Funktionsmulighed så man kan få overblik over de historiske link for et målepunkt. Sikre visningen tilpasses rettigheden af rollen og rollen for visning af link ved målepunkt fremsøgning~~

The following must be supported:
- [ ] By default show all active charges (tariffs, fees, subscriptions) for a consumption metering point
- [ ] Historical charge links may be viewed as well by performing some action
- [ ] The displayed charge link data will vary depending on the user's rights, market participant role, association with the metering point, etc.

**Out of scope for this story:**
Displaying charge link data for other types of metering points (only consumption is in scope).
Display business process (BRS-037)
Maintain Charge Links via GUI

**Acceptance criteria:**

Oplæg til opsætning af prislink ved fremsøgning af et målepunkt:

1. Ingen ”faneopdeling” af de tre typer priselementer, men en simpel linje adskillelse af tarif, abonnement og gebyr (Stephanie). Dette for at undgå for mange klik og for at få det fulde overblik. Gebyr skal vises for den aktuelt måned målepunktet fremsøges i.
2. Kolonner som skal vises (Mighty Ducks og Volt):
• Pris ID
• Navn for priselementet
• Pris ejer
• Afgift (tarif)
• Viderefakturering
• Mængde (gebyr og abonnement)
• Tilknyttet fra (altid)
• Tilknyttet til (kun når der angives flueben for historisk overblik)
3. Fremvisningen skal sortereres efter ”tilknytning fra” og derefter pris ID (Mighty Ducks og Volt)

**To be moved to a new story:** 

4. Mulighed for at sortere på de andre kolonner (OBS – der vil være en form for markering af den grundlæggende sortering). Afklaring om det vil medføre sortering for alle priselementer eller for en af typerne (Mighty Ducks)
5. Kun visning af aktive priselementer (Mighty Ducks og Volt)
6. Flueben markering for fremvisning af historiske link (OBS husk en ellev kun må se gældende tariffer mens de har /havde leverancen) (Mighty Ducks og Volt)
7. Link genvej til charge (ved klik på pris ID, så linkes man over til den aktuelt stamdata for priselementet) (Stephanie og Volt)
8. Forretningstransaktionen (BRS-037) skal angive, hvornår linket er gældende fra (i dag skal beskeden åbnes for at finde den besked der evt. har tilknyttet et link. På den måde kan man risikere at åbne 5 beskeder før den rigtig besked hentes frem). Alternativ kan det løses ved at man kan link tilbage til forretningstransaktionen fra oversigten af priselement. (Mighty Ducks og Volt)
Til aktørtest er det følgende punkter som kræves som accept kriterier:
1 til 3.
Men de følgende punkter vil fortsætte de efterfølgende PI.

**Comment by prtandrup** [comment]
Pending a talk with Alexander from Mighty Ducks before this story can be scoped and refined.

**Comment by prtandrup** [comment]
After working on this story, I realized that it was actually just about refining the next story that would 'implement the delivery of charge links to the GUI', which is done in #792. I have no refined that, therefore I close this one.
 
Note: most of the same info found on this story, is located in the comments on this MD [story](https://app.zenhub.com/workspaces/feature-board-60e2eb437d96850014aa15ab/issues/energinet-datahub/green-energy-hub/196).
