### ISSUE TITLE
Publish integration events (ChargeCreated + ChargePricesUpdated)

### ISSUE THREAD

**Issue by prtandrup** [Energinet-DataHub/geh-charges#612]
As another domain in the Green Energy Hub context
I want the Charges domain to publish the integration event `ChargeCreated` when a new charge is created, 
And the integration event `ChargePricesUpdated` when the charge was created with prices.
So that I can listen for the data, which I need to fulfill my domain's own responsibilities. 

**Synopsis:**
Today, when we receive a valid new charge, we stored it and publish a confirmation to the sender on the Service Bus standing-in for the PostOffice domain. 

Besides above, we need to extend this happy flow with publishing two integration events:
- [ChargeCreated](https://github.com/Energinet-DataHub/geh-charges/blob/main/docs/contracts.md#chargecreated) (with charge master data)
- [ChargePricesUpdated](https://github.com/Energinet-DataHub/geh-charges/blob/main/docs/contracts.md#chargepricesupdated) (the prices of that charge)

![ChargesProcesFlow.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/35a69ba7-8286-4213-a313-005767d588f4)

Notes: 
- Publishing in `U - Development:` Local Service Bus in Charges domain
- Publishing in `T - Test:` Shared Service Bus

**Acceptance criteria**
- [x] Given a valid charge message was received including prices, when processing this, Then we publish both integration events and their content comply to contracts.
- [x] Given a valid charge message was received excluding prices, when processing this, Then only the ChargeCreated integration event is published.
- [x] Given an invalid charge message was received, when processing this, then no integration events get published.
- [x] The [process flow documentation](https://github.com/Energinet-DataHub/geh-charges/tree/main/docs/process-flows#change-of-charge-price-list-flow) has been updated to reflect the publishing of two integration events.

**Comment by bemwen** [comment]
### Test result:

**Given a valid charge message was received including prices, when processing this, Then we publish both integration events and their content comply to contracts: - PASSED**

A valid charge message with prices was sent to the T-environment as seen below:

![image.png](https://images.zenhubusercontent.com/60bdd871726f411a853d94a9/866569cc-e7b5-44ef-8ca5-08f05cced4a9)

It resultatet in one charge created event and one charge price updated event as can be see in the queues

![image.png](https://images.zenhubusercontent.com/60bdd871726f411a853d94a9/f19d433f-27bf-4c07-af4e-76f62c42d202)

![image.png](https://images.zenhubusercontent.com/60bdd871726f411a853d94a9/805aa293-a59f-4c53-b688-83a1b14a3bc9)

Deserializing the charge created event using the protobuf contract results in the following correct event content:

![image.png](https://images.zenhubusercontent.com/60bdd871726f411a853d94a9/755a2feb-4e90-491d-8b23-fcc04870f872)

Deserializing the price updated event using the protobuf contract reveals a correct event with 24 prices (not all shown in screenshot):

![image.png](https://images.zenhubusercontent.com/60bdd871726f411a853d94a9/53555f8a-8945-497e-8363-3c06da628dad)

**Given a valid charge message was received excluding prices, when processing this, Then only the ChargeCreated integration event is published: - PENDING**

Validation rule blocks this from being able to take place using postman.



**Given an invalid charge message was received, when processing this, then no integration events get published: - PASSED**

An invalid charge message (sent to late) was sent to the test environment.

![image.png](https://images.zenhubusercontent.com/60bdd871726f411a853d94a9/4eed2c0f-1e99-4785-aafa-f83d437e0bcd)

This neither resulted in charge created or price updated events as can be seen by the below queues.

![image.png](https://images.zenhubusercontent.com/60bdd871726f411a853d94a9/fae98f6e-6231-4f4a-ba34-c2214cfe5155)

![image.png](https://images.zenhubusercontent.com/60bdd871726f411a853d94a9/dc266c84-72b9-4781-a96c-8f216af38f14)

**The process flow documentation has been updated to reflect the publishing of two integration events.: - PASSED**

https://github.com/Energinet-DataHub/geh-charges/tree/main/docs/process-flows#change-of-charge-price-list-flow now includes the two new integration events as required by the AC.
