### ISSUE TITLE
Enable the Grid Access Provider to peek/get default charge links notification(s) as part of the 'create metering point' process 

### ISSUE THREAD

**Issue by bemwen** [Energinet-DataHub/geh-charges#614]
**Synopsis**
As a Grid Access Provider whom has just created and new metering point and peeked a 'metering point created' confirmation
I want the ability to also peek Charge Link notification(s) for any tax charge links that were linked to this new metering point by default
So my company is able to correctly settle with the Danish Tax Authorities.

The highlighted parts of the diagram below covers the work to be done in this story:

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/45996378-1d40-431e-a58b-36f1adbf7389)
![ARCHITECTURE_ChargeLinks_614.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/f3d9a616-09ad-4d13-8581-8ffa6cd63468)

This approach have the following apparent problems:
1) We are an event domain, but the management of CreateDefaultLink now works without events within the charge domain
2) We do not automatically publish when we create def links, only when initiated by another domain.

**Tech notes:**
- It must be clarified with team Batman, whether they want the reply when (1) the Charges domain has made the notification(s) available to the Grid Access Provider or (2) await the actual peeking of the notification before getting the reply. As of writing this story (1) seemed to be the way forward.
- This story includes processing the [CreateDefaultChargeLinkMessages request](https://github.com/Energinet-DataHub/geh-charges/blob/main/source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Integration/ChargeLink/Commands/CreateDefaultChargeLinkMessages.proto), making the RSM-031 CIM XML message(s) available to the Grid Access Provider (via MessageHub/PostOffice) and replying with [CreateDefaultChargeLinkMessagesSucceeded](https://github.com/Energinet-DataHub/geh-charges/blob/main/source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Integration/ChargeLink/Commands/CreateDefaultChargeLinkMessagesSucceeded.proto) back to the Metering Point domain.
- Batman/MeteringPoint is expected to provide a reply path as part of the request meta data, so we know where to reply to.
~~- API mgmt support in postman is part of the demo scope.~~
- Extend repository with a method that returns only the default charge links (param MP ID)

Considered out of scope for this story:
- Error handling resulting in a [CreateDefaultChargeLinkMessagesFailed reply](https://github.com/Energinet-DataHub/geh-charges/blob/main/source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Infrastructure/Integration/ChargeLink/Commands/CreateDefaultChargeLinkMessagesFailed.proto). 
- ADR-0008 meta data is out of scope, will be handled in another story when requirements for request-reply pattern is settled.

**Acceptance criteria:** 
- [ ] AC1: 
Given a `CreateDefaultChargeLinkMessages request` is received from the Metering Point domain for a New Metering Point that has been linked to default charges
When the Charges domain has processed this request
Then the Grid Access Provider is able to peek a RSM-031 CIM XML 'charge link notification' via the Post Office containing any tax charge links on the given metering point
And a `CreateDefaultChargeLinkMessagesSucceeded reply` has been returned to the Metering Point domain at the expected location and with the correct content and meta data.

### Tasklist
- [ ] avoid DataAvailable notification (MessageHub) when Charge Link Created request is received:
    - [ ] CreateChargeLink function no longer creates a ChargeLinkCommandReceived event, but instead persists ChargeLink
- [ ] implement "Reply" functionality in Charges after a CreateDefaultChargeLinkMessagesRequestAsync is recieved:
    - [ ] New CreateDefaultChargeLinkMessages function get ChargeLink from db and creates ChargeLinkCommandAcceptedEvent

**Comment by prtandrup** [comment]
Due to implications of having two requests related to 'creating default charge links and messaging', we have decided to changed status to blocked until we have verified with the architect(s) that they still want to pursue this 2x requests approach, instead of just having 1 request.

The 2x request problems as we see them:
- The suggested architectural design for this story 'smells' as it moves us further away from being event driven.
- Publishing Charge Link data to other domains, like Aggregations, is now controlled by the Metering Point domain - was that intended?
- It decreases the reusability of components, which would be significantly higher with just 1x request

**Comment by prtandrup** [comment]
We had a meeting with the architects today (Lasse, Bjarke and I).
Conclusion: 
1) Carry on with a single request-reply setup, where Charges...
- reply to the Metering Point domain when Charges cannot process the request (e.g. MP unknown to the Charges domain)
- reply to the Metering Point domain when Charges has successfully processed the request by having made default charge links data available to the MessageHub.
2) Should it be a requirement/need of the Metering Point domain to be notified about any intermediate steps of the default charge link process, like when the links have been created, then we expect the Metering Point domain owners to come forward with those requirements, so we can built the best solution for it. 
2a) The same goes for a need to know when the charge link data was peeked and dequeued by a Market Participant.

**Comment by prtandrup** [comment]
Expect this to be replaced by #795

**Comment by prtandrup** [comment]
Given changed condition; moving from a 2x request/reply pattern to 1x request/reply, this story is closed and replaced by #795.
