### ISSUE TITLE
Provide charge links created bundles via post office (part 1/3): Notify about new data

### ISSUE THREAD

**Issue by BjarkeMeier** [Energinet-DataHub/geh-charges#642]
** Synopsis **

This is the first part of the process of sending a _charge link created_ bundled to the grid operator for electricity taxes (charge.TaxIndicator = true).

This supports both BRS-004 'create new metering point' and BRS037 'handling charge links'

** Please Note **

The splitting of the use case introduces the need to assume an implementation and to have tech based acceptance-criteria in all but the last part.

IMPORTANT: The stories are fragile as they assume a solution and the behavior and contracts for the post office haven't yet been completely settled. It is assumed that the charges domain must be able to support a business requirement of the post office to support bundling, which means that when the grid operator dequeues it will receive all non-dequeued confirmations in a single bundle (but respecting max bundle size calculated from the weight of each message compared to the max weight). This leads to the anticipation (discussed by @bemwen and @BjarkeMeier) that it is better to create the final message when the peek is requested rather than continuously as individual CIM XML messages as links are created. The latter would imply a later merge of the XML documents.

~~IMPORTANT: As of this writing the architect decision is that the charges domain is responsible for sending the _charge link created_ bundle when the charge links are created in BRS-004. This effectively eliminates the need for the charges domain to distinguish whether to send confirmation or not based on _why_ the charge links were created. However, please be aware that the situation is different if the orchestration decision changes (there is currently some debate about this topic).~~

** Tech Notes **

Teams Titans have [these draft drawings](https://github.com/Energinet-DataHub/geh-post-office/issues/215) of communication with the post office.

Based on talk with Titans it is assumed that:
- All communication uses NuGet packages provided by Titans
- It is neither necessary to consume dequeue events nor clean up created bundles
- No book-keeping is needed for refetching/recreating bundles on repeated peeks as we guess that post office will provide path/url of the blob - so we can simply check whether it was already created without having to keep track of the location for the specific peek

** Acceptance-Criteria **

Please note when testing that AC 1 applies both when default charges are created for new consumption metering point (BRS-004) and when charge link creation requested by actor (BRS-037).

AC 1:
Given the charges and post office domains
When an electricity tax tariff (charge) link is created
Then the post office is notified - as (will be) outlined by the post office domain - about new data for the grid operator

AC 2 Ensure #646 and #649 are updated if the outcome of this story affects them

**Comment by PerTHenriksen** [comment]
removed ac 2, for now:
AC 2 (technical requirement due to splitting of story):
Given the charges domain
When notifying the post office about created charge links
Then sufficient information is stored in order to be able to later create the bundled

**Comment by BjarkeMeier** [comment]
Tasks:
- [ ] Rename all handlers (from what they handle to what they do)
- [ ] Add integration test
- [ ] Add unit tests
