### ISSUE TITLE
Draft GEH HTTP response

### ISSUE THREAD

**Issue by BjarkeMeier** [Energinet-DataHub/geh-charges#647]
The software architect asked Bjarke to create a draft suggestion for a unified HTTP response format for all HTTP actor endpoints.

Titans based post office responses on this:
https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#7102-error-condition-responses

**Comment by BjarkeMeier** [comment]
Awaiting PO approval to start working on this.

**Comment by PerLysemose** [comment]
@BjarkeMeier, Per will reach out to you regarding this one as it has been prioritized by PM. We timebox it to 3 hours

**Comment by BjarkeMeier** [comment]
Extract of what was handed over to Søren below.

Recommendation based on section 7.6, 7.10 and 7.11 from https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md. Team Titans has based the post office design on the same guide.
