### ISSUE TITLE
Add a business process description of the Default Charge Link flow

### ISSUE THREAD

**Issue by prtandrup** [Energinet-DataHub/geh-charges#714]
**Description:**
This documentation story is similar to #325, but it covers the process of linking default charges to a metering point as part of the metering point creation process.

Add a Default Charge Links description to the Charges repo that targets the open source community, just like we did for Change of Fee etc. See: https://github.com/Energinet-DataHub/geh-charges/tree/main/docs/business-processes

Note: 
We need to find the right documentation "level" for this, as Charges only handles part of the Metering Point Creation flow.

**Acceptance criteria:**
AC#1: The Default Charge link business process .md has been created and contains as a minimum:
- Description (+ what triggers the process, e.g. request from a Market Actor)
- Sequence diagram

AC#2: Default charge links description has been approved by PO and SME (Irene)
AC#3: Default charge links description has been added to the Charges Repo.

**Comment by PerLysemose** [comment]
To be solved by SME - hence no estimate
