### ISSUE TITLE
Charges: Bundle charge information into CIM/XML messages (Part 2/3)

### ISSUE THREAD

**Issue by bemwen** [Energinet-DataHub/geh-charges#718]
**Synopsis:**
Based on information about charges to bundle we need to be able to create a CIM/XML stream with the information.

Note: Technical story

**Tech note:**
Latest CIM/XML example can be found here:
https://energinet.sharepoint.com/sites/DH3ART-team/Delte%20dokumenter/General/CIM/XSD%20-%20XML%20-%20JSON%20filer/XML%20filer/XML%2020211004%20-%20Danske%20koder/RSM-034%20-%20Notify%20price%20list%20.xml

**Out of scope:**
The following is covered in other stories:
* Saving and retrieving information about charges is handled in #594
* Messagehub exchanges is handled in #595

**Acceptance criteria:**
* Given information about charges to bundle, CIM/XML is generated and written to the requested stream
* Generating the CIM/XML is covered by unit test

**Comment by BjarkeMeier** [comment]
I reviewed the code and it is in main. So I conclude that the ACs are OK. Moving story to PO acceptance.
