### ISSUE TITLE
Documentation and release notes for the Nuget package

### ISSUE THREAD

**Issue by lasrinnil** [Energinet-DataHub/geh-charges#773]
### Synopsis
As Energinet/Datahub we need to document how to use the package.

### Notes
Are there any expectations from the art / SA?

### Acceptance criteria
1) release notes are published with the NuGet package.
2) documentation is released with the NuGet package.

**Comment by bemwen** [comment]
### Testing:

To test the story the nuget-gallary was used to make sure that the needed information was available for people without knowing the location of our source code.

Our nuget looks like this in the gallery:
![image.png](https://images.zenhubusercontent.com/60bdd871726f411a853d94a9/e0c1edec-962c-4ba6-9b11-bab2a95870d4)

**1) release notes are published with the NuGet package - PASSED**

The page has a link to our release notes, https://github.com/Energinet-DataHub/geh-charges/tree/main/source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/documents/release-notes/release-notes.md

![image.png](https://images.zenhubusercontent.com/60bdd871726f411a853d94a9/4add6c50-5c0b-4310-9625-114717fb4d04)

**2) documentation is released with the NuGet package - PASSED**

The page has a link to the documentation.

https://github.com/Energinet-DataHub/geh-charges/tree/main/source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/documents/documentation.md

![image.png](https://images.zenhubusercontent.com/60bdd871726f411a853d94a9/563cce96-a829-4e15-b86a-c5e867e4259e)
