### ISSUE TITLE
Azure Service Bus - best practices

### ISSUE THREAD

**Issue by Sondergaard** [Energinet-DataHub/geh-charges#784]
According to the recommendation from MS in regards to service bus objects ([in general - all azure clients/objects)](https://devblogs.microsoft.com/azure-sdk/lifetime-management-and-thread-safety-guarantees-of-azure-sdk-net-clients/) they should be static/shared or registered as singletons for [best performance](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-performance-improvements?tabs=net-standard-sdk-2#reusing-factories-and-clients). They are by nature thread-safe.

https://github.com/Energinet-DataHub/geh-charges/blob/3b3fab6cfc287ae2ba1c01b24517351f766bacba/source/Energinet.Charges.Libraries/source/Energinet.DataHub.Charges.Clients/ServiceBus/ServiceBusRequestSender.cs#L36

**Comment by lasrinnil** [comment]
@Sondergaard  Team Volt has accepted the implementation based on this ticket. I am closing it. If anything on this matters changes, please reach out to me.
