### ISSUE TITLE
Message Hub domain test is deficient

### ISSUE THREAD

**Issue by BjarkeMeier** [Energinet-DataHub/geh-charges#788]
Origin: #691

### Current Behavior

The test: `When_ReceivingChargeLinkMessage_MessageHubIsNotifiedAboutAvailableData_And_Then_When_MessageHubRequestsTheBundle_Then_MessageHubReceivesBundleResponse` in `source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.IntegrationTests/DomainTests/ChargeLinks/MessageHub/ChargeLinkDataAvailableNotifierEndpointTests.cs`

The test does not assert that a bundle is sent to Message Hub.
The test does not assert that the bundle is the expected one.

### Expected behavior

The test must assert that a bundle is sent to Message Hub.
The test must assert that the bundle is the expected one.

### How to reproduce

Investigate the test code.

### Possible Solution

Requires a session enabled queue listener. Dan from team Mighty Ducks will provide this. So we'll probably prefer to wait for that instead of a temp workaround.

**Comment by prtandrup** [comment]
**Bug test passed** ✅ 

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/6475ce85-a9a2-47a0-b1fa-b6f5985e30dc)

The domain test (added in #691) has been refactored to use the MessageHubSimulator provided by team Titans in their package [Energinet.DataHub.MessageHub.IntegrationTesting](https://www.nuget.org/packages/Energinet.DataHub.MessageHub.IntegrationTesting/). With the aid of this package, we now assert that it is the expected correlation id that is sent to the MessageHub.

For more info on the MessageHubSimulator, please go [here](https://github.com/Energinet-DataHub/geh-post-office/blob/main/source/Energinet.DataHub.MessageHub.IntegrationTesting/source/Energinet.DataHub.MessageHub.IntegrationTesting/MessageHubSimulation.cs).

Has been through PO acceptance, hence Closed.
