### ISSUE TITLE
Reply to the Metering Point domain once Default Charge Link data is available to the Market

### ISSUE THREAD

**Issue by prtandrup** [Energinet-DataHub/geh-charges#795]
**Synopsis:**
As the Metering Point domain
I want the ability to do a single request to the Charges domain to initiate the linking of default charges to a newly created metering point
And receive a reply once the Charges domain has made charge link data available to the Market
So I know when Charges is done processing its' sub process of my 'Create Metering Point process'

![BRS-004-MeteringPoint-Charges-DefaultChargeLinks-SequenceDiagram.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/edc8d99b-a709-4fc9-9ce3-7aecfb76d814)

**Tech notes:** 
~~ - Ensure that any function or queue/topic name related to the Default Charge Links flow, has _links_ in plural and '_default_' included in their name, so it's clear that they are related to this sub process and may include multiple links. ~~ moved to team dev session
- Existing integration tests must be refactored as this story will remove the request-reply for CreateDefaultChargeLinkMessages.
- Domain test/s to be added: 
~~ -- Submit CreateDefaultChargeLink Request => Assert: CreateDefaultChargeLinksReply (on correlationId)~~ covered by #772
-- Submit CreateDefaultChargeLink Request  -> Asserts: DataAvailableNotification (on CorrelationId) & Charge Link message (on correlationId if possible, otherwise on some identifying content)

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/affd6272-d9ac-4d91-9a25-cbfb5865d7d3)

It is assumed that the "ReplyTo" meta data provided in the request by the Metering Point domain can be transferred in some way to the ChargeLinkDataAvailableNotifierEndpoint in order to only make `DefaultChargeLinksDataAvailableNotified` events related to default charge links creation.

**Acceptance criteria:** 
**AC1:**
Given a `CreateDefaultChargeLinks request` for a new consumption Metering Point without any Default Charge Links
When Charges has made (default) charge Link data available to the Market (informed MessageHub about available data)
Then a `CreateDefaultChargeLinks reply (Succeeded)` is sent to the Metering Point domain

~~ **AC2:** 
Given a known consumption Metering Point _with_ Default Charge Links 
When a new `CreateDefaultChargeLinks request` is received for the same metering point
Then ....? **Team to discuss (1) what happens in this case? and (2) do we implement as part with this story?** ~~

**AC3:**
Given a `CreateDefaultChargeLinks request` for an unknown Metering Point
When Charges processes this
A `CreateDefaultChargeLinks reply (Failed)` is sent to the Metering Point domain with a 'metering point unkown' error

**AC4:**
Given a `CreateDefaultChargeLinks request` for a new consumption Metering Point without any Default Charge Links
When the Charges domain has processed this request
Then the Grid Access Provider is able to peek a RSM-031 CIM XML 'charge link notification' via the Post Office containing any tax charge links on the given metering point

**Comment by prtandrup** [comment]
We (Lasse, Henrik, Michael and I) discussed this story today and estimated it.
Although no functionality is created to handle this yet, we have decided to deem AC2 irrelevant for this story; 
When it comes to processing any charge link request for a metering point which already has the given charge linked, we expect 'regular charge link' and 'create default charge link' requests to use the same functionality/logic. This is expected to be implemented later by another story.
Additionally, we decided to move the part of the story regarding naming of functions/queues/topics to the team dev session board to keep this story lean.

**Comment by Mech0z** [comment]
Tasklist

- [ ] Rename endpoint to match domain diagram
- [ ] Create new queue DefaultChargeLinksDataAvailableNotified
- [ ] Subscribe to new endpoint
- [ ] Refactor logic in ChargeLinkDataAvailbleNotifierEndpoint to send data to DefaultChargeLinksDataAvailableNotified if metadata contains IsReplySet

**Comment by lasrinnil** [comment]
Ac1:
Meterinpoint with id: 575391908025497398 now has links and metering point domain registers we have completed their request

![image.png](https://images.zenhubusercontent.com/60bdfcb3effb2082025638c1/797d1b9d-bd21-44d3-be00-ebf417b45e7d)
