### ISSUE TITLE
Market Participants sends messages to the charges domain

### ISSUE THREAD

**Issue by bemwen** [Energinet-DataHub/geh-charges#816]
**Synopsis:**
We need to enable market participants to send messages to the charge domain through the API management which is their entry point to the Green Energy Hub.

**Out of scope:**
* The full response format to the market participant is out of scope of this story. For the purpose of this story, a temporary response is fine.
* Automatic testing across domain boundaries are out of scope.

**Tech note:**
* The HTTP response code from the charge domain should survive through the API management back to the sender.

**Acceptance criteria**
* A market participant can send a charge creation message to the API management which reaches the charge domain and receive a synchronous response back through the API management.
* A market participant can send a charge link creation message to the API management which reaches the charge domain and receive a synchronous response back through the API management.
* Postman queries must be updated in accordance to go through the API Gateway.

![image.png](https://images.zenhubusercontent.com/60bdd871726f411a853d94a9/69fa75fb-b07c-4663-b6a6-541d733794cb)

![image.png](https://images.zenhubusercontent.com/60bdd871726f411a853d94a9/5e2960df-df2c-4204-9ff0-2a49f7172406)

**Comment by BjarkeMeier** [comment]
In order to peek/dequeue as different market actors JWT tokens can be created at jwt.io with a payload like:
```json
{
  "sub": "8100000000030"
}
```

**Comment by BjarkeMeier** [comment]
Above notes added as description to the postman MessageHub requests in the charges collection.

**Comment by PerTHenriksen** [comment]
Test results;
ac 1) Tested that a charge request can be passed through the api management, and a reply is received from the charges domain:
![image.png](https://images.zenhubusercontent.com/60bdf7bbfa2182da7fd5cc6d/6385cd18-ee8e-4d9a-abee-65f0d911d855)

ac 2) Tested that a charge link request can be passed through the api management, and a reply is received from the charges domain:
![image.png](https://images.zenhubusercontent.com/60bdf7bbfa2182da7fd5cc6d/1f4cd846-ff8d-4fe2-a50c-07f860baa992)

ac 3) Tested that postman global settings did indeed point to api management, thus passing through the request. 
![image.png](https://images.zenhubusercontent.com/60bdf7bbfa2182da7fd5cc6d/5b9dc675-df04-4f33-899b-cd486251dd2b)

**Comment by IreneDataHub** [comment]
Testing summary; all accept criteria passed unsuccessfully

Test results below:

ac 1) Tested that a charge request can be passed through the api management, and a reply is received from the charges domain:

Test results below:
![image.png](https://images.zenhubusercontent.com/612f6568004bdd03eab7ca46/9affc197-49d2-456d-a93a-7b11d17d7ab5)

**Comment by IreneDataHub** [comment]
Testing summary; Test 1 and 2 accept criteria passed unsuccessfully - got the same status 500 regardless environment T-001 or U-001.
 Test 3 passed successfully.

Test results below:

ac 1) Tested that a charge request can be passed through the api management, and a reply is received from the charges domain:

![image.png](https://images.zenhubusercontent.com/612f6568004bdd03eab7ca46/25e085f2-764d-4ed2-8e8c-9c325492e7c7)

ac 2) Tested that a charge link request can be passed through the api management, and a reply is received from the charges domain:

![image.png](https://images.zenhubusercontent.com/612f6568004bdd03eab7ca46/eb25d9e0-8065-4f0f-a39d-70eef91a41c2)

c 3) Tested that postman global settings did indeed point to api management, thus passing through the request.
![image.png](https://images.zenhubusercontent.com/612f6568004bdd03eab7ca46/0eac4ae6-4cd8-4031-a957-915ac31060be)

**Comment by IreneDataHub** [comment]
Testing summary; Test 1, 2 and 3 passed successfully.

Test results below:

ac 1) Tested that a charge request can be passed through the api management, and a reply is received from the charges domain:
 ![image.png](https://images.zenhubusercontent.com/612f6568004bdd03eab7ca46/11f96a5d-5100-490d-9754-e58b824908bf)


ac 2) Tested that a charge link request can be passed through the api management, and a reply is received from the charges domain:
![image.png](https://images.zenhubusercontent.com/612f6568004bdd03eab7ca46/e3e6a205-9011-4274-8ea1-213a79a3247b)


c 3) Tested that postman global settings did indeed point to api management, thus passing through the request.
 
![image.png](https://images.zenhubusercontent.com/612f6568004bdd03eab7ca46/f09036f3-a404-4d69-95fb-f8fdbf91b15b)
