### ISSUE TITLE
Market participants' Charges messages which fail schema validation are rejected

### ISSUE THREAD

**Issue by bemwen** [Energinet-DataHub/geh-charges#817]
**Synopsis:**
We want to schema validate the incoming Charges messages from market participants to the charge domain to make sure that they follow the expected CIM/XML syntax.

We want to return the result to the caller of our ingestion points synchronously to live up to the markets expectations on when schemas are validated.

**Tech note:**
* Skemavalidering. Titans lever NuGet pakke. De enkelte teams skal hooke det ind, og levere skema der valideres
* Add domain test: Verify a "400 bad request" response upon submitting an invalid CHARGE message

**Acceptance criteria:**
* CIM/XML request change of pricelists is schema validated and the result returned to the sender
* Successfully schema validated packages should return success back to sender (HTTP 202 Accepted)
* Unsuccesful schema validated packages should return failure back to to sender (HTTP 400 Bad Request) including list of schema validation errors
* Sync response must comply to the CIM XML webservice interface documentation (https://energinet.dk/-/media/B4DEEF1CFBAC418C9EA7923FDD38AA45.pdf)
* Validation result is logged to application insight

![image.png](https://images.zenhubusercontent.com/60bdd871726f411a853d94a9/f5772b52-f9bf-48b3-8b6a-cba893903106)

**Comment by PerTHenriksen** [comment]
Agree that Titans will expand the task with replying to the participant, as described in the linked pdf.  (assumed titans have ownership of the entire story)
