### ISSUE TITLE
Charge ingestion points down in T-001

### ISSUE THREAD

**Issue by BjarkeMeier** [Energinet-DataHub/geh-charges#845]
https://teams.microsoft.com/l/message/19:3fa44dbb75854b57a4a48936d70743b6@thread.tacv2/1637165039266?tenantId=f7619355-6c67-4100-9a78-1847f30742e2&groupId=38e0432b-6379-40d1-9b3a-b1b90c48de70&parentMessageId=1637165039266&teamName=Mighty%20Ducks%20-%20Public&channelName=Questions&createdTime=1637165039266

**Comment by PerTHenriksen** [comment]
closed as part of #816 test
