### ISSUE TITLE
Code coverage seems to malfunction

### ISSUE THREAD

**Issue by BjarkeMeier** [Energinet-DataHub/geh-charges#866]
This is just one example where the diff in coverage does not match the expectation. For dependabot PRs expectation is (cirka) 0%.

![image.png](https://images.zenhubusercontent.com/60c2e712ae37899de9483e3a/4dcd6b77-2148-411b-80d0-5487c624a21e)

**Comment by BjarkeMeier** [comment]
I've talked to Daniel from team MightyDucks and he accepted to disable code cov. So this bug only addresses disabling of the wrong report. MightyDucks will take care of eventually fixing the reports.

**Comment by Mech0z** [comment]
Tested by validating that CodeCov is not part of PR currently
