### ISSUE TITLE
Default charge link uses hardcoded DataHub GLN

### ISSUE THREAD

**Issue by BjarkeMeier** [Energinet-DataHub/geh-charges#869]
Default charge link (`source/GreenEnergyHub.Charges/source/GreenEnergyHub.Charges.Domain/DefaultChargeLinks/DefaultChargeLink.cs`) must use hub sender ID from configuration.

Please also remove this obsolete comment:
`// Logically there is a MeteringPointType attached to the DefaultChargeLink, but atm. It is not used.`

**Comment by lasrinnil** [comment]
verified through the changed implementation and the test covering it.
