### ISSUE TITLE
Domain test log output contains errors

### ISSUE THREAD

**Issue by BjarkeMeier** [Energinet-DataHub/geh-charges#879]
Example: https://github.com/Energinet-DataHub/geh-charges/runs/4235636600?check_suite_focus=true

It's currently unknown whether it's a technical problem or an error in the production code. But we should fix it. Also because it might hide other important errors if we just leave it as-is.

**Comment by HenrikSommer** [comment]
Give me a call if you take this story

**Comment by bemwen** [comment]
Fixed in #977 and #968

**Comment by BjarkeMeier** [comment]
Test: This doesn't look as desired (should be the [latest CI](https://github.com/Energinet-DataHub/geh-charges/pull/981/files) from this story - PR #977):
![image.png](https://images.zenhubusercontent.com/60c2e712ae37899de9483e3a/be161f84-6fd2-445d-835e-2c4837033189)

**Comment by bemwen** [comment]
Log entries shown was caused by missing environment variable in the charge app fixture.

Fixed in #983

**Comment by BjarkeMeier** [comment]
Test OK: I can't find any significant errors in [the latest test run](https://github.com/Energinet-DataHub/geh-charges/runs/4604161847?check_suite_focus=true).
