### ISSUE TITLE
Update to latest MessageHub.Client to re-establish communication with MessageHub after breaking changes were introduced

### ISSUE THREAD

**Issue by BjarkeMeier** [Energinet-DataHub/geh-charges#888]
Acccording to team Titans MessageHub communication has breaking changes from 26th of November.

We'll need to fix this.

See [this post](https://teams.microsoft.com/l/message/19:91c8a12a0ed34734b72b5678596377f5@thread.tacv2/1637913716878?tenantId=f7619355-6c67-4100-9a78-1847f30742e2&groupId=e1b7877a-ee7d-4505-a4b2-4989abc2d22a&parentMessageId=1637913716878&teamName=GreenForce&channelName=Developers&createdTime=1637913716878):
![image.png](https://images.zenhubusercontent.com/60c2e712ae37899de9483e3a/0cdda54b-6eec-4e91-9d65-0904ba9cf4bc)

**Comment by Mech0z** [comment]
Tested on U002 that peek still works
![image](https://user-images.githubusercontent.com/2316684/144433084-8ea8f26e-57cc-47b8-97a3-233399ad3d70.png)
