### ISSUE TITLE
Market participants' ChargeLinks messages which fail schema validation are rejected

### ISSUE THREAD

**Issue by prtandrup** [Energinet-DataHub/geh-charges#920]
**Synopsis:**
We want to schema validate the incoming ChargeLinks messages from market participants to the charge domain to make sure that they follow the expected CIM/XML syntax.

We want to return the result to the caller of our ingestion points synchronously to live up to the markets expectations on when schemas are validated.

**Tech note:**
* Skemavalidering. Titans lever NuGet pakke. De enkelte teams skal hooke det ind, og levere skema der valideres
* Add domain test: Verify a "400 bad request" response upon submitting an invalid CHARGE LINK message

**Acceptance criteria:**
* CIM/XML request change billing master data (links) is schema validated and the result returned to the sender
* Successfully schema validated packages should return success back to sender (HTTP 200 OK)
* Unsuccessful schema validated packages should return failure back to to sender (HTTP 400 Bad Request) including list of schema validation errors
* Sync response must comply to the CIM XML webservice interface documentation (https://energinet.dk/-/media/B4DEEF1CFBAC418C9EA7923FDD38AA45.pdf)
* Validation result is logged to application insight (OK/Failed  + message reference)

![image.png](https://images.zenhubusercontent.com/60bdd871726f411a853d94a9/1a1280a9-3c99-4095-95df-d27b72e5722b)

**Comment by PerTHenriksen** [comment]
blocked by https://github.com/Energinet-DataHub/geh-charges/pull/959

**Comment by defectiveAi** [comment]
Blocked by #990
