### ISSUE TITLE
Ensure correct error texts and codes are used in rejection messages (for charge price list) sent to market participants

### ISSUE THREAD

**Issue by prtandrup** [Energinet-DataHub/geh-charges#922]
**Synopsis:**
As a market participant
I want to receive rejection messages that uses correct error texts and codes.
So that it is clear what went wrong
And the rejection messages are familiar to the ones I'm used to in DataHub2.

**Tech note:**
* Creating the rejection message for a charge price list is already in main, it does however not apply correct error texts and codes, which is needed to be considered valid.
* This is for the async validation of charges only
* English error descriptions are to be used (JST 3/1-'21)
* Error texts are now to support placeholders for dynamically filled variables, contrary to previous decision, where descriptions were dynamical and text static. (JTST &/1-'21)

**Acceptance criteria:**
Given the already implemented validation rules for charge price list requests
When violating any of them
Then the rejection text and code sent in the rejection message to the market partipant
complies with the error code and text provided by (PO and SME)
~~EDIT: the list of error codes and corresponding texts are availble in the internal file: 
https://energinet.sharepoint.com/:x:/r/sites/DH3ART-team/Delte%20dokumenter/General/CIM/Kodelister%20og%20Attributter/Kodeliste%20DH3%20-%20CIM%20inkl.%20att.%20tilknytning.xlsx?d=wc9be2dea8a7f4c20a12ee53bcd944dd9&csf=1&web=1&e=NVP8zq
(filter by TYPE ResponseReasonDescriptionCode)
 ![image.png](https://images.zenhubusercontent.com/60bdf7bbfa2182da7fd5cc6d/8bbb5832-2ca9-437d-a4b5-a1da4aac803a)~~
EDIT 20220106: The list of validation texts is changed to ((https://app.zenhub.com/files/345465244/9fc033f5-4f35-45a1-a557-e8c133da4cde/download)) The file is due for changes, and current story will be updated once a versionized file is shared.

**Comment by HenrikSommer** [comment]
@PerTHenriksen or @IreneDataHub please provide the correct error codes and texts as per AC2.

**Comment by BjarkeMeier** [comment]
@PerTHenriksen, the synopsis seems updated but it's no longer aligned with the title and AC, which should also be updated to make the story clear and unambigous.

**Comment by prtandrup** [comment]
> @PerTHenriksen, the synopsis seems updated but it's no longer aligned with the title and AC, which should also be updated to make the story clear and unambigous.

Given the talk we had Monday during planning, I actually updated the story the same day (title + description). Besides having the source for codes and texts, what would you like to have changed? @BjarkeMeier

**Comment by prtandrup** [comment]
Added another tech note to, hopefully, remove ambiguity.
(the first listed tech note)

**Comment by HenrikSommer** [comment]
MeteringPointId indicated in the validation rule Excel sheet for VR.009 and VR.223 does not make sense. Document ID is used as parameter for errormessages.

**Comment by PerTHenriksen** [comment]
(https://app.zenhub.com/files/345465244/9fc033f5-4f35-45a1-a557-e8c133da4cde/download)

**Comment by prtandrup** [comment]
Added new bug #1068

**Comment by prtandrup** [comment]
added another bug #1070

**Comment by prtandrup** [comment]
Additional two bugs #1071 and #1072

**Comment by prtandrup** [comment]
New story added #1073

**Comment by prtandrup** [comment]
[Test documentation](https://github.com/Energinet-DataHub/geh-charges/files/7905285/ValidationRulesErrorTestResult_Story922.md)
