### ISSUE TITLE
GUI: Sorting Charge Links on StartDate and group by Price ID

### ISSUE THREAD

**Issue by prtandrup** [Energinet-DataHub/geh-charges#929]
Considerations: Sorting done backend?

### AC
Table header shows the sorting (e.g. Date Asc), but not possible to change.

### MD estimate: 1, see relative estimation guidelines in MD [here](https://energinet.sharepoint.com/:w:/s/MightyDucks/EZoinyIGGLdFpO8oZYophKgBpVrsu1NHHOFpWyHkyMm

**Comment by bemwen** [comment]
Estimated: 2
Both if done backend or frontend

**Comment by PerTHenriksen** [comment]
17/12-21 Blocked by: 
https://app.zenhub.com/workspaces/joules-5fd22a1a59e4740018f5ab5a/issues/energinet-datahub/geh-charges/928
