### ISSUE TITLE
Use agreed names and CIM values for Charge Link Data delivered to frontend

### ISSUE THREAD

**Issue by bemwen** [Energinet-DataHub/geh-charges#933]
**Synopsis:**

@Sondergaard has decided that frontend must receive data in agreed names and CIM values. Agreed names are decided by Jan Stie.

The currently agreed names can be found in [this document](https://energinet.sharepoint.com/:x:/r/sites/DH3ART-team/Delte%20dokumenter/General/CIM/Kodelister%20og%20Attributter/CIM%20Mapning%20af%20Attributter%20DH3.xlsx?d=w003873b304554e9fbccc54a45b2b6ca2&csf=1&web=1&e=TRop8K) in column E on tab "RSM - Attributer":
![image.png](https://images.zenhubusercontent.com/60c2e712ae37899de9483e3a/fb8855ec-dad8-46e9-8f78-cd9428ec0655)

The CIM values can be found in [this document](https://energinet.sharepoint.com/:x:/r/sites/DH3ART-team/Delte%20dokumenter/General/CIM/Kodelister%20og%20Attributter/Kodeliste%20DH3%20-%20CIM%20inkl.%20att.%20tilknytning.xlsx?d=wc9be2dea8a7f4c20a12ee53bcd944dd9&csf=1&web=1&e=RZh4AA) on tab "Databub 3.0 - CIM":
![image.png](https://images.zenhubusercontent.com/60c2e712ae37899de9483e3a/d9290346-870c-40dd-8803-5e97d4e60489)

**Tech notes:**

Currently the data the frontend receives from the Charges domain (and BFF) is internal representation of values.
This must be changed to CIM values and agreed names (if the currently used deviates) along the way from backend via BFF to the frontend. 

A similar story has been completed by team Batman in the metering point domain, [here](https://github.com/Energinet-DataHub/geh-metering-point/issues/489).

According to Thomas from Batman, what they've done is:
- use the agreed names (the SME's has an excel sheet with "Ny navngivning for DataHub 3" where the agreed names are located)
- use CIM values (basically enums), should also be located in the same excel file.
- if any agreed names are not allowed by StyleCop, then add the agreed name to allowed names list

**Acceptance criteria:** 
- [ ] AC1: Charge Links data returned by the BFF use CIM values and names dictated by Jan Stie.
- [ ] AC2: The front-end developers have accepted the solution.

**Comment by BjarkeMeier** [comment]
@PerTHenriksen , @prtandrup , @PerLysemose , @Sondergaard, I've made major updates to the story in order to make it clear who is the originator of the story and how to verify solution and also to enable developers to actually pick and solve the story. Please reach out if you have comments.

**Comment by BjarkeMeier** [comment]
It's not in the documents but according to Jan Stie ChargeLink.Factor must be named ChargeOccurrence.

**Comment by prtandrup** [comment]
> It's not in the documents but according to Jan Stie ChargeLink.Factor must be named ChargeOccurrence.

Please verify with Irene that this is correct.

**Comment by Mech0z** [comment]
Same test result as https://github.com/Energinet-DataHub/geh-charges/issues/792

With these variables
1. ChargeOwnerId => ChargeOwner
2. Factor (or Quantity) => Quantity
3. StartDateTimeUtc => StartDate
4. EndDateTimeUtc => EndDate

**Comment by BjarkeMeier** [comment]
For testers of this story:
I've spoken to @frontend-specialisten from the FE developers. He has accepted the naming and approved [the PR](https://github.com/Energinet-DataHub/greenforce-frontend/pull/197) effectively introducing the changes in the BFF.

**Comment by Mech0z** [comment]
Same test result as https://github.com/Energinet-DataHub/geh-charges/issues/792

AC1:
With these variables
1. ChargeOwnerId => ChargeOwner
2. Factor (or Quantity) => Quantity
3. StartDateTimeUtc => StartDate
4. EndDateTimeUtc => EndDate

AC2:
https://github.com/Energinet-DataHub/geh-charges/issues/933#issuecomment-994825395
