### ISSUE TITLE
Store new Production and Special metering points and add default charge links if required

### ISSUE THREAD

**Issue by bemwen** [Energinet-DataHub/geh-charges#936]
**Synopsis**
Currently, the Charges domain is able to consume `ConsumptionMeteringPointCreated` integration events published by the Metering Point domain. This is necessary for being able to assign default charge links to it, and allow market participants to link their charges. 

We want to extend this with `Production` and `Special` metering points, but we are aware of the Metering Point domain team being in progress of deprecating the `ConsumptionMeteringPointCreated` integration event and creating a new integration event to be use for any type of metering point being created (see the registered dependency).

With this story, we 
* Stop using the `ConsumptionMeteringPointCreated`
* Start consuming the new integration event for any metering point type created
* Extend our flow to store `Production`, `Special` as well as `Consumption` metering points.
* Ensure `default charge links` are created for `Consumption` and `Production` metering points 
(Currently no special metering points require default charge links, except the `Electrical heating` metering point type. This type is however considered out of scope, as creating electrical heating metering point is not implemented, yet, but will probably be published as part of the new integration event later)
* Ensure `notification` about default charge links are sent out to Grid Access Provider (if tax) 
* Ensure providing the Metering Point domain a `CreateDefaultChargeLinksReply` about passing/failing the creation of default charge links.

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/7c610df7-68c2-4a91-8663-b4652fc8b747)

**Acceptance criteria:**
- [ ] AC1:
Given the Metering Point domain published a `metering point created` integration event for (`Consumption`/`Production`/`Special`)
When the Charges domain consumes it
Then the Metering Point is stored
<br>

- [ ] AC2: 
Given a new `Consumption` or `Production` metering point has been stored
When the Metering Point domain makes a `CreateDefaultChargeLinks` request for it
Then `default charge links` are created
And the grid access provider is notified about any tax tariff charge links created
And a `CreateDefaultChargeLinks (success)` reply is sent back to the Metering Point domain
<br>

- [ ] AC3:
Given a new `Special` metering point has been stored
When the Metering Point domain makes a `CreateDefaultChargeLinks` request for it
Then **no** `default charge links` are created
And a `CreateDefaultChargeLinks (success)` reply is sent back to the Metering Point domain
<br>

- [ ] AC4: 
Given a `Production` metering point has been stored and default charges have been linked
When looking up the metering point in the Frontend
Then the linked charges are displayed under the "Priser" tab.

**Comment by prtandrup** [comment]
Re-refined so it matches that the Metering Point domain will provide a single integration event for any type of metering point being created.

**Comment by prtandrup** [comment]
### Tested in progress...

#### Tested in U-001

- [x] AC1:
Given the Metering Point domain published a `metering point created` integration event for (`Consumption`/`Production`/`Special`)
When the Charges domain consumes it
Then the Metering Point is stored

* Consumption MP created: `573481500325272187` (Grid Access Provider: `8200000001409`)

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/271dbb0a-aac6-42cf-a156-8affb3b241c7)

* Production MP created: `572065631381039878` (Grid Access Provider: `8200000001409`)

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/c26d0a19-e763-4469-b67b-09efe2508b30)

* Special MP created: `579464367205384126`  (Grid Access Provider: `8200000001409`)

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/74209ae3-991f-4070-b66d-a70e6fefed71)

**Comment by prtandrup** [comment]
Strange behavior appeared while testing AC#2.

Apparently default charge links were set on Production MP ID ´572065631381039878´

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/dc68c6c1-06a8-4edd-a4e3-cfd2d2055e53)

However the subsequent flow seems to be a rejection flow, as the link command seems to be violating our temp validation rule for not allowing charge link updates.

````
{
	"ChargeLinksCommand": {
		"MeteringPointId": "572065631381039878",
		"Document": {
			"Id": "fc7663a3-40e0-4bce-8bde-059c0b4b4618",
			"RequestDate": "2022-01-24T12:55:20.0970054Z",
			"Type": 1,
			"CreatedDateTime": "2022-01-24T12:55:20.0970054Z",
			"Sender": {
				"Id": "5790000432752",
				"BusinessProcessRole": 3
			},
			"Recipient": {
				"Id": "5790001330552",
				"BusinessProcessRole": 7
			},
			"IndustryClassification": 1,
			"BusinessReasonCode": 1
		},
		"ChargeLinks": [
			{
				"OperationId": "95ef4d37-cb2b-405a-8aff-d9d6e7485777",
				"StartDateTime": "2022-01-24T12:50:54.5885129Z",
				"EndDateTime": "9999-12-31T23:59:59Z",
				"SenderProvidedChargeId": "40010",
				"Factor": 1,
				"ChargeOwnerId": "5790000432752",
				"ChargeType": 3
			},
			{
				"OperationId": "65641b7a-2c1f-4b8f-af28-23fa0f5e401d",
				"StartDateTime": "2022-01-24T12:50:54.5885129Z",
				"EndDateTime": "9999-12-31T23:59:59Z",
				"SenderProvidedChargeId": "45012",
				"Factor": 1,
				"ChargeOwnerId": "5790000432752",
				"ChargeType": 3
			}
		],
		"Transaction": {
			"MRID": "4da471b92c09418a8ca54fa7e5e7ed2a"
		}
	},
	"ValidationErrors": [
		{
			"ValidationRuleIdentifier": 28,
			"TriggeredBy": null
		},
		{
			"ValidationRuleIdentifier": 28,
			"TriggeredBy": null
		}
	],
	"PublishedTime": "2022-01-24T12:55:20.2301815Z",
	"Transaction": {
		"MRID": "961be6ce6c3045e7bf12962ea69484b2"
	}
}
````
Further analysis is ongoing.

**Comment by prtandrup** [comment]
### Tested in U-001 (due to some token challenges in T-001)

- [x] AC1:
Given the Metering Point domain published a `metering point created` integration event for (`Consumption`/`Production`/`Special`)
When the Charges domain consumes it
Then the Metering Point is stored

**Consumption MP: "571913019395893869"**
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/64cad49a-36d4-4bfb-9455-cd47bab6f273)

**Production MP: "576383363981805775"**
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/8091cfd5-a35d-4378-b1ad-83f895058933)

**Special MP: "570272189830693729"**
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/f62b2b9d-335d-4d48-97b4-b768e8eabfc8)

**Comment by prtandrup** [comment]
### Tested in U-001

Note: New Metering Point ID's than AC1.

- [x] AC2: 
Given a new `Consumption` or `Production` metering point has been stored
When the Metering Point domain makes a `CreateDefaultChargeLinks` request for it
Then `default charge links` are created
And the grid access provider is notified about any tax tariff charge links created
And a `CreateDefaultChargeLinks (success)` reply is sent back to the Metering Point domain
<br>

<hr>
**Consumption MP: "570612370902641562"**
<hr>
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/8567da7a-f649-49e7-9f69-ae3cf1d65632)

````
<?xml version="1.0" encoding="utf-8"?>
<cim:NotifyBillingMasterData_MarketDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:cim="urn:ediel.org:structure:notifybillingmasterdata:0:1" xsi:schemaLocation="urn:ediel.org:structure:notifybillingmasterdata:0:1 urn-ediel-org-structure-notifybillingmasterdata-0-1.xsd">
    <cim:mRID>9a9db852038c496cb3a23d3974edadbf</cim:mRID>
    <cim:type>D07</cim:type>
    <cim:process.processType>D17</cim:process.processType>
    <cim:businessSector.type>23</cim:businessSector.type>
    <cim:sender_MarketParticipant.mRID codingScheme="A10">5790001330552</cim:sender_MarketParticipant.mRID>
    <cim:sender_MarketParticipant.marketRole.type>DDZ</cim:sender_MarketParticipant.marketRole.type>
    <cim:receiver_MarketParticipant.mRID codingScheme="A10">9656626091925</cim:receiver_MarketParticipant.mRID>
    <cim:receiver_MarketParticipant.marketRole.type>DDM</cim:receiver_MarketParticipant.marketRole.type>
    <cim:createdDateTime>2022-02-03T09:25:45Z</cim:createdDateTime>
    <cim:MktActivityRecord>
        <cim:mRID>0a5f07d5f929402ca9c5d753e3cadaeb</cim:mRID>
        <cim:marketEvaluationPoint.mRID codingScheme="A10">570612370902641562</cim:marketEvaluationPoint.mRID>
        <cim:start_DateAndOrTime.dateTime>2022-02-03T09:23:22Z</cim:start_DateAndOrTime.dateTime>
        <cim:ChargeGroup>
            <cim:ChargeType>
                <cim:chargeTypeOwner_MarketParticipant.mRID codingScheme="A10">5790000432752</cim:chargeTypeOwner_MarketParticipant.mRID>
                <cim:type>D03</cim:type>
                <cim:mRID>EA-001</cim:mRID>
                <cim:factor>1</cim:factor>
            </cim:ChargeType>
        </cim:ChargeGroup>
    </cim:MktActivityRecord>
</cim:NotifyBillingMasterData_MarketDocument>
````

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/87322a74-224c-4e9b-a625-23c279bd1a7c)

<hr>
**Production MP: "572719069371839148"**
<hr>

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/6b1bf0dc-16cb-48fb-b009-40717211f799)

Above charge links are not tax, hence no message to grid access provider.

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/1e8c7c14-6a76-4fa4-a10b-aef01850b45e)

**Comment by prtandrup** [comment]
### Tested in U-001

- [x] AC3:
Given a new `Special` metering point has been stored
When the Metering Point domain makes a `CreateDefaultChargeLinks` request for it
Then **no** `default charge links` are created
And a `CreateDefaultChargeLinks (success)` reply is sent back to the Metering Point domain
<br>

Special Metering Point persisted in Charges:

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/ea0b6daf-af73-4acb-a700-b6741a47382d)

And no default Charge Links created:

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/1dbae604-7986-4675-b1bc-5691d22dd7eb)

Reply back to the Metering Point domain:

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/0a1829d1-ab33-49b1-87f0-e52dcc8123d1)

**Comment by prtandrup** [comment]
### Tested in U-001

- [x] AC4: 
Given a `Production` metering point has been stored and default charges have been linked
When looking up the metering point in the Frontend
Then the linked charges are displayed under the "Priser" tab.

<hr>

**Production MP ID: `572719069371839148`**

<hr>

In Frontend:

![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/99cc664e-410a-4c4a-87b3-9d90b43cfcb7)

OBS: I've observed an unexpected link start date (03-02-2022), expected (01-01-2022), and a quick analysis show that the metering point is persisted in the Charges domain with an incorrect effective date. Seems to be today's date. Will investigate.

I consider the story to be tested OK.
