### ISSUE TITLE
VR: ChargeLinks update and stop requests are rejected via new validation rule

### ISSUE THREAD

**Issue by bemwen** [Energinet-DataHub/geh-charges#938]
**Synopsis**
Given that functionality for updating and stopping a **ChargeLink** is not available when we let external parties start testing, we've decided to implement a temporarily validation rule that rejects any update or stopping requests.

This validation will be checking if an incoming request's charge link period overlaps an existing charge link period (for same charge and metering point combination), if so => reject.

**Tech notes:**

* Validation rule setup has not been made for charge links yet
* Even though it is not the intention in the long run, it is currently possible to submit a charge link with an end date which will not be rejected by this rule. E.g.
Existing Charge Link with start = 01/01/2022
Same charge link submitted with start and end dates = 01/11/2021 - 01/12/2021 (accepted)
* Domain test should be updated by adding 1 failing charge link resulting in 3 message types being received by MessageHub (Rejected, Accepted and the 2 charge links)

**Tech Tasks**
~~- [ ]  (1) And why do we use ProtoBuf internally? Is it still an architect requirement?~~

~~- [ ]  (2) Only one contract. Example:    ChargeCommand = ChargeCommandReceived = ChargeCommandAccepted =     ChargeCommandRejected.ChargeCommand.~~

~~- [ ]  (3) Don't repeat enums in contracts Use int's for enum values and just cast on both sides (serialization and deserialization).~~

~~- [ ]  Make protobuf Decimal a shared type (get Søren (SA) to sign off on namespace)~~

- [x]  Ensure that any function or queue/topic name related to the Default Charge Links flow, has links in plural and 'default' included in their name, so it's clear that they are related to this sub process and may include multiple links.

- [x]  Swith to Json on internal events in Charges domain

- [x] Cleanup files used to send Protobuf internally in Charges domain

- [x] Add unit test to ensure switch on BundleType enum in BundleCreatorProvider is always complete

- [x] Create meaningful reject messages to market participants for all validation rules

**Acceptance Criteria:**
AC 1 Update and stops are not supported, and will be handled by an added validation rule, with an error text reflecting this.
AC 2: New validation rule to be added to general validation rule excel sheet and to overview on GitHub

**Comment by lasrinnil** [comment]
@HenrikSommer and I have discussed the Json / Protobuf usage internally in the Charges domain. We found the existing overhead of maintaining the existing internal protbuf contracts and their mappers etc, are quite high. And would only grow in the future. So we think it would be beneficial to switch to Json internally.

**Comment by HenrikSommer** [comment]
Following the shift to json-serialization internally in the charges domain, the DecimalValue is now only represented once, hence that issue is now a non-issue.

**Comment by IreneDataHub** [comment]
Har oprettet en bug, da jeg ikke modtager en afvisning efter jeg indsender en prislink med start/Stop. Jeg kan se, at beskeden modtages og vises på MP/GUI men den danner en ny linje, hvor jeg forventede at den havde over skrevet samme tarif eller afvist da stop og opdatering af ude af scope.

**Comment by prtandrup** [comment]
Blocked by #1087

**Comment by IreneDataHub** [comment]
[https://app.zenhub.com/files/345465244/49e94fa9-8346-4bac-bdbf-f89d88f7324e/download](https://app.zenhub.com/files/345465244/49e94fa9-8346-4bac-bdbf-f89d88f7324e/download)

**Comment by IreneDataHub** [comment]
Receive reject = OK
<cim:text>Charge ID U-001Id01 for owner 9656626091925 of type Subscription cannot yet be updated or stopped. The functionality is not implemented yet.</cim:text>

But the text could be more specific. ( specify meteringpoint and change charge to chargelink)

eg:
<cim:text>Chargelink ID "U-001Id01" for owner 9656626091925 of type Subscription can't be updated or stopped for meteringpoint "571254147033029296". The functionality is not implemented yet.</cim:text>

**Comment by IreneDataHub** [comment]
I have made a new test after the reject text has been change so it is more specific.
cim:textCharge link for metering point ID 5725202 and Charge with ID AbonnId01 for owner of type cannot yet be updated or stopped. The functionality is not implemented yet.</cim:text>

Everything is do as I expect and the bug can be closed

**Comment by IreneDataHub** [comment]
Test 1087 ok.
ChargeLinks update and stop requests are rejected via validation rule

![image.png](https://images.zenhubusercontent.com/612f6568004bdd03eab7ca46/c7209837-e54e-451e-8f93-a1a4ac6ed727)
