### ISSUE TITLE
Update process flow diagrams for Charge Price List Flow

### ISSUE THREAD

**Issue by bemwen** [Energinet-DataHub/geh-charges#939]
This story is about bringing the following process flows up to date with implementation: 
* Charge Price List Flow

Located [here](https://github.com/Energinet-DataHub/geh-charges/tree/main/docs/process-flows).

**Acceptance criteria:**
- [x] 1 Process flow diagram and associated text have been updated to reflect current implementation, [link](https://github.com/Energinet-DataHub/geh-charges)
- [ ] 2 Charge Price Architecture drawing updated to current implementation, [link](https://github.com/Energinet-DataHub/geh-charges/tree/main/docs/process-flows#Process-Flow-For-Charge-Information-And-Charge-Prices)

**Comment by prtandrup** [comment]
Ready for testing. Documentation links are located next to the ACs.
