### ISSUE TITLE
Tech: Add global.json to pin .Net Core SDK version

### ISSUE THREAD

**Issue by HenrikSommer** [Energinet-DataHub/geh-charges#949]
**Synopsis**

A global.json file can pin the .Net Core SDK version used to build and thereby avoid any confusion as to which version is used.

**Acceptance criteria**
- [x] global.json is added to pin the .Net Core SDK for all .Net solutions in Charges and Timeseries domains

**Comment by prtandrup** [comment]
Tested OK ✅ 

**global.json in GreenEnergyHub.Charges:** <br>
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/95ebdf2e-c60a-40b2-a849-593c80c078f2)

**global.json in Energinet.Charges.Libraries:** <br>
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/db94264a-91e1-4017-b517-7f49c62ad0cc)

**global.json in GreenEnergyHub.TimeSeries:** <br>
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/eb0651f0-a2ee-422d-bd2d-f690d677926c)

**global.json in GreenEnergyHub.TimeSeries.Integration:** <br>
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/b659d7e2-0306-4c17-a47e-c9281265f7c0)

And it's using the latest available version SDK:
![image.png](https://images.zenhubusercontent.com/60ae42d0916bb92d8b000901/c22bddbf-b09a-4932-9759-9643f5b4fe7f)
