### ISSUE TITLE
Charge ADR's are outdated, and needs to reflect current state and architecture

### ISSUE THREAD

**Issue by PerTHenriksen** [Energinet-DataHub/geh-charges#969]
**Synopsis:**
Update: Story is about cleaning up existing ADRs, not replacing them with updated ones. Yet. 

As a market participant
I want the ADR documentation of the charge and time series domain to reflect the current choices
So that I am not confused by the ADRs stating something which is no longer correct

ADRs are located [here](https://github.com/Energinet-DataHub/green-energy-hub/tree/main/docs/architecture-decision-record).

**Acceptance criteria:**

* Charges ADR-001 must be proofread and either approved in this story as is, or updated with needed changes.
* Charges ADR-002 must be updated or replaced by another ADR to reflect the current status (currently entirely wrong)
* Charges ADR-003 must be proofread and either approved in this story as it, or updated with needed changes.
* Charges ADR-004 must be updated or replaced by another ADR to reflect the current status (current outcome is wrong)
* README.md must link to the existing ADRs afterwards and include information about retired ADRs for the ease of the reader

**Comment by PerLysemose** [comment]
No requirements from Green ART in terms of maintenance. Hence this story is closed as we consider our documentation as sufficient.
